### PR TITLE
Collapsible left and right sidebars.

### PR DESCRIPTION
**Pull request by wldcordeiro**
Issue #426 - I had an idea in the issue that I went with here. Collapse is done by double clicking the sidebars. Styling is still WIP.

I'll record a video shortly @jasonLaster 

screenshot_20160830_095353
screenshot_20160830_095421

### CODE REVIEW

**Comment by helenvholmes** [comment]
Hey Wellington, 

I think we'd like to add a small animation to the expand/collapse icon as well, if you have the time: https://cl.ly/3q2C1w1b3U0e

(I can also open a new bug for it.)

The icon in the .mov is different from the icon you added—that's because the animation was comp'd when we had older icons, but the idea is still the same for how we want it to animate :)

**Comment by wldcordeiro** [comment]
@helenvholmes Here's a little video. https://www.dropbox.com/s/3kq2b98l5fuc8dl/collapse-sidebar.mp4?dl=0

**Comment by jasonLaster** [comment]
Hey @wldcordeiro what's the status here? I'm not sure if you're looking for a review

**Comment by wldcordeiro** [comment]
@jasonLaster I was awaiting @helenvholmes response, in the issue she had asked me for a video to show what I meant, I'm working on the styling to use the svg provided though (I still like the idea of just increasing the width of the `Draggable` by 1-2px and adding the double click to it as an additional way to collapse. 😄

**Comment by jasonLaster** [comment]
Cool. Did you get Helens message with the svgs?

**Comment by helenvholmes** [comment]
Based on your commit messages (I haven't pulled this down), looks like we ended up going with what's currently in the tools? (https://cl.ly/3S0B1D210I1T ?)

**Comment by clarkbw** [comment]
@wldcordeiro I think you're missed adding the new files, SidebarHeader etc. 🙀 😸

**Comment by wldcordeiro** [comment]
@clarkbw I have a local commit I was working on that I hadn't pushed up yet. 😆

**Comment by jasonLaster** [comment]
thanks @wldcordeiro 

Couple things:
+ i noticed that clicking on the collapsey thing did not work. Could it be a bug?
+ i believe the buttons should be on the other side of the draggable? This might be an issue with how you've setup the headers?
+ Could we do the double click behavior in a later PR? I think this is adding a lot to this PR and making it hard to review.

**Comment by wldcordeiro** [comment]
>  i noticed that clicking on the collapsey thing did not work. Could it be a bug?

Not yet implemented, just putting the skeleton there since it was going in a new component.

> i believe the buttons should be on the other side of the draggable? This might be an issue with how you've setup the headers?

Do you mean they should be in the tab bar area rather than in the sidebar?

> Could we do the double click behavior in a later PR? I think this is adding a lot to this PR and making it hard to review.

Sure.

**Comment by wldcordeiro** [comment]
@helenvholmes where would it be preferred to put the collapse buttons? In the sidebar headers like this? Or in the tab bar?

screenshot_20160901_154403

**Comment by jasonLaster** [comment]
One reason I mentioned putting the button in the center is that the header realestate is more valuable. I.e I like the debugger buttons on the left and we have copy for the right side of the sources header.

**Comment by jlongster** [comment]
I agree with Jason, I think where it is in that screenshot is too prominent. A few notes:

* @helenvholmes we talked about the idea of not having any icons, but a "gesture" where if the user slides it far enough in that it just collapses. Have we tried that? I guess there is the problem of how to open it back up.
* Is it just me or does the icon seem darker then the rest of the icons?  Or is it just thicker?
* I suppose we could copy Chrome and put them in the editor header...

I thought I had another question but I forget. It's awesome to see this worked on, thanks @wldcordeiro !

**Comment by jlongster** [comment]
Oh, I remember: in https://bugzilla.mozilla.org/show_bug.cgi?id=1260552 Honza has ported our Draggable and SplitBox components to m-c. But we're modifying Draggable... I suppose it's ok and we'll just deal with it when we try to copy back his new SplitBox which has a bunch of new stuff.

**Comment by jlongster** [comment]
Also, one last thing (sorry): any reason the width of the splitter is increased a lot? Can we keep it consistent with the rest of the borders but just make the clickable area as big as you want it?

**Comment by helenvholmes** [comment]
> @helenvholmes we talked about the idea of not having any icons, but a "gesture" where if the user slides it far enough in that it just collapses. Have we tried that? I guess there is the problem of how to open it back up.
I don't think we could have the gesture without the icon; with the icon, you click the icon, that opens it back up.

**Comment by wldcordeiro** [comment]
Calling PR bankruptcy on this one and will reopen from another branch based on discussion above. 👍

**Pull request closed without merging**
