### PR TITLE
Add ctrl+shift+f hint

### PR DESCRIPTION
**Pull request by nyrosmith**
Associated Issue: #3708 

search

### CODE REVIEW

**Comment by darkwing** [comment]
Awesome contribution @nyrosmith!  I think one of your other PRs accidentally got added with this change too :)

**Comment by nyrosmith** [comment]
Thx! You are absolutly right and I'll fix this during  the weekend

**Comment by jnachtigall** [comment]
@nyrosmith Great, thanks :) Nitpicking as seeing the screencast though ;) I think for readability it would be better if the text was left-aligned centered. That is like:

```
          Ctrl+P to search for sources
          Ctrl+Shift+F to find in files
```

instead of
```
           Ctrl+P to search for sources
             Ctrl+Shift+F to ...
```

**Comment by nyrosmith** [comment]
I'd prefer a new one. This PR is still useful and fits the issue...
A new issue would also be a good first one for new contributors

**Comment by codehag** [comment]
Great! merging :) new issue is here: #3734

**Pull request merged**
