### PR TITLE
Avoid allow text selection in secondary panels - Fix #5762

### LINKED ISSUE #5762: [SecondaryPane] should not allow text selections
STR
1. add a breakpoint
2. select the breakpoint and drag your mouse down 

:/

### PR DESCRIPTION
**Pull request by AngelFQC**
Fixes Issue: #5762

Should not allow text selections 

Example test plan:

- add a breakpoint
- select the breakpoint and drag your mouse down

### CODE REVIEW

**Comment by jasonLaster** [comment]
@AngelFQC can you update the title / description to be more descriptive?

**Comment by AngelFQC** [comment]
Done

**Comment by darkwing** [comment]
Excellent work @AngelFQC !!!!  Thank you so much for your help!

**Comment by AngelFQC** [comment]
Thank you @darkwing

**Pull request merged**
