### PR TITLE
Remove active tab border

### PR DESCRIPTION
**Pull request by wldcordeiro**
Closes issue #661 

## Screenshot

screenshot_20160919_212930

### CODE REVIEW

**Comment by jlongster** [comment]
Hardcoding the height seems like it might cause issues on various platforms; are we sure it's `24px` on all platforms, with subtle font rendering differences, etc? How did you get 24? I don't see 23 hardcoded anywhere and I assume this just needs to make it 1px taller to overlap the border.

**Comment by wldcordeiro** [comment]
@jlongster I'm not a big fan of hardcoding it either, `23` was hardcoded here though, https://github.com/wldcordeiro/debugger.html/blob/92b582e80174f0b821f823652fdd101765927334/public/js/components/SourceTabs.css#L19

**Comment by jlongster** [comment]
I see, ok, that makes sense.

**Comment by jasonLaster** [comment]
@wldcordeiro mind updating the branch, or giving us write permissions

**Comment by wldcordeiro** [comment]
@jasonLaster rebased onto master.

**Pull request merged**
