### PR TITLE
Return what was mapped in mapExpression.

### PR DESCRIPTION
**Pull request by nchevobbe**
In `mapExpression`, we now return an object instead of the mapped expression directly.
The object contains the mapped expression, as well as a `mapped` object containing
all the mapping the happened on the expression or not (await, originalExpression, bindings).

We take this as an opprtunity to clean-up `mapAwaitExpression`:
 - the default exported function is renamed to `mapTopLevelAwait` to match other mapping functions
 - we add a `.catch` in which we `console.error` to catch any promise rejection or Exception.

### CODE REVIEW

**Comment by nchevobbe** [comment]
the returned `mapped` object will be used in the console to *not* print the Promise we create by wrapping the await in an async function.

**Comment by nchevobbe** [comment]
Travis is rightfully not happy since the change here would need some modifications in mozilla-central

**Comment by nchevobbe** [comment]
> I'm not sure if doing a string comparison is correct because the transform can re-format the expression, but not change its meaning

Yeah I know. In the test for example, there are some cases that go from `a` to `a;`, so it's marked as mapped, but ideally should not.

**Comment by jasonLaster** [comment]
JSTerm is getting a bad result: 
https://searchfox.org/mozilla-central/source/devtools/client/webconsole/components/JSTerm.js

This looks alright:
https://github.com/devtools-html/debugger.html/blob/master/assets/panel/panel.js#L100

**Comment by jasonLaster** [comment]
this should help

```diff
diff --git a/src/workers/parser/mapOriginalExpression.js b/src/workers/parser/mapOriginalExpression.js
index efb9955..ad9afe0 100644
--- a/src/workers/parser/mapOriginalExpression.js
+++ b/src/workers/parser/mapOriginalExpression.js
@@ -42,7 +42,7 @@ export default function mapOriginalExpression(
 ): string {
   const ast = parseScript(expression, { allowAwaitOutsideFunction: true });
   const scopes = buildScopeList(ast, "");
-
+  let shouldUpdate = false;
   const nodes = new Map();

   const replacements = new Map();
@@ -94,9 +94,14 @@ export default function mapOriginalExpression(

     const replacement = replacements.get(locationKey(node.loc.start));
     if (replacement) {
+      shouldUpdate = true;
       replaceNode(ancestors, t.cloneNode(replacement));
     }
   });

+  if (!shouldUpdate) {
+    return expression;
+  }
+
   return generate(ast).code;
```

**Pull request merged**
