### PR TITLE
[Telemetry] Fixed telemetry import to point at devtools module using transform-mc.js

### PR DESCRIPTION
**Pull request by MikeRatcliffe**
Fixed telemetry import to point at devtools module using transform-mc.js

### CODE REVIEW

**Comment by MikeRatcliffe** [comment]
This should fix it.

**Comment by jasonLaster** [comment]
Looks good. I'll test it a bit and then we can land it

**Comment by jasonLaster** [comment]
feel free to merge if you're happy with this

**Comment by MikeRatcliffe** [comment]
I'm happy with it but can't merge it without a review.

**Pull request merged**
