### PR TITLE
adding DocSearch to the site

### PR DESCRIPTION
**Pull request by s-pace**
Following https://help.github.com/articles/customizing-css-and-html-in-your-jekyll-theme/

Fixes Issue:#5338 

Help #5047

Here's the Pull Request Doc
https://devtools-html.github.io/debugger.html/CONTRIBUTING.html#pull-requests

### Summary of Changes

I am [working at DocSearch](https://community.algolia.com/docsearch/) and we would love to help you super project!

### Screenshots/Videos (OPTIONAL)

You can try it here:

http://debugger-docsearch.surge.sh/

Let me know if you have any feedback

### CODE REVIEW

**Comment by s-pace** [comment]
cc @jasonLaster :)

**Comment by s-pace** [comment]
You are right.

Done ✅

**Comment by jasonLaster** [comment]
does this work for you
debugger-docsearch.surge.sh

**Comment by s-pace** [comment]
Now yes, surge had a bad time

**Comment by jasonLaster** [comment]
it's working for me too!

Could we move the search bar into the header so it is available on other pages too?

**Comment by jasonLaster** [comment]
also, did you have a good way of testing this locally, like jekyll start?

**Comment by s-pace** [comment]
Since it is included into the template it will be available everywhere.

No I don't have a proper way so far

**Comment by jasonLaster** [comment]
strange, i didn't see it here: http://g.recordit.co/QfTiruwKF9.gif

**Comment by s-pace** [comment]
Because you are redirected to the official website. It is only a showcase on the first page

**Comment by jasonLaster** [comment]
Great work!

**Comment by s-pace** [comment]
So huge! 

Thanks

**Pull request merged**
