### PR TITLE
[L10N] Fix hardcoded strings

### PR DESCRIPTION
**Pull request by viswanathamsantosh**
Associated Issue: #<1143>

### Summary of Changes

*Replaced a hardcoded string using L10N strings from debugger.properties 

### Testing

* [29 ] passes `npm test`
* [ ] passes `npm run lint`
 
My First merge request to this project! I was unable to run `npm run lint on my system so couldn't update the number of passes.

### CODE REVIEW

**Comment by jasonLaster** [comment]
Thanks!

**Comment by jasonLaster** [comment]
@viswanathamsantosh just rebased your branch. Hopefully it'll pass CI soon and we can merge!

**Comment by jasonLaster** [comment]
@viswanathamsantosh found the bug [here](https://github.com/devtools-html/debugger.html/pull/1175/files#diff-2cf5ca54ef1aa18d5ca2f259e62142eaR15).

We'll be removing the need for strings.json soon :) [here](https://github.com/devtools-html/debugger.html/issues/1030). In fact if you wanted to get some practice with webpack loaders, you could do it too!

**Comment by viswanathamsantosh** [comment]
Awesome! Thanks jason. I will look into webpack loaders. \o/

**Comment by jasonLaster** [comment]
Awesome! I've been doing lots of webpack in the past month, so if you have any questions let me know. The issue has a branch with my first attempt, which was just 20 minutes of messing around. 

I recommend adding console logs to the node_module/webpack-loader-x you're playing with! Also, don't be afraid of webpack's internals it's just a fancy lifecycle game with compiler jargon. Also, there are plenty of more gratifying issues in the up for grabs, this is especially gnarly, so don't take to bad if it's hard / weird!

**Pull request merged**
