### PR TITLE
refactored loading states & added loading in outline

### PR DESCRIPTION
**Pull request by Rohanhacker**
### Summary of Changes

*  Refactor the loading state of symbols #5554
* Should show a loading message in outline #5267

### CODE REVIEW

**Comment by jasonLaster** [comment]
I'm seeing some issues w/ the mochitests in travis like: `variables is undefined: formatSymbols`

**Comment by Rohanhacker** [comment]
Will look into it. I thought it was timing out for some reason.

**Comment by jasonLaster** [comment]
Hey @Rohanhacker i made some tweaks earlier. Looks like it is causing some issues which i can touch up tomorrow

**Comment by jasonLaster** [comment]
alright, i feel pretty good about this. take a look at the tweaks and let me know what you think

**Comment by Rohanhacker** [comment]
@jasonLaster Thanks

**Pull request merged**
