### PR TITLE
Test symbol extraction for async/exported functions

### PR DESCRIPTION
**Pull request by frigus02**
Associated Issue: #3158

### Summary of Changes

* Add examples of export, async and export async functions to the func.js parser tests.
* Update the corresponding snapshot files.

### CODE REVIEW

**Comment by jasonLaster** [comment]
just noticed that jumpTo now has functions like exFoo!

screen shot 2017-08-01 at 3 35 36 pm

**Comment by frigus02** [comment]
Uh, that's neat. Seems like there's no support for async functions yet, though :-)

**Comment by jasonLaster** [comment]
oh neat, it's good that we established the baseline. 

That'll be good to add :)

We have tons of async functions in debugger.html

**Comment by frigus02** [comment]
Oh, I meant the GitHub "Jump to..." feature does not recognize async functions yet. The debugger.html does recognize them.

**Comment by jasonLaster** [comment]
haha - that's hilarious. We're one step ahead of the pack.

We're also ahead of atom function search :)

**Pull request merged**
