### PR TITLE
File Search on All platforms

### LINKED ISSUE #533: Cmd+P keyboard shortcut for Windows
Currently, the keyboard shortcut to toggle file search is (Cmd+P) which works perfectly on OSX. But I suspect, it will not work Windows as it does not have the Cmd key.
We need to add additional listener for the corresponding Windows key shortcut (Ctrl+P) to toggle file search.
We should also modify the welcome screen copy to reflect that change for Windows users.
screen shot 2016-08-10 at 11 41 40 pm
thoughts @jasonLaster?

### PR DESCRIPTION
**Pull request by wldcordeiro**
Fixes #533 making it so the shortcut works on non-OSX devices and shows the appropriate message for the platform.

### CODE REVIEW

**Comment by jlongster** [comment]
Great job! This looks good to me, although I'm not sure what our shimmed Services does locally. I bet it just hardcodes Mac as the platform. But we shouldn't deal with that here.

**Comment by jlongster** [comment]
Not sure about the consistent cypress errors. I've never seen those ones and almost every test is failing, but it can't be because of this PR. Any ideas @jasonLaster?

**Comment by wldcordeiro** [comment]
@jlongster yeah, I asked about the best way to determine the platform and @jasonLaster suggested using the `Services` lib.

**Comment by wldcordeiro** [comment]
@jlongster Looking at CI we get this error

`CypressError: Timed out retrying: Expected to find element: '.autocomplete input', but never found it.`

**Comment by jbhoosreddy** [comment]
from my understanding from the [webpack.config](https://github.com/devtools-html/debugger.html/blob/master/webpack.config.js#L43-L46), Services library is taken from devtools instead of devtools sham, so it should work. [Services](https://github.com/devtools-html/debugger.html/blob/master/public/js/lib/devtools/client/shared/shim/Services.js#L484-L497)

 But yes, devtools-sham simply assumes it to be OSX.

**Comment by jasonLaster** [comment]
Looks like a good change. I wouldn't be surprised if this change did break the cypress tests as they use file search to navigate to a source.

The best thing to do here is to run [cypress](https://github.com/devtools-html/debugger.html/blob/master/docs/integration-tests.md#installing-cypress) locally. Happy to look into it as well.

**Comment by wldcordeiro** [comment]
So my phone is dead, and Cypress wants me to log into Github which needs 2FA so I can try later in that case. 😐

**Comment by jasonLaster** [comment]
Actually, you're changes run perfectly locally. I'm going to rebuild circle and see if the test failures are just on CI

**Comment by jasonLaster** [comment]
You should be good. I bet we'll merge soon :) 

Thanks for the help

**Comment by jasonLaster** [comment]
You know, the second test failed too.

What i think is happening is that we're firing cmd on a linux box


[cmd](https://github.com/wldcordeiro/debugger.html/blob/file-search-all-platforms/public/js/test/cypress/commands/debugger.js#L65-L66). I'm going to play with this on CI, by building w/ ssh [here](https://circleci.com/gh/devtools-html/debugger.html/679) and will report back. Feel free to do the same

**Comment by jasonLaster** [comment]
Closing this so that I can merge a fix for the platform event.

**Pull request closed without merging**
