### PR TITLE
immutable variable hover

### PR DESCRIPTION
**Pull request by samuel-peers**
### Summary of Changes

* check if variable is an Immutable
* show "Immutable" in the header
* filter relevant roots (`tail`, `root`, and `size`)

### Screenshots
Before:
immutable_before

After:
immutable_after_map
immutable_after_list

### CODE REVIEW

**Comment by jasonLaster** [comment]
This is a great start!

Here's my next question, 
1) is there an easy way to show the immutable type in the header "List"
2) is there a way to format the list so it looks like an array or a map looks like an object
3) can we throw a small immutable logo in the header :P

**Comment by samuel-peers** [comment]
immutable_logo_list
immutable_logo_map
immutable_logo_stack

**Comment by samuel-peers** [comment]
> is there a way to format the list so it looks like an array or a map looks like an object?
I couldn't find an easy way to do this :/ I think `ObjectInspector` would have to be modified

**Comment by jasonLaster** [comment]
Hmm one thought would be to load root and use that as the OI roots lol. Naming collision

**Comment by samuel-peers** [comment]
immutable_entries
immutable_entries_expanded

**Pull request merged**
