### PR TITLE
QuickOpen File Search rows can be quite tall

### PR DESCRIPTION
**Pull request by marcogallo566**
Fixes Issue: #5630

Here's the Pull Request Doc
https://devtools-html.github.io/debugger.html/CONTRIBUTING.html#pull-requests

### Summary of Changes

* Now the path is in the same line of the filename
* Added truncation to filename and path

Here's the Debugger's Testing doc
https://docs.google.com/document/d/1oBMRxV8A2ag2t22YsQOxTdEv0mXKzIg0tggJjRkU1S0/edit#.
Feel free to improve it!

### Screenshots
c02ca444-6b3a-4f34-8541-d21d546fe6e1

### CODE REVIEW

**Comment by darkwing** [comment]
@violasong Do you have an opinion on this?  I'm thinking the file name should be right-justified.

**Comment by jasonLaster** [comment]
I find having the filename and path on the same line to be a bit dense...
I think i would prefer 2 lines, with css truncation so that we don't wrap lines

**Comment by marcogallo566** [comment]
I tried this other solution, it's more readable.
Otherwise I move again the path under the filename, but with truncation, as @jasonLaster suggested.

Both `max-width: 45%` | Left 40%, right 50% | No `max-width`
------------ | ---------------- | -------------
45d31da8-16d7-421f-a3f1-fb732867ed73 | 24d1eb5a-633d-469e-9ab0-038a2fe403de | 4e435d51-cf54-410a-8e6f-f0b62aef63ab

**Comment by violasong** [comment]
I'm currently working on a full mockup of quick search and other panels, and I'm pattering the rows after the Firefox awesomebar - here's the WIP:
image
More soon!

**Comment by jasonLaster** [comment]
@violasong that looks really nice. Based on this suggestion, perhaps this PR should

1. left align the path
2. add comparable spacing

Going forward:

1. I love the tab icon
2. It would be really cool if we could drop SHAs e.g. `frameworks-a4d22334fsdf.js` became `frameworks.js`. Some will say they use it all the time, but I think if we expose it through a tooltip that will satisfy their use case while still preserving the usability of the modal.

**Comment by marcogallo566** [comment]
This is the result now:

b3caf9b2-0cf6-45a6-9599-a0c5ab541056

**Comment by jasonLaster** [comment]
Small nit, and maybe out of scope, but lets drop the filename from the URL on the right. That will really shorten it.

**Comment by violasong** [comment]
Thanks @marcogallo566 for working on this! It's looking good. Will your patch preserve the white-on-dark-blue selection styling that's currently in the quick open on nightly?

Once I finish my mockups I can write up my full recommendations, including icons and visual tweaks, for a separate issue. 

> It would be really cool if we could drop SHAs e.g. frameworks-a4d22334fsdf.js became frameworks.js. Some will say they use it all the time, but I think if we expose it through a tooltip that will satisfy their use case while still preserving the common use case for the modal.

Yeah, this would be great! Maybe we could truncate it after the first couple characters of the hash like `frameworks-a4d...` (JS icon removes the need to have the .js in there)

**Comment by jasonLaster** [comment]
> frameworks-a4d... 

Lets follow up on ellipsis and extensions in another issue. Have to think about this some more :)

**Comment by marcogallo566** [comment]
Yes, it preserves the changes @violasong.

**Comment by marcogallo566** [comment]
@jasonLaster this is the result without the right filename.

573e6f82-71fe-4176-b753-bb9e4f127394

**Comment by jasonLaster** [comment]
Looking great. I think it might be nice to drop the first and last slash. They seem to add very little information.

**Comment by marcogallo566** [comment]
Yes, it's better but I have one doubt : if there is a file in the root folder the URL would be empty...should I leave the first slash in case of empty URL?

This is an example:

a64f215d-4414-4bbf-af23-bbf8fd32b4d2

**Comment by jasonLaster** [comment]
I think that is okay. @violasong's mockups did not have a slash and this is definitely softer on the eyes :)

**Comment by darkwing** [comment]
Working on a quick update to this to prevent the following wrapping:

longfilenameproblem

Should be in shortly!

**Pull request merged**
