### PR TITLE
Right sidebar tweaks

### PR DESCRIPTION
**Pull request by wldcordeiro**
Associated Issue: #700

### Summary of Changes

* adjust padding of scope items
* change background color for zebra striping scope items to a more noticeable one.

### Testing

* [x] passes `npm test`
* [x] passes `npm run lint`

### Screenshots/Videos (OPTIONAL)

screenshot_20160926_154939

Hover effect? @SezginEge suggested this.
screenshot_20160926_185622

### CODE REVIEW

**Comment by clarkbw** [comment]
@helenvholmes can you take a look?

**Comment by wldcordeiro** [comment]
Yeah, the color choices I made were based on increasing visibility for the zebra striping and making a hover distinct from the active call stack element, I can adjust any of it as needed. 😄

**Comment by jlongster** [comment]
I personally really prefer the old background color. To me it makes it stand out way too much. It should be a subtle hint, not actually trying to differentiate a new section. There's already a ton of information in the right sidebar so we need to be conservative about how much weight we give things. I like tightening up the padding though.

**Comment by jlongster** [comment]
Although I think it needs a little more padding. It almost likes like it has no padding.

I'm not too concerned with having consistent styles across the sections. They all contain different contain laid out in very different ways. Each pane should have freedom to display information as it chooses, but conform to only basic style choices like font-size, item padding, and maybe a few others, but otherwise feel free to optimize for its content.

**Comment by jlongster** [comment]
I will totally defer to whatever @helenvholmes thinks is best though. Obviously she has the most weight in this discussion.

**Comment by wldcordeiro** [comment]
@jlongster the color I chose might be a bit strong but the original might as well be non-existent it's so subtle. Padding I took the cue from the surrounding accordions but could be tweaked as well.

screenshot_20160927_080134

**Comment by jlongster** [comment]
Yeah, it could be a tiny bit stronger, but it needs to be subtle. Let's let Helen pick a color.

> Padding I took the cue from the surrounding accordions but could be tweaked as well.

The accordions have no padding by default, iirc. Each panel needs to specify its own padding, because it could to do anything. For example we want the background color to span the entire width of the panel, but the padding will be applied inside the item. And the breakpoints has a checkbox which is different visual treatment should not receive the same padding as text.

**Comment by wldcordeiro** [comment]
@jlongster I'll defer color choices to Helen as there are three themes that need them. I chose one out of the current variables rather than picking an arbitrary color. Sorry I wasn't referring to the accordions themselves but to their contents. Breakpoints for example uses `padding: 0.25em 0`, but as you said we'll defer. I just wanted to kick off something and adjust from there.

**Comment by jlongster** [comment]
Sounds good! Thanks for opening. Good point about need to consider other themes.

**Comment by wldcordeiro** [comment]
Another adjustment that isn't really styling but might be worth doing is moving scopes/breakpoints/etc into their own accordions so that their headings always stay visible in the sidebar but the contents move when scrolled.

**Comment by jlongster** [comment]
I'm not sure what you mean by that. Why would we have multiple accordions?

I imagine us finding a better way to display all that information, but it's going to take time and we need to be careful about it. Most alternatives I've seen so far would not actually play out in practice. The way it acts right now is intentional; we played with a few different behaviors a long time ago but they all had serious drawbacks.

**Comment by helenvholmes** [comment]
Striping on the original is purposefully non-existent; @jlongster's correct, it's about not highlighting too much information at once, and [relying on white space to create line items](https://twitter.com/helenvholmes/status/742998316963790848).

Issue #700 is more about treating the padding and alignment in the right sidebar consistent; currently padding between items in accordions and left-alignments are all inconsistent. Getting everything lined up will help the vertical rhythm, as Jason put it, and consistent white space will help users differentiate what is a line item at a glance.

I think it would be best to left-align everything vertically first, and come back to visual changes like these second.

screen shot 2016-09-28 at 2 29 35 pm

screen shot 2016-09-28 at 2 30 01 pm

**Comment by wldcordeiro** [comment]
Updating PR for those changes @helenvholmes mentioned. Should be ready a little later today.

**Comment by wldcordeiro** [comment]
@helenvholmes I resized the arrows a bit because they were larger than what appeared in your images and adjusted their margin. Looks like the alignment is there now.

screenshot_20160929_104818

**Comment by jlongster** [comment]
It feels a little inconsistent to change the size of the arrow when it's used in several other places.

Honestly, I'm still unsure exactly what the original issue is about :) The main thing that I think needs tweaking is the top/bottom padding of the call stack. We could indent the contents come to make it more "nested", but that doesn't make sense with the call stack I think. 

@helenvholmes, the designs you posted aren't what we currently implement (grouping breakpoints by file, etc), so it's a little hard to talk about what to specifically change on our end. If you have any recommendations for small tweaks the current designs, that's great! Otherwise I think we should just make the call stack items a little tighter and that's all.

**Comment by wldcordeiro** [comment]
@jlongster draw a line from the pause button and the left edge of the accordion headings is left aligned to it.

**Comment by wldcordeiro** [comment]
Moving the command bar over a few pixels achieves this too.

screenshot_20160929_124315

**Comment by helenvholmes** [comment]
Lining it up either way is an improvement—I'd say we merge this and then debate arrow sizing in a separate pr.

Thanks for the hard work @wldcordeiro, thanks for going back and forth with us ✌🏽

**Comment by jlongster** [comment]
My bad, I definitely read it wrong! I like this solution too, it's very simple. I'll merge it! Thanks for talking through it @wldcordeiro !

**Comment by wldcordeiro** [comment]
Separate PR is fine for this but I realized that while the breakpoints and scopes had the left alignment right, call stack did not (aside from its padding issues.) 
screenshot_20160929_131122

**Comment by jlongster** [comment]
That's because there's no checkbox or arrow icon. It would be really weird imho to give up precious spacing in the call stack for that. It's more important to see more of the function name.

**Pull request merged**
