### PR TITLE
Fix remaining quick open intermittent

### PR DESCRIPTION
**Pull request by jasonLaster**
still seeing some intermittents
https://treeherder.mozilla.org/#/jobs?repo=try&revision=c667044750ad5dce22ae4f447de87e24ac0cc745&selectedJob=161341812

### CODE REVIEW

**Comment by jasonLaster** [comment]
lets leave this open until we fix the int

**Comment by codehag** [comment]
is this in relation to a release?

**Comment by darkwing** [comment]
What's the next step here?

**Comment by jasonLaster** [comment]
try is good. gotta fix browser.ini here

**Pull request merged**
