### PR TITLE
Remove unecessary check when focusing Tree

### PR DESCRIPTION
**Pull request by nchevobbe**
According to James Teh in https://bugzilla.mozilla.org/show_bug.cgi?id=1424159#c8 , the check we were doing in the Tree was preventing interacting with them in a given mode of screenreaders.

The original check was made to make sure we only automatically select the first node of a Tree if the focus was not set in the Tree. We did that by relying on `explicitOriginalTarget`.
But we already bail out if there's already a `focused` prop. So it makes sense to simply remove the extra check. According to my manual testing in the Reps test app (and in the console with the reps bundle updated), it seems to work fine. 

I pushed to [TRY](https://treeherder.mozilla.org/#/jobs?repo=try&revision=69647b885a2dfa7eec3fa4ee0b7e04201457ad9b) to see if everything is okay

### CODE REVIEW

**Comment by nchevobbe** [comment]
So far I see 2 failures: 

- `devtools/client/webconsole/test/mochitest/browser_webconsole_longstring_getter.js` | which is expected since the copied bundle from Github erased the hotfix made directly in m-c bundle
- `devtools/client/webconsole/test/mochitest/browser_webconsole_object_inspector_scroll.js` | which can be fixed with:

```diff
diff --git a/devtools/client/webconsole/test/mochitest/browser_webconsole_object_inspector_scroll.js b/devtools/client/webconsole/test/mochitest/browser_webconsole_object_inspector_scroll.js
--- a/devtools/client/webconsole/test/mochitest/browser_webconsole_object_inspector_scroll.js
+++ b/devtools/client/webconsole/test/mochitest/browser_webconsole_object_inspector_scroll.js
@@ -39,8 +39,7 @@ add_task(async function() {
   });
 
   info("Expand the last node");
-  const view = lastNode.ownerDocument.defaultView;
-  EventUtils.synthesizeMouseAtCenter(lastNode, {}, view);
+  lastNode.click();
 
   await onOiMutation;
```

**Comment by darkwing** [comment]
R+ from testing in debugger sources tree 👍

**Comment by jasonLaster** [comment]
@darkwing why did you add disableFocus?

**Comment by darkwing** [comment]
Marking as pr-wip as this requires test updates.

**Comment by darkwing** [comment]
@nchevobbe Is someone working on those tests?  Is there a patch in MC that needs to be merged first?

**Comment by nchevobbe** [comment]
> @nchevobbe Is someone working on those tests? Is there a patch in MC that needs to be merged first?

I'll have a patch soon

**Comment by nchevobbe** [comment]
@darkwing here's a review for you https://phabricator.services.mozilla.com/D3774 :)

**Comment by darkwing** [comment]
Rebased this with another change.  Since our MC commit was merged, I'll merge this when tests pass.

**Pull request merged**
