### PR TITLE
fix key shortcut on linux (#715)

### PR DESCRIPTION
**Pull request by jbhoosreddy**
**WIP**
This is how Chrome deals with it. After it is resolved, I'll go ahead and file a bug/patch in m-c for the old debugger.

PS: I took that test because it seemed the easiest of the lot, but turned out to be a rabbit hole. Haha.

### CODE REVIEW

**Comment by jlongster** [comment]
Woo awesome!

**Comment by jasonLaster** [comment]
Wow, looks great

**Comment by jasonLaster** [comment]
looks like there was a lint and the test timed out
509 INFO TEST-UNEXPECTED-FAIL | devtools/client/debugger/new/test/mochitest/browser_dbg_keyboard-shortcuts.js | Test timed out - 


@jbhoosreddy should be close to landing though

**Comment by jbhoosreddy** [comment]
I obviously wasted some time on this one. But that's okay. Someone would have to spend time debugging this at some point anyway. Apart from any possible nits, I think the key shortcuts are good to go for all platforms, including Linux.

**Comment by jbhoosreddy** [comment]
Also, Yay!

**Comment by jasonLaster** [comment]
:thumbsup:

Great work on this!

**Comment by jbhoosreddy** [comment]
This should be good to go.

**Pull request merged**
