### PR TITLE
Keeps focus on input field

### PR DESCRIPTION
**Pull request by lukaszsobek**
Associated Issue: #4422

### Summary of Changes

* Added clickhandler to listen to changes in box

### Test Plan

Clicked a lot

### Screenshots/Videos (OPTIONAL)
http://g.recordit.co/iXs7CldKz5.gif

### CODE REVIEW

**Comment by lukaszsobek** [comment]
closes #4422

**Comment by lukaszsobek** [comment]
Guess I can't do that XD

**Comment by jasonLaster** [comment]
hehe - too much power? ...

**Comment by lukaszsobek** [comment]
I'm sorry Dave ...

**Pull request merged**
