### PR TITLE
add docs for connecting to safari on iOS

### LINKED ISSUE #734: [documentation] Include docs on how to debug ios safari
@clarkbw has a great gist on connecting to ios safari https://gist.github.com/clarkbw/782e9a7c558d83eb95dae005bf203362

We should include this in our docs

### PR DESCRIPTION
**Pull request by clarkbw**
Fixes #734

### CODE REVIEW

**Comment by jbhoosreddy** [comment]
this is amazing. i can't wait to try it out!

**Comment by clarkbw** [comment]
mochitest failed for unrelated reasons

`637 INFO TEST-UNEXPECTED-FAIL | devtools/client/debugger/new/test/mochitest/browser_dbg-console.js | Test timed out - `

**Comment by clarkbw** [comment]
I'm going to merge this in so I can finish up with the rest of the docs changes

**Comment by clarkbw** [comment]
It looks like the tests are failing because we need #736 to merge

**Pull request merged**
