### PR TITLE
Fix name collisions: getOutOfScopeLocations

### PR DESCRIPTION
**Pull request by pradeepgangwar**
Associated Issue: #4886

### Summary of Changes

* Fix naming collisions between `getOutOfScopeLocations` in `workers/parser`/getOutOfScopeLocations.js and `getOutOfScopeLocations` in `reducers/ast.js`

### CODE REVIEW

**Comment by pradeepgangwar** [comment]
@codehag Please review.

**Comment by codehag** [comment]
Shoot, i think i wasn't entirely clear in the issue.

we don't want to rename both, just one. I was thinking we should rename the parser (which you did, perfect!) but not the ast reducer, since we use the `get` prefix on most of our reducer selectors. The ast reducer should keep the name `getOutOfScopeLocations`..

Let me know if anything is unclear!

**Comment by pradeepgangwar** [comment]
@codehag I am not getting where i have done mistake. I changed `src/actions/ast.js` to this 
```
import {
   getSymbols,
   getEmptyLines,
-  getOutOfScopeLocations,
+  findOutOfScopeLocations,
   isReactComponent
 } from "../workers/parser";
```
because it is imported from parser. Other than this I haven't touched `ast reducer` code. Please correct me if i am doing wrong somewhere.

**Comment by codehag** [comment]
oh, my mistake! you are absolutely right. I will read through the pr again when i have more time :)

thanks for the correction!

**Pull request merged**
