### PR TITLE
[Preview] Don't allow popover to move outside editor boundaries

### PR DESCRIPTION
**Pull request by darkwing**
Fixes Issue: #5134

Took a while to identify the problem element but this should be the right strategy.

### CODE REVIEW

**Comment by jasonLaster** [comment]
nice, mind sharing a GIF

**Comment by jasonLaster** [comment]
@darkwing is this ready for review? If so, can you share a before/after GIF?

**Comment by darkwing** [comment]
Not ready yet -- see the "ToDo" in the PR description

**Comment by jasonLaster** [comment]
got it. yeah, this is a tricky case. I suppose one option if we can't put the popup below or above, is to always go to the right and then use the full height... I believe this is what chrome does. Worth checking out

**Comment by darkwing** [comment]
This PR is 75+% of the way there.  Where this PR falls short is when the popover appears *above* the highlighted token:

- An incorrect maxHeight is calculated because the maxHeight is currently taking the {all space} - {top}
- Since the maxHeight is wrong, the arrow shifts downward and no longer points to the highlighted token when the `ObjectInspector` on the inside is expanded.

I think the best course of action here would be to recalculate the maxHeight an positioning of the popover when the `ObjectInspector` is expanded or contracted; that should fix the maxHeight problem.  An additional need is adding the orientation as a condition to the maxHeight positioning so that the popover appears in the correct spot.

**Comment by darkwing** [comment]
Current status:

heightyessss

I need to change the code, however, so that the top arrow content doesn't look weird, but this is super encouraging.

**Comment by darkwing** [comment]
@jasonLaster I think this is ready for evaluation.  I don't want the scope to creep out and all my testing shows this works

**Comment by jasonLaster** [comment]
can we use react `style={}` while rendering?
https://reactjs.org/docs/dom-elements.html#style

**Comment by darkwing** [comment]
Instead of `popupNode.style.maxHeight = `${maxHeight}px`;`?  Nope; we're styling an element inside the component, not the component wrapper itself.

**Comment by jasonLaster** [comment]
I wonder what this would look like if we used a [render prop](https://reactjs.org/docs/render-props.html) strategy where Popup can get the coords from popover and use them intelligently...

Here's a quick sketch i made. I never tried to run it and i did get a bit distracted.
- coords becomes a regular field i.e. not state
- the default coords are saved once
- coords are passed up to Popup, which uses it when rendering 

Why is this strategy better?

I think it is dangerous for Popover to know too much about what it is showing. It is a bit cleaner for Popup to be responsible for doing its own styling... Anyways, this is just a hunch i'm not in the code so just guessing.

[sketch]: https://gist.github.com/jasonLaster/459f61ca03ef7b4a92933410d86229f1

**Comment by darkwing** [comment]
Render props are cool but I don't see how it applies here -- `this.getChildren()` is the closest handle I get

**Comment by jasonLaster** [comment]
https://gist.github.com/jasonLaster/459f61ca03ef7b4a92933410d86229f1

**Comment by darkwing** [comment]
Superceded by: https://github.com/devtools-html/debugger.html/pull/6654

**Pull request closed without merging**
