### PR TITLE
[Search] Put find in file modifers on same line as input and move whole search bar to bottom of editor

### LINKED ISSUE #6651: [Search] New design for Find in File/Find in Project
I made this mock up 2 months ago, so it's possible it needs to be updated. The main changes here include: polishing/unifying the look of the two types of search, moving the fields to the bottom, and allowing the user to still see both the fields and their open file/search results at the same time. Let me know if I should make any changes.

https://mozilla.invisionapp.com/share/Y8H6UH8V5HX#/screens

screen shot 2018-07-18 at 11 25 38 am

### PR DESCRIPTION
**Pull request by audreyfang**
Fixes #6651

### Summary of Changes

* Put search modifiers for find in file on the right of the input bar instead of below
* Make the focus highlight surround the whole search bar instead of just the input bar

### Test Plan

Tell us a little a bit about how you tested your patch.

- [x] Crtrl-f to bring up search bar
- [x] Click in and out of search bar to test focus highlighting
- [x] Search for text in file
- [x] Close search bar

### Screenshots/Videos
search

### CODE REVIEW

**Comment by audreyfang** [comment]
Here is what resizing the window does to the search bar: 
search-squeeze

**Comment by audreyfang** [comment]
Search bar now on bottom of editor:
search-bottom

**Comment by darkwing** [comment]
This is so awesome @audreyfang !  I have only one tiny suggestion.

## Border on Bottom
One artifact of the last UI is that there was a bottom border under the input to separate search from the editor.

borderbottom

We'll want to move that border to the top:

## Top (Better)
borderontop

The selector I changed from `border-bottom` to `border-top` was `.search-bar`.

**Comment by darkwing** [comment]
@violasong Check out how awesome this is! :)

**Comment by darkwing** [comment]
This is amazing, great work!

**Comment by jasonLaster** [comment]
Great work @audreyfang!

**Comment by violasong** [comment]
Wow, awesome to see this @audreyfang! 

I realized I hadn't considered how the navigational buttons would look next to the modifier buttons, and that a bit of extra UI would be helpful there - I'll file a new bug with UI polish nits :).

**Pull request merged**
