### PR TITLE
Photon ui tweaks for issue #6180

### PR DESCRIPTION
**Pull request by marvinkome**
Fixes Issue: #6180 

### Summary of Changes

* remove close button
* add the loading message

### Test Plan

- [x] Command-P opens the panel
- [x] Clicking ctrl (cmd) + shift + 'f'

### CODE REVIEW

**Comment by darkwing** [comment]
I rebased this to get the linting issues out (they were already fixed on master) A few improvements we should make before merging:

- [ ] We should make the "Loading text" appear lower; would "align-self: center" work?
- [ ] The loading text should only display while a search is occurring, then hide when the serach is complete

**Comment by jasonLaster** [comment]
I believe @aaronmoodie might be working on this as well...

- The search input is used in other components, so we'll want to hide it conditionally.
- Perhaps "loading" should be passed to the input through some prop like statusMsg, that way other UIs could put different messages there...

**Comment by darkwing** [comment]
Hello again @marvinkome.  Let's pinch the scope of this PR to just removing the close button, since the "Loading..." message is going to be a lot tougher.  I'm thinking we can do something like this:

```js
diff --git a/src/components/QuickOpenModal.js b/src/components/QuickOpenModal.js
index 0caabcef..709098be 100644
--- a/src/components/QuickOpenModal.js
+++ b/src/components/QuickOpenModal.js
@@ -397,6 +397,7 @@ export class QuickOpenModal extends Component<Props, State> {
           selectedItemId={
             expanded && items[selectedIndex] ? items[selectedIndex].id : ""
           }
+          hideCloseButton={true}
         />
         {this.renderLoading()}
         {newResults && (
diff --git a/src/components/shared/SearchInput.js b/src/components/shared/SearchInput.js
index 704dd941..b84e891f 100644
--- a/src/components/shared/SearchInput.js
+++ b/src/components/shared/SearchInput.js
@@ -46,7 +46,8 @@ type Props = {
   shouldFocus?: boolean,
   showErrorEmoji: boolean,
   size: string,
-  summaryMsg: string
+  summaryMsg: string,
+  hideCloseButton: boolean
 };
 
 type State = {
@@ -162,7 +163,8 @@ class SearchInput extends Component<Props, State> {
       selectedItemId,
       showErrorEmoji,
       size,
-      summaryMsg
+      summaryMsg,
+      hideCloseButton
     } = this.props;
 
     const inputProps = {
@@ -201,7 +203,9 @@ class SearchInput extends Component<Props, State> {
           <input {...inputProps} />
           {summaryMsg && <div className="summary">{summaryMsg}</div>}
           {this.renderNav()}
-          <CloseButton handleClick={handleClose} buttonClass={size} />
+          {!hideCloseButton && (
+            <CloseButton handleClick={handleClose} buttonClass={size} />
+          )}
         </div>
       </div>
     );
```

**Comment by aaronmoodie** [comment]
@jasonLaster had some changes to remove the close button which are in this PR.
https://github.com/devtools-html/debugger.html/pull/6247

**Pull request closed without merging**
