### PR TITLE
Fix firefox.mcPath documentation.

### PR DESCRIPTION
**Pull request by ochameau**
I had to do a local.json file like this in order to make `yarn copy-assets` to work.

### CODE REVIEW

**Comment by jasonLaster** [comment]
strange, that seems like the default. When i'm copying to another dir, i use the node script `node bin/copy-assets.js --mc ../gecko --assets` maybe we should just document that. local.json can be a pain.

**Comment by ochameau** [comment]
I don't have much opinion here as I just discover all this ;)
The only important thing here is to have a correct and complete doc to build the m-c bundle manually.

**Comment by ochameau** [comment]
Ok, so you have to pass --assets to have the same behavior than what is shipped.
And also --symlink false to prevent having `devtools/client/debugger/new/test/mochitest` to be deleted by the symlink function from launchpad.

May be it is easier to document setting that in the json file rather than saying you have to pass this to yarn copy-assets every time?

**Comment by jasonLaster** [comment]
yeah - i'll review this tomorrow and try and simplify the steps. it's gotten pretty stale

**Comment by codehag** [comment]
ping @jasonLaster did you have a chance to take a look? should we update the docs?

**Comment by jasonLaster** [comment]
yep - just busy :)

**Pull request merged**
