### PR TITLE
 [Watch Expressions] polish header buttons

### PR DESCRIPTION
**Pull request by andreicristianpetcu**
Associated Issue:#1347

### Summary of Changes

* added "refresh" button in Watch Expressions as SVG
* added "add" button in Watch Expressions as char

### Test Plan
https://github.com/devtools-html/debugger.html/issues/1347#issue-192350493

Enable watch expressions in config/local.json
The new buttons should look like lin Chrome https://cloud.githubusercontent.com/assets/254562/20721502/f53bf546-b630-11e6-8472-bc36ff1a2b7a.png

### Screenshots/Videos (OPTIONAL)
[Before](https://cloud.githubusercontent.com/assets/254562/20721494/e8cd2f82-b630-11e6-8080-02c092e5272b.png)
[After](https://cloud.githubusercontent.com/assets/922368/21114739/0053ea22-c0a6-11e6-8d2c-38b252e6ab24.png)

### CODE REVIEW

**Comment by andreicristianpetcu** [comment]
@jasonLaster third attempt to a pull request. I hope I got this one right. :)

**Comment by jasonLaster** [comment]
Mind rebasing off of master. https://robots.thoughtbot.com/keeping-a-github-fork-updated

Also, could you attach screenshots from the debugger in chrome and firefox. One thing I'm checking for is the height of the header, which i saw changed quite a bit.

**Comment by andreicristianpetcu** [comment]
@jasonLaster  Sorry but I don't understand. Did you copy [something](https://github.com/devtools-html/debugger.html/commit/56684cfbaa323787587d601f45da78d38a34289e) from my pull request before it was accepted or I'm reading this wrong? I keep having merge issues and I'm trying to understand what happened.

I'l first resolve all the issues and then I will put the print screens.

**Comment by jasonLaster** [comment]
Yeah, sorry your first patch landed: https://github.com/devtools-html/debugger.html/commit/56684cfbaa323787587d601f45da78d38a34289e

sadly under my name, but that shouldn't matter :)

**Pull request closed without merging**
