### PR TITLE
[parser] Pause at multi-line returns

### PR DESCRIPTION
**Pull request by jasonLaster**
### Summary of Changes

This is a small tweak which now lets us add breakpoints at return statements when the argument is on another line. This is actually quite common for JSX.

### CODE REVIEW

**Comment by darkwing** [comment]
I made a minor adjustment to cut down on code; feel free to remove it if you'd like.

**Comment by jasonLaster** [comment]
hmm, the jest updates seem off...

**Comment by darkwing** [comment]
I was trying to explain that to you in Slack yesterday, must have misworded that

**Comment by jasonLaster** [comment]
yep.. strange

**Comment by jasonLaster** [comment]
the jest issues were the result of adding to the fixture example

**Pull request merged**
