### PR TITLE
Jsx ally/no noninteractive tabindex warning fixed

### LINKED ISSUE #7544: Fix jsx-a11y/no-noninteractive-tabindex warnings raised by jsx-a11y linter.
To get a list of accessibility warnings raised by jsx-a11y linter run: `yarn lint:jsx-a11y`.

From that list please note all instances that are flagged to have "jsx-a11y/no-noninteractive-tabindex" problem. Each one needs to be addressed individually.

Once all of the instances are resolved make sure to change this setting in `.eslintrc.jsx-a11y` from:
```
"jsx-a11y/no-noninteractive-tabindex": ["warn", {
  "tags": [],
  "roles": ["tabpanel"]
}],
```

to
```
"jsx-a11y/no-noninteractive-tabindex": ["error", {
  "tags": [],
  "roles": ["tabpanel"]
}],
```

### PR DESCRIPTION
**Pull request by codingnninja**
Fixes #7544

### Summary of Changes

* Noninteractive-TabIndex removed from
        /src/components/SecondaryPanes/Frames/Frame.js (line: 153)
        /src/components/SecondaryPanes/Frames/Group.js (line: 144)
        /src/components/shared/Accordion.js (line: 68)

*"Warn" is changed to "error" in  /.eslintrc.jsx-a11y (line: 53)
  

### Test Plan

yarn lint:jsx-a11y is run in the root directory to check whether tabIndex is used and if any, such must be presented in red (as an error) because of the change in /.eslintrc.jsx-a11y (line: 53)

Example test plan:

- [x] Run yarn lint:jsx-a11y
- [x] Check for "tabIndex" in red (color) if any.

### Screenshots
Before fixing the issue

After fixing the issue

### CODE REVIEW

**Comment by codingnninja** [comment]
@jasonLaster  @AnshulMalik ..... Anything on this?

**Comment by AnshulMalik** [comment]
Looks good @codingnninja . Looks like jest snapshots needs to be updated, `yarn jest -u` should do the trick :)

**Comment by codingnninja** [comment]
@AnshulMalik ... Oh! Thanks for that...

**Comment by darkwing** [comment]
Unfortunately I don't think it's going to be this easy.  The `tabIndex` exists so that we can hit the `[enter]` key to toggle open and closed each accordion title/heading.  I think we may need to put the accordion header items inside a `<button>` and apply the `onClick` to taht.

**Comment by jasonLaster** [comment]
How's it going @codingnninja?

**Comment by darkwing** [comment]
@codingnninja I really appreciate your effort here but we may need to put this one on ice momentarily.  We need to restructure our accordion headers so that `tabIndex` isn't needed, and that will be complicated.

Please stick around and grab another issue! 👍

**Comment by darkwing** [comment]
[](url)

**Pull request closed without merging**
