### PR TITLE
Fix preview for falsy values

### PR DESCRIPTION
**Pull request by nyrosmith**
Associated Issue: #3944 

falsypreview

### CODE REVIEW

**Comment by jasonLaster** [comment]
Could you check with null, undefined and 0?

We have a glitch template in the issue template PR :)

**Comment by nyrosmith** [comment]
I checked it. You can see it in the GIF.

**Comment by nyrosmith** [comment]
Just realized that you don't see undefined case but I checked that too

**Comment by jasonLaster** [comment]
Looks like we should show undefined as well: 

Here's a quick example
https://plucky-mustang.glitch.me/

chrome shows it and i believe julian had a case where he expected it too


I think our rule of thumb should just be show all values for result. So lets drop this IF statement entirely :)

**Comment by nyrosmith** [comment]
Undefined is already handled
falsypreview2

**Pull request merged**
