### PR TITLE
create /dev/mqueue before running docker command

### PR DESCRIPTION
**Pull request by clarkbw**
Trying a fix via https://github.com/boot2docker/boot2docker/issues/1098

### CODE REVIEW

**Comment by clarkbw** [comment]
Grrr... Well the test actually ran, but ran into an error inside the docker image.

```
** (xpcshell:416): WARNING **: Could not open X display

runtests.py | Running with e10s: True

runtests.py | Running tests: start.



Application command: /firefox/obj-x86_64-pc-linux-gnu/dist/bin/firefox -marionette -foreground -profile /tmp/tmp8SjpyK.mozrunner

runtests.py | Application pid: 474

TEST-INFO | started process Main app process

error: XDG_RUNTIME_DIR not set in the environment.

Error: cannot open display: unix:99

Traceback (most recent call last):

  File "/firefox/obj-x86_64-pc-linux-gnu/_tests/testing/mochitest/runtests.py", line 2420, in doTests

    marionette_args=marionette_args,

  File "/firefox/obj-x86_64-pc-linux-gnu/_tests/testing/mochitest/runtests.py", line 2026, in runApp

    self.marionette.start_session(timeout=port_timeout)

  File "/firefox/testing/marionette/client/marionette_driver/decorators.py", line 42, in _

    return func(*args, **kwargs)

  File "/firefox/testing/marionette/client/marionette_driver/marionette.py", line 1178, in start_session

    self.protocol, _ = self.client.connect()

  File "/firefox/testing/marionette/client/marionette_driver/transport.py", line 214, in connect

    self.sock.connect((self.addr, self.port))

  File "/usr/lib/python2.7/socket.py", line 224, in meth

    return getattr(self._sock,name)(*args)

error: [Errno 111] Connection refused

0 ERROR Automation Error: Received unexpected exception while running application
```

**Comment by jlongster** [comment]
I'm confused that only you are running into this... we also don't use the webdriver stuff for mochitests. It just runs `./mach mochitest`, so I don't understand how that effects you?

**Comment by clarkbw** [comment]
> I'm confused that only you are running into this... 

I wish it wasn't so...  But I'm going to look into the circleci settings.

> we also don't use the webdriver stuff for mochitests. It just runs ./mach mochitest, so I don't understand how that effects you?

Oh, those might be in the wrong branch.  Getting confused with the other work that's blocked on getting past these errors.

**Comment by clarkbw** [comment]
The devtools-html environment was set to `Ubuntu 12.04 (Precise)`
While my clarkbw account was set to `Ubuntu 14.04 (Trusty)`

Trying that now.

**Comment by clarkbw** [comment]
Looks like setting the environment to `Ubuntu 12.04 (Precise)` is the difference.  Wow. 🔥 

Closing this PR as the changes, even though they pass, don't do anything required in the working build environment.  I can probably kick my other changes into action now.

**Pull request closed without merging**
