### PR TITLE
changed div into button

### PR DESCRIPTION
**Pull request by phoenixking25**
pull
#6251 converted div/span into buttons

### CODE REVIEW

**Comment by jasonLaster** [comment]
Thanks @phoenixking25 can you update the css so that it doesnt change aesthetically

**Comment by phoenixking25** [comment]
@jasonLaster you mean to remove on hover effect?

**Comment by jasonLaster** [comment]
and the button styling

**Comment by phoenixking25** [comment]
updated
@jasonLaster is it looking fine now?

**Comment by jasonLaster** [comment]
hmm, lets also get rid of the background hover. I think its somewhat distracting

**Comment by phoenixking25** [comment]
The hover effect is set on button element for all. If i remove that then wouldnt be it same as before?

**Comment by jasonLaster** [comment]
it would be more accessible. think tabs

**Comment by phoenixking25** [comment]
@jasonLaster Done :+1:

**Comment by jasonLaster** [comment]
small jest issue, youll need to run `jest -u`

mind sharing another gif?

**Comment by phoenixking25** [comment]
tabbed
@jasonLaster Now can access with tabs and removed background hover

**Comment by AnshulMalik** [comment]
Can we get rid of the text outline and keep the button outline?

**Comment by jasonLaster** [comment]
@phoenixking25 to might be nice to undlerine the text on hover and change the cursor to a pointer

**Comment by AnshulMalik** [comment]
And also the cursor should be changed to pointer @phoenixking25

**Comment by phoenixking25** [comment]
screenshot from 2018-05-14 20-57-27
@jasonLaster changed the cursor and underlined it!!

**Comment by darkwing** [comment]
Hello @phoenixking25 -- great work so far.  I took a look, threw a few ideas around with colleagues, and what we came up with two options:

1.  If we switch to `<button>`, we should style the button to look just as the `<div>s` look now; same color, font-size, and font family

2.  If we stay as a `<div>`, add `role=button` (https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20160317/examples/button/button.html), set a `tabindex=0` (we'll see how this effects other stuff), add a pointer cursor, and make the text a bit darker upon hover.

I like option 2 the best but have fun and try a few things!  Thank you so much for your help! 👍

**Comment by phoenixking25** [comment]
div
@darkwing done as you said, used `<p>`  tags instead of `<div>` because using div was changing  the alignment and applied onKeyPress, made the text bit bolder but in case of commands like `Ctrl P` we are using some font-family so it is not getting bolder. ignore the cursor its my gif making tool fault, actually its pointer cursor.

**Comment by darkwing** [comment]
Hello again @phoenixking25 ; this seemingly small change (not your code, just the design change in general) seems to have kicked off a bunch of different opinions 😸  and our design person want to look at it a bit more.  I'm closing this PR until they make a decision but I wanted to let you know this is really awesome work and we'll likely re-open and use it soon.  In the mean time, please stick with us and pick another issue to fix -- you do great work! 👍

**Pull request closed without merging**
