### PR TITLE
Bump devtools-components to 0.1.4

### PR DESCRIPTION
**Pull request by MikeRatcliffe**
Couldn't be simpler... bump devtools-components to 0.1.4

### CODE REVIEW

**Comment by wldcordeiro** [comment]
Failing snapshots so I think you need to run `yarn test -u`

**Comment by MikeRatcliffe** [comment]
> Failing snapshots so I think you need to run `yarn test -u`

Because I was working on a pull request I decided to mark it WIP so that nobody else would work on it.

Thanks for giving me the magical incantation though... that save me some time.

**Comment by MikeRatcliffe** [comment]
I am testing all debugger functionality because I don't want to recreate all of the snapshots if the debugger is doing the wrong thing.

**Comment by MikeRatcliffe** [comment]
As soon as we land this I will create a bundle and get on with upgrading all the things to React 16.

**Comment by MikeRatcliffe** [comment]
> I think it is safe to remove the devtools-components dependency from package.json...

Done

**Pull request merged**
