### PR TITLE
Synchronize browser_dbg-chrome-debugging.js from m-c

### PR DESCRIPTION
**Pull request by juliandescottes**
Synchronize changes from https://bugzilla.mozilla.org/show_bug.cgi?id=1416711

### CODE REVIEW

**Comment by juliandescottes** [comment]
I'm wondering why the previous test wasn't failing though, because addBrowserActors() is no longer available on DebuggerServer. Is it possible that the image used for mochitests is outdated?

**Comment by codehag** [comment]
hmm good question, lets see if it fails now

**Comment by juliandescottes** [comment]
As discussed, failed because we are based on mozilla central rev [f27105b62753](https://hg.mozilla.org/mozilla-central/rev/f27105b62753) which is too old. Will update the PR

**Comment by juliandescottes** [comment]
Travis is green with the new m-c changeset.

**Pull request merged**
