### PR TITLE
Bugfix watch expression hover

### PR DESCRIPTION
**Pull request by zeoneo**
Associated Issue: 5500

### Summary of Changes

* Change in Expressions.css: onHover background-color of expression-container changes to blue( --theme-selection-background-hover). Earlier it used change only for expression text.

* Change in Expressions.js: Add doubleClick listener to expression container instead of expression text. 

### Test Plan

Tell us a little a bit about how you tested your patch.

Example test plan:

- [x] Add new watch expression
- [x] On mouse hover background-color of entire row should change to blue(--theme-selection-background-hover)
- [x] Add one more watch expression and try hovering over it.
- [x] Double click on the expression row even on white space should allow user to edit watch expression.
- [x] Click on close icon should remove the watch expression.
watch-expression

### Screenshots/Videos (OPTIONAL)

### CODE REVIEW

**Comment by AnshulMalik** [comment]
Looks great @zeoneo. Just an edge case in firebug theme,
a

**Comment by zeoneo** [comment]
Thanks for pointing it out. I will fix that too.

**Comment by jasonLaster** [comment]
Thanks @zeoneo it's easy to change the theme in the launchpad `localhost:8000`. There's a settings pane with a themes dropdown

**Comment by zeoneo** [comment]
Testing in firebug theme. 
mar-04-2018 01-19-43

**Pull request merged**
