### PR TITLE
Convert to es6 modules

### PR DESCRIPTION
**Pull request by sashakru**
Associated Issue: https://github.com/devtools-html/debugger.html/issues/1884

### Summary of Changes

* refactor `actions` to es6 modules: `breakpoints.js`, `sources.js` - partially
* refactor `reducers` to es6 modules
* refactor `utils` `test-head.js` to es6 modules
* refactor `selectors.js`

### CODE REVIEW

**Comment by jasonLaster** [comment]
This is awesome work. 

Let's prioritize landing ASAP. I see some integration test failures. There best thing to do is try doing the test steps manually and make sure everything works. We likely broke something stupid like pausing :)

**Comment by jasonLaster** [comment]
@sashakru do you have time to finish this up?

**Comment by sashakru** [comment]
@jasonLaster hey,

Will try fix today,
Found that there is some disable integration tests with comment `// timed out`:

```
 // timed out
  xit("sourceMaps", async function() {
    await sourceMaps(ctx);
  });
```.

Will ping you tonight about my progress.

**Comment by jasonLaster** [comment]
Hey @sashakru! I rebased your work so that it is up to date.

When I tried to start the debugger on your branch I found some errors in `reducers/index` it looks like import/export is failing.

**Comment by jasonLaster** [comment]
@sashakru i'm closing this for now. Feel free to open it up again when it's ready. Also i suggest smaller PRs :)

**Pull request closed without merging**
