### PR TITLE
Improving the contrast of the hover background for the buttons in the dark mode - BUG ID - 1513414.

### PR DESCRIPTION
**Pull request by akshithashetty**
Background color on hover of the following buttons have been fixed (made consistent with the higher level tabs)-
In the debugger mode,
1)Collapse panes both right and left
2)Pause F8
3)Step over F10
4)Step in F11
5)Step out Shift + F11
6)Deactivate breakpoints
7)Keyboard Shortcuts

### CODE REVIEW

**Comment by akshithashetty** [comment]
slice
Thank you ! 
Yes sure, this is how the hover color looks before and after the fix, it is now consistent with the other tabs.  I have tried to implement the fix prescribed by @violasong in
https://bugzilla.mozilla.org/show_bug.cgi?id=1513414
Let me know how to go ahead with this. Thanks.

**Comment by violasong** [comment]
This looks correct to me!

**Comment by akshithashetty** [comment]
Hi, 
@darkwing ,I have optimized the CSS by adding a prefix .theme-dark for the styles concerned. Could you please review it?
Thanks

**Comment by darkwing** [comment]
Thank you @akshithashetty !!

**Pull request merged**
