### PR TITLE
Us#3361 excepion details in dark theme

### PR DESCRIPTION
**Pull request by elpddev**
Associated Issue: #3316 

### Summary of Changes

* change color of component part from one theme color to another theme color
* add vim temp file to gitignore

### Test Plan

Run yarn test-all

### CODE REVIEW

**Comment by elpddev** [comment]
#goodnessSquad

**Comment by jasonLaster** [comment]
@elpddev mind sharing a before/after screenshot

**Comment by elpddev** [comment]
@jasonLaster Sure. Those are the screenshots:

Before:
before

After:
after

**Comment by jasonLaster** [comment]
@elpddev per a comment in the issue, i think the text should be un-italicized

**Comment by elpddev** [comment]
@jasonLaster I've changed to error font to style normal.

after-normal

**Pull request merged**
