### PR TITLE
add headline screenshot to README

### LINKED ISSUE #398: readme screenshot
thinking of using this for the readme screenshot

debugger

thoughts? @jlongster  @jasonLaster 

I want something that shows off
* sources tree view
* editor
* editor tabs
* breakpoint list
* scopes
* call stack (however this call stack was actually too big to include and pushed everything down)
* paused state

### PR DESCRIPTION
**Pull request by clarkbw**
fixes #398

### CODE REVIEW

**Comment by jasonLaster** [comment]
👍

**Comment by jasonLaster** [comment]
Sorry, I accidentally pushed a change that enabled fixtures https://github.com/devtools-html/debugger.html/commit/8041eeebf682d0db3303cdabcddb0ae72f5c9a57. Ughh, pushing to master directly is so dangerous :/

**Comment by clarkbw** [comment]
> Sorry, I accidentally pushed a change that enabled fixture

I'll rebase and force push

**Comment by clarkbw** [comment]
ugh

**Pull request merged**
