### PR TITLE
[Preview] Switch to token-over

### PR DESCRIPTION
**Pull request by haoRchen**
Fixes Issue: #6193 

### Summary of Changes

Goals:

1. Display/hide preview via OnToken events
2. A preview should be cleared via OnPreviewLeave when hovering off the popup.

### CODE REVIEW

**Comment by jasonLaster** [comment]
Thanks @haoRchen. This will be great to get in

**Comment by darkwing** [comment]
Hello @haoRchen!  Is this still a WIP or do you have more coming?  Thank you!

**Comment by jasonLaster** [comment]
I believe he has more coming

**Comment by darkwing** [comment]
Any update @haoRchen ?  I'd love to help!

**Comment by haoRchen** [comment]
Hey @darkwing. Currently, the preview displays onTokenEnter but does not clear. Something is causing mouseOver to be called twice and somehow skips the call for TokenLeave(which clears the preview). Could you help me look into whats causing this?

**Comment by jasonLaster** [comment]
Alright, I looked into this and confirmed what you were seeing @haoRchen. CodeMirror is in fact replacing the ENTIRE line everytime we update a marker, thus no mouseleave events...

by the way, i used chromes break on dom event here...

**Comment by jasonLaster** [comment]
I took a look at this today and found some interesting things:

1. token events could ignore entering editor-mount
2. we could stop using markText
3. we could simplify our rules for entering and leaving

ultimately, i think this is pretty close to being perfect.

I left logging in to help w/ the debugging

**Comment by jasonLaster** [comment]
Alright, I'm really excited to share this work. @haoRchen and I have been working on a new system for Preview events that I believe will be much more robust:


It starts with *tokenEvents*, where we introduce two new codeMirror events `tokenEnter` and `tokenLeave`. These events have really helpful properties: 

- tokenEnter is triggered once per token
- tokenEnter is only fired for tokens that we could preview or jump to. Not whitespace, syntax, ...
- tokenLeave is triggered immediately after the mouse leaves the element

*tokenEvents* simplifies the problem and makes everything below possible.

Preview component:
- `tokenEnter` - kick off a preview 
- `tokenLeave` - clear the preview, unless we're hovering on the popup 
- `componentDidUpdate` - updates the highlight
- `render` - renders the popup if the Preview is ready...

Popup Component:
- `onMouseLeave` - clears the preview, unless we're hovering on the highlight...

Redux:

- `updatePreview` is now much simpler because it doesn't need to check if the token is valid or if we're hovering on the same element.
- `setPreview` used to have a race conflict when you cleared before it finished, we now check that the preview is updating before we set the final value

**Comment by haoRchen** [comment]
looks good!

**Comment by jasonLaster** [comment]
- i removed the shared helper because the two were different
- cleaned up circle ci
- fixed the travis tests

**Pull request merged**
