### PR TITLE
Fix #5707: added flow coverage to parser/types.js

### LINKED ISSUE #5707: [Flow] add flow coverage to parser/types.js
`src/workers/parser/types.js` is missing `// @flow` which is causing a bunch of other components that import these types to get anys.

### PR DESCRIPTION
**Pull request by yalooong**
Fixes Issue: #<5707>

### Summary of Changes

This PR added flow coverage to parser/types.js. There are three errors remaining (see screenshots for more details). My last commit (dede657) attached with original error message, was a fix to solve the incompatibility of AstPosition which is similar to two of the remaining errors. What I did was a quick fix and I believe there is better way to solve it.

### Testing

I ran "yarn run test-all". Both test suites and lint passed.

### Screenshots
First

Second

Third

### CODE REVIEW

**Comment by jasonLaster** [comment]
Hey @yalooong I pushed some tweaks to your PR for the two other inconsistent cases. I'm not really sure how to fix this error:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/workers/parser/index.js:53:15

*** Recursion limit exceeded ***

     50│   Scope
     51│ } from "./types";
     52│
     53│ export type { PausePoint } from "./pausePoints";
     54│
```

Hopefully some smart folks can help us out...

**Comment by humphd** [comment]
I have no idea either, so I asked the Twitters for help https://twitter.com/humphd/status/977192201154330631.  Maybe someone will know something that can help us here.

**Comment by jasonLaster** [comment]
@yalooong could you help tidy up the lint and jest issues in the meantime? Ping me on slack if you have any questions about pulling down my tweaks from github

**Comment by yalooong** [comment]
Thanks. I fixed.

**Comment by jasonLaster** [comment]
Okay, so I added some additional tweaks and **critically** removed the `// @flow` header from `parser/types.js` which removes the recursion. The reason I did that was the rest of the work is great and we *should* land it.

Once this lands, @yalooong can you open a new PR with *just* the `// @flow` header added to `parser/types.js`. This way it'll be much easier to debug.

**Comment by yalooong** [comment]
@jasonLaster Yes, I will do. Thank you for your active help.

**Pull request merged**
