### PR TITLE
Do not render breakpoint toggle if none exist.

### PR DESCRIPTION
**Pull request by Garbee**
Associated Issue: #1648

### Summary of Changes

* Check for breakpoint(s) existence before rendering the toggle button.

### Test Plan

Open up clean debugger profile. See by default there is no breakpoint toggle checkbox. Set a breakpoint somewhere and verify the checkbox then renders.

### Screenshots

No Breakpoints:

no-points

Breakpoints:

breakpoints

### CODE REVIEW

**Comment by Garbee** [comment]
Just updated the PR to also add an `aria-label` since the checkbox doesn't have a label. To increase a11y handling. Also refactored a little bit to remove the `breakpointsExist` variable that is no longer necessary for re-use since the node is never rendered unless it is true and all of its usages within the node were checking for it to be true.

**Comment by wldcordeiro** [comment]
@Garbee Maybe only show it when we have more than one? A toggle for all breakpoints when there's only one seems a little pointless.

**Comment by Garbee** [comment]
Can you join in on our call today at 3 EST? I'm basically rethinking this entire interface today. Will discuss more there first to show things running for clarity.

**Comment by jasonLaster** [comment]
@Garbee I'll be there. Excited about this work.

I pushed a small style nit fix: replace the ternary with a guard statement. let me know if it's alright and we can merge. otherwise happy to revert

**Pull request merged**
