### PR TITLE
checking if source is javascript for pretty print

### PR DESCRIPTION
**Pull request by warjet777**
Associated Issue: #1226

### Summary of Changes

* Imported function to `src/utils/editor.js`, to check if a source url is JS. 
* Made sure `shouldShowPrettyPrint()` function returned false if the source wasn't JS

### Test Plan
- [ ] Select a non-JS source and observe that the pretty print button no longer displays

Let me know if I've done something wrong. I'm new to contributing to open source software, so any suggestions are welcome!

### CODE REVIEW

**Comment by warjet777** [comment]
@jasonLaster or @jlongster can I get some assistance? CI seemed to have issues with this step:

```bash
$ npm run flow
```

The build exceeded a 4GB memory limit at that step. I ran the command locally and it worked. I'm not sure why it exceeded the limit. I don't think I can rerun CI build, so I'm not sure what to do here. If you could let me know what I need to do that would be great!

**Comment by jasonLaster** [comment]
No worries.
CI is being flakey. It should be fixed though so try rebasing and pushing.
Or just rebuilding from the circle UI.

**Comment by warjet777** [comment]
Thanks! CI passed.

**Comment by jasonLaster** [comment]
Thanks @warjet777 this looks great.

One thing I'd add to your test plan is:
- [ ] Select a JS source and observe the pretty print button

**Comment by jasonLaster** [comment]
@warjet777 while I was testing your patch I found that we don't get the source contentType field in the client, which makes it impossible to detect if a console eval'd source is JS!

https://github.com/devtools-html/debugger.html/issues/1273

(Thought I'd share)


Thanks for the help. I hope you snag another [up for grab](https://github.com/devtools-html/debugger.html/issues?q=is%3Aissue+is%3Aopen+label%3A%22up+for+grabs%22)

**Pull request merged**
