### PR TITLE
[Outline] clicking class selects source in editor

### PR DESCRIPTION
**Pull request by nyrosmith**
Associated Issue: #5259 

outline_click_class

### CODE REVIEW

**Comment by bomsy** [comment]
Nice one!! 
It seems like it highlights two locations (class A on line 41 and functionC on line 53) the first time you click class A in the outline

**Comment by nyrosmith** [comment]
@bomsy you are absolutly right! But I have no idea how this can even be possible...

**Comment by nyrosmith** [comment]
I just tried to debug it and I can't reproduce it.

**Comment by jasonLaster** [comment]
Lets look into the multiple highlights on master. It's likely unrelated to this PR

**Pull request merged**
