### PR TITLE
Continue conversion from commonjs to es modules

### PR DESCRIPTION
**Pull request by peterschussheim**
# Continue conversion from commonjs to es modules
Associated Issue: #1884

## Summary of Changes

Refactor the following files to use ES module syntax:
- [x] src/client/chrome.js
- [x] src/client/chrome/commands.js
- [x] src/client/chrome/create.js
- [x] src/client/chrome/events.js
- [x] src/client/firefox/commands.js
- [x] src/client/firefox/create.js
- [x] src/client/firefox/events.js
- [x] src/client/index.js
- [x] src/components/Editor/Tabs.js
- [x] src/components/SecondaryPanes/Breakpoints.js
- [x] src/components/SecondaryPanes/WhyPaused.js
- [x] src/utils/log.js
- [x] src/utils/pause.js
- [x] src/utils/redux/middleware/thunk.js
- [x] src/utils/redux/middleware/wait-service.js

### Test Plan

- [x] `yarn test-all`

### CODE REVIEW

**Comment by jasonLaster** [comment]
We're going to 🔫 commonjs soon

**Comment by peterschussheim** [comment]
Any thoughts why `src/utils/prefs.js` is so troublesome to convert?  I tried many different solutions for this file but always get one of the following syntax errors during loading of the compiled `debugger.js` bundle:

- `Uncaught SyntaxError: Unexpected token import`
- `Uncaught SyntaxError: Unexpected token export`

**Comment by jasonLaster** [comment]
Forget it. It's a trap

**Comment by jasonLaster** [comment]
Let's do everything but that lol

**Pull request merged**
