### PR TITLE
Fix CallStack Group with anonymous function.

### LINKED ISSUE #7579: Hitting breakpoints fails with l10n error
Nightly 66.0a1 (2018-12-20) (64-bit)

STR:
- Open https://angular-quickstart.glitch.me/
- Toggle breakpoint in one of the ts files
- Reload

AR:  Debugger loads and then blow up into a white panel

Before refresh:
image

After:

Error: `TypeError: "l10n is undefined"`

```
TypeError: "l10n is undefined"

    formatDisplayName resource://devtools/client/debugger/new/src/utils/pause/frames/displayName.js:85 renderDescription resource://devtools/client/debugger/new/src/components/SecondaryPanes/Frames/Group.js:126 render resource://devtools/client/debugger/new/src/components/SecondaryPanes/Frames/Group.js:164 finishClassComponent resource://devtools/client/shared/vendor/react-dom.js:10332 updateClassComponent resource://devtools/client/shared/vendor/react-dom.js:10295 beginWork resource://devtools/client/shared/vendor/react-dom.js:10894 performUnitOfWork resource://devtools/client/shared/vendor/react-dom.js:12713 workLoop resource://devtools/client/shared/vendor/react-dom.js:12730 renderRoot resource://devtools/client/shared/vendor/react-dom.js:12770 performWorkOnRoot resource://devtools/client/shared/vendor/react-dom.js:13359 performWork resource://devtools/client/shared/vendor/react-dom.js:13281 performSyncWork resource://devtools/client/shared/vendor/react-dom.js:13253 requestWork resource://devtools/client/shared/vendor/react-dom.js:13153 scheduleWork$1 resource://devtools/client/shared/vendor/react-dom.js:13022 enqueueSetState resource://devtools/client/shared/vendor/react-dom.js:8845 setState React

onStateChange5Redux	waitUntilService resource://devtools/client/debugger/new/src/actions/utils/middleware/wait-service.js:65 promiseMiddleware resource://devtools/client/debugger/new/src/actions/utils/middleware/promise.js:32 thunk resource://devtools/client/debugger/new/src/actions/utils/middleware/thunk.js:21 dispatch Redux	paused resource://devtools/client/debugger/new/src/actions/pause/paused.js:63 thunk resource://devtools/client/debugger/new/src/actions/utils/middleware/thunk.js:21 bindActionCreator Redux

    paused resource://devtools/client/debugger/new/src/client/firefox/events.js:75 

react-dom.js:11273:5
```

image

[`formatDisplayName`](https://github.com/devtools-html/debugger.html/blob/d5db38f91ef080675fb2fa672c0a1d7a01ca75df/src/utils/pause/frames/displayName.js#L84) isn't called with `l10n`:

image

### PR DESCRIPTION
**Pull request by nchevobbe**
`formatDisplayName` was called without the `l10n`
object, which caused an exception if the last
frame of a stack was anonymous (because we then
use `l10n`).
The fix is simple, pass the `l10n` object to
`formatDisplayName`.
A test is added to ensure we cover this case.
The test do fails without the fix in `Group.js`

Fixes #7579 

### Test Plan

1. Go to https://angular-quickstart.glitch.me/
1. Open the debugger
1. In the debugger, open `app.component.ts`
1. Put a breakpoint on the `export` line
1. Reload the debuggee tab to make the debugger pause
1. Make sure the callstack panel is expanded
1. You should see an `<anonymous> Angular` group in it

### CODE REVIEW

**Comment by nchevobbe** [comment]
TODO:
- [ ] Find out why flow did not report this
- [ ] Write a mochitest?

**Comment by nchevobbe** [comment]
Mochitest is a WIP. I wanted to get feedback before going further.
I created a "mock" because it is way easier to trigger the faulty test case. Not sure how we should name the example files and put them though.

**Comment by jasonLaster** [comment]
I'd probably name the mochitest in a more descriptive fashion `anonymous-function` or soemthing like that.

With that said, I do want to add a real angular mochitest at some point...

**Comment by nchevobbe** [comment]
> I'd probably name the mochitest in a more descriptive fashion anonymous-function or soemthing like that.

Yeah, I agree. I ended up creating a file from the httpServer, as it feels bad to have a fake `angular.js` file only to test this.

**Pull request merged**
