### PR TITLE
[FunctionSearch] Select result item on click

### PR DESCRIPTION
**Pull request by irfanhudda**
### STR
1. Open function search.
2. Click on a result item.
Bug

### Changes
* Add index to `onClick` handler of `ResultList`

### Screenshot
fix

### CODE REVIEW

**Comment by irfanhudda** [comment]
Found a problem with this PR so I'll close this for now

**Comment by irfanhudda** [comment]
After looking into the problem it turn out that there was another bug

### STR
1. Open TodoMVC example in browser
2. Open `js/views/app-view.js` file in debugger.html
3. Open function search in editor and enter `a`.
4. Navigate to lower result by pressing `down` arrow key
5. Now enter `a` in function search to narrow the result
Bug

This problem was because we are trying to scroll to result that don't exist anymore.

**Comment by jasonLaster** [comment]
Is this a dupe #2524?

**Comment by irfanhudda** [comment]
@jasonLaster Just realised that. Closing this for now.

**Pull request closed without merging**
