### PR TITLE
[Editor] Show a link to a generated file - ultimate PR

### PR DESCRIPTION
**Pull request by khal0988**
Associated Issue: #4242

Here's the Pull Request Doc
https://devtools-html.github.io/debugger.html/CONTRIBUTING.html#pull-requests

### Summary of Changes

* Footer shows a short message in the bottom for generated with a link to the root original directory aka webpack "(From bundle.js)"
* Hover over message, tooltip comes up and shows full message "(source mapped from bundle.js)"
* Click on short message "(From bundle.js)" to jump to the start of the original file in the generated bundle

### Test Plan

- [x]  open http://firefox-dev.tools/debugger-examples/examples/increment/ in firefox
- [x]  navigate to webpack/math.js
- [x]  the Footer should show a message in the bottom for generated with a link to the root original directory aka webpack "(source mapped from bundle.js)"
- [x]  files without original sources will show nothing in footer or will footer wont appear if not necessary

Here's the Debugger's Testing doc
https://docs.google.com/document/d/1oBMRxV8A2ag2t22YsQOxTdEv0mXKzIg0tggJjRkU1S0/edit#.
Feel free to improve it!

### Screenshots/Videos
screen shot 2017-11-15 at 1 31 57 pm

screen shot 2017-11-15 at 1 32 06 pm

screen shot 2017-11-15 at 2 06 06 pm

### CODE REVIEW

**Comment by bomsy** [comment]
@khal0988 For some reason, i'm not able to push to your branch. This diff below should fix the failing tests and should add a test for the sourcemap links

```diff
diff --git a/src/test/mochitest/browser_dbg-pretty-print.js b/src/test/mochitest/browser_dbg-pretty-print.js
index 846aab48..178553df 100644
--- a/src/test/mochitest/browser_dbg-pretty-print.js
+++ b/src/test/mochitest/browser_dbg-pretty-print.js
@@ -32,8 +32,7 @@ add_task(async function() {

   // The pretty-print button should go away in the pretty-printed
   // source.
-  ok(!findElement(dbg, "editorFooter"), "Footer is hidden");
-
+  ok(!findElement(dbg, "prettyPrintButton"), "Pretty Print Button is hidden");
   await selectSource(dbg, "math.min.js");
-  ok(findElement(dbg, "editorFooter"), "Footer is hidden");
+  ok(findElement(dbg, "prettyPrintButton"), "Pretty Print Button is visible");
 });
diff --git a/src/test/mochitest/browser_dbg-sourcemaps2.js b/src/test/mochitest/browser_dbg-sourcemaps2.js
index a85204e1..d8e8867a 100644
--- a/src/test/mochitest/browser_dbg-sourcemaps2.js
+++ b/src/test/mochitest/browser_dbg-sourcemaps2.js
@@ -38,4 +38,12 @@ add_task(async function() {

   await waitForPaused(dbg);
   assertPausedLocation(dbg);
+
+  // Tests the existence of the sourcemap link in the original source.
+  ok(findElement(dbg, "sourceMapLink"), "Sourcemap link in original source");
+  await selectSource(dbg, "main.min.js");
+  ok(
+    !findElement(dbg, "sourceMapLink"),
+    "No Sourcemap link exists in generated source"
+  );
 });
diff --git a/src/test/mochitest/head.js b/src/test/mochitest/head.js
index e4f269cb..37e2fd57 100644
--- a/src/test/mochitest/head.js
+++ b/src/test/mochitest/head.js
@@ -914,7 +914,8 @@ const selectors = {
   stepOut: ".stepOut.active",
   stepIn: ".stepIn.active",
   toggleBreakpoints: ".breakpoints-toggle",
-  prettyPrintButton: ".prettyPrint",
+  prettyPrintButton: ".source-footer .prettyPrint",
+  sourceMapLink: ".source-footer .mapped-source",
   sourcesFooter: ".sources-panel .source-footer",
   editorFooter: ".editor-pane .source-footer",
   sourceNode: i => `.sources-list .tree-node:nth-child(${i})`,
```

**Comment by khal0988** [comment]
@bomsy I was pretty sure the tests needed to be updated. Thanks alot that solved the problem. we can finally land this xD

**Comment by jasonLaster** [comment]
jumping can be achieved with the `jumpToMappedLocation`, 

e.g. `jumpToMappedLocation({sourceId: selectedSource.id, line: 1, column: 1 })`

https://github.com/khal0988/debugger.html/blob/maps4/src/components/Editor/EditorMenu.js#L99-L100

**Pull request merged**
