### PR TITLE
Add `dir=""` to the html tag on the index.html

### PR DESCRIPTION
**Pull request by wldcordeiro**
Associated Issue: #852 

### Summary of Changes

* add `dir` attribute to the main html element of index.html

### Testing

* [x] passes `npm test`
* [x] passes `npm run lint`

### CODE REVIEW

**Comment by jlongster** [comment]
What's this do?

**Comment by wldcordeiro** [comment]
@jlongster according to @nt1m this lets Firefox change the direction of the content from left to right and right to left more easily. Simple enough addition I figured I'd open the PR and see whether we want it or not.

**Comment by jlongster** [comment]
It's fine with me! Just curious. Note that we use a different `index.html` for the Firefox panel, so it's probably more important that we change in there. Are you willing to help land a change on mozilla-central?

**Comment by wldcordeiro** [comment]
@jlongster yeah I can use hg and make a change on m-c. Heh, I just did a `ctrl+p` and typed index.html to find it

**Comment by jlongster** [comment]
Look in `devtools/client/debugger/new/index.html`. If you don't mind, file a bugzilla bug and make a patch, and I'll review it, and we can get it checked in there too.

**Pull request merged**
