### PR TITLE
Add Martin to the Core Team :wave:

### PR DESCRIPTION
**Pull request by jasonLaster**
I'd like to be the first to welcome Martin to the team!

Martin has helped in almost every capacity: code health, new features, windows compat, bug fixes. More importantly, he's been a friendly voice in the community. He's helped new comers feel welcome and has also helped us triage and keep the bug list actionable. 

Cheers 🍺

### CODE REVIEW

**Comment by nyrosmith** [comment]
Looks good to me :-)
Thanks for trusting me that mich!

**Comment by wldcordeiro** [comment]
I take it Travis isn't setup properly? Ready to go! Welcome @nyrosmith 😄

**Comment by darkwing** [comment]
Nyro's icon is a bit large but not a blocker.

**Comment by jasonLaster** [comment]
nope, he's going to upgrade his avatar tomorrow

**Pull request merged**
