### PR TITLE
Run mozilla-central Frames dependent tests on Travis.

### PR DESCRIPTION
**Pull request by nchevobbe**
This adds all the smartrace component tests, as
well as copy message/export all context menu entries tests.

### CODE REVIEW

**Comment by nchevobbe** [comment]
Okay, tests that are expected to fail **do** fail:

```
failed test:  devtools/client/shared/components/test/mochitest/test_smart-trace-grouping.html 
failed test:  devtools/client/shared/components/test/mochitest/test_smart-trace-source-maps.html 
failed test:  devtools/client/webconsole/test/mochitest/browser_webconsole_context_menu_copy_entire_message.js 
```
How should we proceed from there @jasonLaster ? Landing this will cause all the PR to fail (and would need maintainer to look at each travis job manually). I feel like we should wait until the fixed version of those tests land in m-c.
What's your take on this?

**Comment by jasonLaster** [comment]
I think that's right, when the fixes are in we can bump the travis.yml MC sha

**Comment by nchevobbe** [comment]
Patch landed on mc. I updated the `MC_COMMIT` here, so let's see if travis is okay with those changes now.

**Comment by jasonLaster** [comment]
hmm, travis crashed... do we need anything else in github?

**Comment by jasonLaster** [comment]
just landed - https://github.com/devtools-html/debugger.html/pull/7850 which should make this easier

**Comment by nchevobbe** [comment]
```
devtools/client/debugger/new/test/mochitest/browser_dbg-breakpoints-cond.js | A promise chain failed to handle a rejection: bpClient.setCondition is not a function - stack: setBreakpointOptions devtools/client/debugger/new/src/client/firefox/commands.js 215:10
```

re-built a few time but this is still happening. Is this because of the `MC_COMMIT` change ?

**Pull request merged**
