### PR TITLE
Add chrome tests for source maps

### LINKED ISSUE #405: Source Maps - Integration Tests
In addition to having unit tests that mock out different aspects (e.g. client) we should have at least one integration test that covers the most common cases.

### PR DESCRIPTION
**Pull request by jasonLaster**
Fixes #405. 

Notes:
* Adds an env flag for debugging chrome
* Adds the "Inspectable Pages" tab to the list
* Adds a test for debugging an app with source maps

Note: the test is actually flakey now and half the time does not pause even though the breakpoint is added and button clicked... Looking into the protocol now

### CODE REVIEW

**Comment by jasonLaster** [comment]
I disabled the test so that i can look into the flakiness later. I believe it's a timing issue with the connection and when commands are being issued.

**Comment by jlongster** [comment]
Don't we already download Firefox for the integration tests? Is it possible to download Firefox Dev Edition so we can test against Firefox? I wonder if Firefox wouldn't be flaky (and I'd rather be consistently testing Firefox right now).

**Comment by jasonLaster** [comment]
> testing firefox

That's a good point. I'd like to merge this work as it will be useful in the future and then follow up by downloading firefox.

> flakiness

I'm not sure if it's chrome specific, we'll see.

**Comment by jlongster** [comment]
I'd like to be mindful about committing code that needs a lot of follow-up... what's the benefit of committing it now? We can leave this PR open until at least the test is running (I'm fine with Firefox as a follow-up)

**Comment by jasonLaster** [comment]
@jlongster mind taking another look now that the tests pass. Note, I added #482 to switch to firefox soon. After that, it would be nice to have CI run both firefox and chrome.

**Comment by jlongster** [comment]
Looks fine to me! Looks like one of the cypress runs failed? Not sure if that's related or not...

**Comment by jasonLaster** [comment]
Hmm, interesting. It was very consistent locally, but it might be slower on CI. You might have noticed that I added some pauses in there for good measure. I actually did not test it without them when it started working, but it might be at play here. I can look into this later if it's an issue

**Pull request merged**
