### PR TITLE
#3506 WhyPaused to JSX

### PR DESCRIPTION
**Pull request by ksaldana1**
Associated Issue: #3506 

### Summary of Changes
* Replace all React.createElement calls to JSX.

### Test Plan
Previous [snapshot test](https://github.com/devtools-html/debugger.html/blob/master/src/components/tests/WhyPaused.js) passes.

### CODE REVIEW

**Comment by jasonLaster** [comment]
opening (just incase)

**Comment by ksaldana1** [comment]
The tests failed two linting rules that did not get caught in my editor first time around. I closed the PR until I could get back around to fixing them. Will update to get rid of the errors.
```/home/ubuntu/debugger.html/src/components/SecondaryPanes/Frames/WhyPaused.js
  22:1   error  Component definition is missing display name  react/display-name
  48:16  error  Component definition is missing display name  react/display-name
```

**Comment by jasonLaster** [comment]
Feel free to leave the pr open :)

It's all good

**Comment by jasonLaster** [comment]
yeah - that's a good solution. I think its the only one too

**Pull request merged**
