### PR TITLE
fixed the close button alignment with the open tabs by changing flexb…

### PR DESCRIPTION
**Pull request by soheilhm**
…ox property of the parent container

Associated Issue: #<issue number>

### Summary of Changes

* Adjusted tab alignments by changing flexbox property of their parent container

### Test Plan

Look at the style, it's centered.

### CODE REVIEW

**Comment by jasonLaster** [comment]
@soheilhm mind sharing some [screenshots](https://github.com/devtools-html/debugger.html/blob/master/docs/pull-requests.md#screenshots)? It'd be great to see:
* with a lot of tabs
* narrow with the "more dropdown"

**Comment by soheilhm** [comment]
screen shot 2017-01-23 at 8 47 56 pm

**Comment by jasonLaster** [comment]
Found a couple of issues @soheilhm 

**chrome**

looks like flexbox might need to be prefixed here

screen shot 2017-01-24 at 12 11 05 am

I think we want to keep the + button vertically aligned with the toggle buttons. So the tabs will need to shift up a bit so their labels are lined up.

screen shot 2017-01-24 at 12 11 00 am

When the tabs get narrow, things blow up :)

screen shot 2017-01-24 at 12 10 50 am

Tabs have 100 edge cases, it comes with the territory. We've fixed them more than any other component

**Comment by jasonLaster** [comment]
Ping @soheilhm do you think you'll have time to look at this soon?

**Comment by soheilhm** [comment]
Hi Jason,

I am very busy in the next couple kf week to work on it. If anyone else wants to go for it.

**Comment by jasonLaster** [comment]
no worries.

**Pull request closed without merging**
