### PR TITLE
Add an Open Office Hours section

### PR DESCRIPTION
**Pull request by jasonLaster**
It would be great to offer a venue for contributors to 
* talk with the team
* ask questions. 
* meet each other

I think it would also be nice to promote the team [weekly call](https://wiki.mozilla.org/DevTools) as well.

@clarkbw, @jlongster, @helenvholmes, @jbhoosreddy thoughts?

@wldcordeiro, @Zacqary, @Garbee, @bomsy, @jacobjzhang, @kareniel, @amitzur, @ThomasCrevoisier, @jagtalon, @Dalimil interested?

### CODE REVIEW

**Comment by clarkbw** [comment]
I like the idea.  We could just do a live coding session if no one else shows.

Your Event link seems to require a Mozilla Okta account... Is there a public version?

**Comment by jbhoosreddy** [comment]
This makes a lot of sense to me. I remember joining slack or IRC channels for OSS projects to ask for help or mentor ship but due to time zone or other issues, not be able to get much help.

**Comment by jagtalon** [comment]
I'd be down for this :)

**Comment by bomsy** [comment]
Cool idea! down for this :)

**Comment by jasonLaster** [comment]
@clarkbw et al, does the event link work for you?

**Comment by jasonLaster** [comment]
@jbhoosreddy yeah. One thing I like about it, is if we get stuck trying to help someone in IRC or Github we can suggest they stop by and we can help them out in person.

**Comment by jbhoosreddy** [comment]
> does the event link work for you?

The link does not seem to work for me.

But I will be down for this idea also. 👍

**Comment by kareniel** [comment]
I like it! Won't be able to attend though, as those are work hours for me. :/

**Comment by clarkbw** [comment]
> @clarkbw et al, does the event link work for you?

I don't think so, I keep trying it in Opera where I'm not logged into anything.  It seems to require a google account, maybe that's intended but I had assumed it would just show a calendar event or listing with the dates / times.

**Comment by jasonLaster** [comment]
@clarkbw what do you think about also including a link to our vidyo #devtools room, so others can listen in as well?

[url](https://v.mozilla.com/flex.html?roomdirect.html&key=n9vJUD3L1vRMHKQC5OCNRT3UBjw)

My one concern is that we'll confuse contributors who don't know which call to join :)

**Comment by clarkbw** [comment]
> My one concern is that we'll confuse contributors who don't know which call to join :)

I share that concern.  Anyone is welcome to join our weekly call but I would worry that they wouldn't get enough value from it so I wouldn't want to direct them there.  I'd rather direct them to some where else where we can more directly work with them.

**Comment by Garbee** [comment]
I think having some kind of open channel for people to try and find someone involved to help them out is great. Not everyone works on this kind of schedule though (or some of us may just have "whatever comes up" for ours.) I think having a directory of contact points to get in touch with people to try and setup a time to discuss things as-needed would be more beneficial compared to a set office-hour(s) period.

The only thing I'll say on promoting the weekly status meetings is proceed with caution. I can easily see having too many people trying to jump in becoming a problem of some kind (not sure on the technical side since I haven't been in one of these yet.)

**Comment by jasonLaster** [comment]
Here is the link to the hangout - https://hangouts.google.com/hangouts/_/calendar/amFzb24ubGFzdGVyLjExQGdtYWlsLmNvbQ.30mdpa6ncqn8uttvmrj9b9d3jc?authuser=0

**Comment by ThomasCrevoisier** [comment]
Really great idea ! Definitely interested by it too :)

**Comment by Zacqary** [comment]
This sounds cool in theory. I'm personally worried about whether or not I can make it if it's during the week, but I'd say give it a try and I'll do my best to show up once in a while.

As far as helping people who need it, I'd also suggest some more official way of scheduling time to talk to people who are hopping into IRC or Slack at the wrong time to get attention.

**Comment by clarkbw** [comment]
We can try this and see if it works.

@jasonLaster It does feel like perhaps we need something more like Office (after) Hours than something during the regular working hours.  What do you think?

**Comment by amitzur** [comment]
I think it's great to have a time when mentors dedicate to answer longer questions and have deeper discussions with contributors (if that is indeed the intent).
Regardless, for smaller on-the-spot issues the IRC is still beneficial, and for async communication there should also be a medium like email or a discussion forum, or like @Garbee suggested - a directory of contact points.

**Comment by jasonLaster** [comment]
@clarkbw yeah - w/r/t to after hours. Lets play it by ear, it's harder to schedule but maybe we can do something :)

I'm already scheduling lots of calls with people too. It could be fun to explore a monthly 3 hour after hours hacking session, or something like that.

**Comment by arthur801031** [comment]
Hi guys, are we having an office hour today? :)

**Comment by Garbee** [comment]
Those are Tuesday's at 3PM EST.

**Comment by arthur801031** [comment]
@Garbee 

So no more office hour on Thursday?

**Comment by jasonLaster** [comment]
Also Thursdays.

The team is at an on site. But feel free to setup by and see if others
attend.

**Pull request merged**
