### PR TITLE
Use addons icons for extensions

### PR DESCRIPTION
**Pull request by darkwing**
I thought it would be cool to show an icon for Firefox extensions:

extensions

### CODE REVIEW

**Comment by jasonLaster** [comment]
I like it. What if we changed moz-extension:// to "Extensions"...

While you'r in there we should fix angular:// to be consistent with webpack's scheme :wink:

**Comment by jasonLaster** [comment]
lol you already fixed angular

**Comment by jasonLaster** [comment]
Also, this feels a bit big, might be fine though

**Comment by darkwing** [comment]
Updated the text value and icon size:

extensionsicon

**Pull request merged**
