### PR TITLE
Revert "Revert "[Exceptions] Update Checkbox Options Language (#6086)…

### PR DESCRIPTION
**Pull request by jasonLaster**

### CODE REVIEW

**Comment by jasonLaster** [comment]
seeing this error
https://travis-ci.org/devtools-html/debugger.html/builds/371650228?utm_source=github_status&utm_medium=notification

**Comment by darkwing** [comment]
@jasonLaster You said not to touch this on Friday because you knew what was going on here -- any insight?

**Comment by jasonLaster** [comment]
looking soon

**Comment by jasonLaster** [comment]
running some travis runs here:
- [baseline](https://travis-ci.org/devtools-html/debugger.html/builds/373202728)
- [prefs change](https://travis-ci.org/devtools-html/debugger.html/builds/373201672)

**Comment by jasonLaster** [comment]
so the tweaks lead to helpful travis errors:
https://travis-ci.org/devtools-html/debugger.html/builds/373202728

**Comment by darkwing** [comment]
So is Firefox using the pref and not what we're sending from the thread client?  Any tiny bit of background here?

**Comment by darkwing** [comment]
I'm slightly concerned that we're going to have to manage two prefs, or should we bail on the new pref, revert to old, and simply set a reverse value?

**Comment by jasonLaster** [comment]
I think the issue is that the old pref is used by the old debugger...
we shouldnt use it

**Comment by darkwing** [comment]
Travis seems happy

**Pull request merged**
