### PR TITLE
Fix 7864: Set required node ver to 10.3.0

### LINKED ISSUE #7864: Tests require Node 10, package.json says 7.7
I'm using Node 8 and a bunch of tests fail because Node 8 doesn't have Promise.prototype.finally (Node 10 does).

- Should the minimum version be bumped to Node 10 in `package.json`?
- Or do we want to inject a `.finally` polyfill?

MDN says Promise.prototype.finally is Node 10.0.0+ but not sure how reliable that info is:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally

With Node 8.15:

```
Test Suites: 12 failed, 184 passed, 196 total
Tests:       70 failed, 10 skipped, 1576 passed, 1656 total
Snapshots:   7 failed, 413 passed, 420 total
Time:        118.244s
```

With Node 10.15:

```
Test Suites: 1 failed, 195 passed, 196 total
Tests:       1 failed, 10 skipped, 1645 passed, 1656 total
Snapshots:   1 failed, 434 passed, 435 total
Time:        108.516s, estimated 111s
```

(Still have one test to fix, please disregard.)

### PR DESCRIPTION
**Pull request by dhyey35**
Fixes #7864

### Summary of Changes

* Updated minimum node version to 10.3.0 in `package.json`

@fvsch I have used https://node.green/#ES2018-features-Promise-prototype-finally for deciding the minimum node version required, I think it's a pretty reliable resource as they run automated tests against all node versions.

I ran tests on `10.3.0` on my end they work as expected

### CODE REVIEW

**Comment by fvsch** [comment]
The change looks good to me.

**Comment by jasonLaster** [comment]
> error debugger.html@0.6.0: The engine "node" is incompatible with this module. Expected version ">=10.3.0".

**Comment by dhyey35** [comment]
@jasonLaster Can you please let me know your node version. According to me any version including and above 10.3.0 shouldn't have this issue

**Comment by darkwing** [comment]
@dhyey35 Thank you for submitting this!  Looking at our travis build system, I'm seeing `$HOME/.nvm/nvm.sh; nvm install 9; nvm use 9;`.  I pushed a branch that uses `>=9.11.0` as the value and it appears to be working (https://travis-ci.org/devtools-html/debugger.html/builds/492245253), so use that version and I think we'll be good to go!

**Comment by fvsch** [comment]
> so use that version and I think we'll be good to go!

That won't achieve much because users on Node 9.11+ and <10.3 won't be able to run Jest tests locally and will get no warning.

Running `yarn test` with Node 9.11.2 gives me 68 failed tests, including a bunch of:

> TypeError: Promise.resolve(...).finally is not a function

If I'm understanding the situation correctly, we have two test suites:

1. The Jest tests included in debugger.html, which can be run with `yarn test` and require Node 10.3+. They are also run for each PR on CircleCI, with Node 11 apparently:
    ```
    Status: Downloaded newer image for node:11.9.0
  using image node@sha256:0cc92d0934e9f990755b9b22bd449d665c559587b8f8bc4d0d4db33264f60762
    ```

2. Mochitests from mozilla-central, running on Travis using Node 9.

Not sure if we can align the two.

For context: the purpose of bumping the Node version in debugger.html's package.json was to let yarn warn users of Node <10.3 who try to run `yarn test` that they need a minimum Node.js version.

**Comment by dhyey35** [comment]
@darkwing I see #7946, do let me know if I can do something.

**Comment by darkwing** [comment]
@dhyey35 I landed my test branch -- thank you so much for tackling this -- I learned a lot! 👍 

Please grab another issue and keep up the good work!

**Pull request closed without merging**
