### PR TITLE
[Sources] updated fix "set directory root" bug

### PR DESCRIPTION
**Pull request by yalooong**
Updates regarding of PR: #6052 

### Summary of Changes

Fix a minor bug when setting domain directory as root.

STR:

1. Go to http://firefox-dev.tools/debugger-examples/examples/todomvc/
2. On the left panel, right click on "firefox-dev.tools" and Click on "Set directory root"
3. Notice the root name is not displayed correctly.

n1owkgixyv

### Test Case

Added ui test case in regarding to this bug.

### CODE REVIEW

**Comment by yalooong** [comment]
@mutdmour Could you show me how to reproduce your test?

**Comment by mutdmour** [comment]
ya. 
clone my repo `git clone https://github.com/mutdmour/debugger.html`
checkout my test branch `git fetch origin 5100-test-source-tree && git checkout 5100-test-source-tree`
run `yarn install`
run the test `yarn test ./src/components/tests/SourcesTree.spec.js`
you should see an error like the one [here](https://circleci.com/gh/devtools-html/debugger.html/12333?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
make your fix to `SourcesTree.js` and rerun the test

**Comment by yalooong** [comment]
@mutdmour So I made an one line change to your test and it passed. Basically, I was comparing the project root name at this line `if (sourceContents && sourceContents.name !== rootLabel)`.
screen shot 2018-04-25 at 14 22 37

**Comment by mutdmour** [comment]
Nice, thanks for helping with that.

**Pull request merged**
