### PR TITLE
[WIP][Tree] Virtualize tree

### PR DESCRIPTION
**Pull request by AnshulMalik**
Fixes Issue: #4168

### Summary of Changes

* Virtualize the 🌲 component so that we can handle huge trees

Currently, the source tree works really nice and fast. But there are some side effects, the scopes panel has some issues, when we expand, it doesn't expand the first time, but expands second time. I think that's because the properties are fetched asynchronously and the re-render doesn't take place when the results arrive.

### CODE REVIEW

**Comment by jasonLaster** [comment]
Oh neat, i believe in the past we might have tried something like this. At first glance your implementation looks great. Did you compare this approach to what is in react-virtualized?

@nchevobbe curious what you think

**Comment by AnshulMalik** [comment]
@jasonLaster I had a look at react-virtualized, it seemed to me that we are using a lot of custom functionality, like expand and collapse and handling keyboard navigation, I am not sure if we can do those things without modifying the codebase of react-virtualized. So I went the other way.

**Comment by jasonLaster** [comment]
Oh yeah, was mostly asking because it is nice to see how others do things. Have you checked to see how this does with scrolling? I believe that was an issue with react-virtualized

https://hacks.mozilla.org/2017/11/async-panzoom-apz-lands-in-firefox-quantum/

**Comment by AnshulMalik** [comment]
Thanks @nchevobbe, those link will really help.

And yeah, when height is not fixed, then my current solution won't work. I'll see how react-virtualised achieves that.

I'll also explore IntersectionObserver.

**Comment by jasonLaster** [comment]
### Editor/componentWillReceiveProps

We try and resize the gutter and bp every time, that is kind of crazy. We should only do this, if the source has changed or some other indicator:
`resizeBreakpointGutter`, `resizeToggleButton`



### Editor/componentWillUpdate

can we prevent doing costly work here?

    this.setText(nextProps);
    this.setSize(nextProps);
    this.scrollToLocation(nextProps);

 

### Editor/setupEditor

4 seconds, can we speed this up?



### SourcesTree/renderItem

It's by far the slowest part of the tree, and renderItem is disproportionately spending time in getIcon, which is URL.parse heavy...

[video](http://recordit.co/s02VZpD7Yb)

**Comment by jasonLaster** [comment]
closing this so we can focus on the quick wins above

**Pull request closed without merging**
