### PR TITLE
Improve Editor gutter hover 

### PR DESCRIPTION
**Pull request by jasonLaster**
Fixes Issue: #5979 

### Summary of Changes

* highlights active lines on hover
* softer highlight for empty lines
* moves gutter styles to gutter.css

Todo

- it would be nice to animate off the highlight
- fix a bug with scrolling

### CODE REVIEW

**Comment by darkwing** [comment]
This PR scares me a little bit.  Prior to very, very recent changes, a lighter line number means you can't interact with it -- now we're changing it to the default state?  Seems like it would give the impression you couldn't interact with any lines.  Just my two cents.

**Comment by jasonLaster** [comment]
Yeah, that could be true... 

I was thinking that this is softer on the eyes... but we could be overthinking this by a factor of 10x

**Comment by jasonLaster** [comment]
@violasong @digitarald what do you think?

**Comment by digitarald** [comment]
@jasonLaster I like it. There is a slight risk, but overall I don't think our short spell of styling disabled gutter entries will keep users from hovering over the gutter to delightfully discover this.

nit, hard to tell from low fps GIF, but the animation could be a little snappier with `0.1s` (vs `0.2s`). To animate out, could this use `transition` (vs `animation`)?

**Comment by jasonLaster** [comment]
Thanks @digitarald i think that makes sense.

I'll look into transition. First time using these commands.

@mcote - http://g.recordit.co/JGYhTujZdr.gif

the str is just scroll a lot over the gutter, and then mouse over it...

**Comment by violasong** [comment]
I like the idea of this lighter line number color by default because they're more visually heavy than they need to be currently. Without the zebra effect, I don't think the light color looks disabled.

I'm a bit worried that the very subtle different grays for both numbers and hover arrows in this prototype might not be clear enough. Maybe when hovering over the gutter, the non-breakable lines should actually go lighter, and not be hover-able? (I know we thought this looked broken previously, but I'm curious if it looks less broken when the zebra is in effect.)

**Comment by jasonLaster** [comment]
Closing this as it's not clear how we want to move forward

**Comment by jasonLaster** [comment]
seeing something weird
http://g.recordit.co/Ubanf7yEZ1.gif

**Pull request closed without merging**
