### PR TITLE
[Source Tree] show first root #1337

### PR DESCRIPTION
**Pull request by Dalimil**
See https://github.com/devtools-html/debugger.html/issues/1337#issuecomment-264318724
screenshot_2016-12-01_22-26-54

### CODE REVIEW

**Comment by jasonLaster** [comment]
This looks really good.

Mind trying to add some unit tests here for the source-tree utils?

Roping in @gregtatum who has lots of source-tree experience.

**Comment by Dalimil** [comment]
But it's not ideal, because it always picks the domain of the first script it receives as the top one... Keeping track of the tab url in the sources-tree would require more work + I'm not sure which group should be expanded when a website has all its scripts hosted externally.

**Comment by jasonLaster** [comment]
Haha that's a really interesting problem. 

Perhaps we create a new issue for sorting domains. I don't want to clutter those issue

**Comment by jasonLaster** [comment]
https://github.com/devtools-html/debugger.html/issues/1374

**Comment by jasonLaster** [comment]
Sorry that this sat @Dalimil I was traveling on the past three days :/

This is some great work, but I'm noticing that the "first source" rule might be racey. 

I got this when i went to mozilla.com.

screen shot 2016-12-06 at 1 13 33 pm
screen shot 2016-12-06 at 1 12 20 pm

How about with this PR we drop the domain sorting and then do it properly in a new issue. I agree that we want to use the tab URL as the point of reference. I'll stub out a reducer update that stores it.

**Comment by Dalimil** [comment]
OK, makes sense.

**Comment by jasonLaster** [comment]
Thanks @Dalimil!

**Pull request merged**
