### PR TITLE
Additional close items

### PR DESCRIPTION
**Pull request by bomsy**
Associated Issue: #1104

### Summary of Changes

* Add new properties
* Added new closeOtherTabs and closeTabsToRight

### Testing

* [x] passes `npm test`
* [x] passes `npm run lint`

### Screenshots/Videos 
addcloseitems

### CODE REVIEW

**Comment by jasonLaster** [comment]
This looks great @bomsy.

I was thinking about it last night and I think an improvement would be to improve the close action or add a new action named closeTabs that would know how to close many tabs. The advantage is that now we fire off N actions for closing each tab.

Perhaps we make a new issue for this.

**Comment by bomsy** [comment]
Cool. I think thats a great idea.
I'll create the issue and a PR.

Thanks!

**Comment by bomsy** [comment]
Also i had a thought.
Do we want to hide or disable (grey out) close items that are may not be useful.
e.g If there's only one tab , "Close other tabs" should be disabled, cos its of no use.
Your thoughts?

**Comment by jasonLaster** [comment]
> Do we want to hide or disable close items

@bomsy I think that's a great idea. I'd propose hiding those items if there's only one tab.
just created this https://github.com/devtools-html/debugger.html/issues/1139. mind snagging it?

**Comment by bomsy** [comment]
excellent!  will do!

**Pull request merged**
