### PR TITLE
Style functions in outline view

### PR DESCRIPTION
**Pull request by amelzer**
Associated Issue: #2901 

### Summary of Changes

* Removed bullet points and decreased left padding for functions in outline view
* Added pointer and hover effect to functions in outline view

### Test Plan

- [x] Hover over functions in outline view changes background according to theme

### Screenshots/Videos (OPTIONAL)
outlinefunctions

### CODE REVIEW

**Comment by jasonLaster** [comment]
This looks great @amelzer!

My one style critique is that it would be nice to have the hover background be full width. Other than that I think it's ready!

**Comment by amelzer** [comment]
I disagree. A full width hover would still require a little margin to the right which would require to implement a little handler for function names exceeding the width of the panel (either overflowing the container or shortening the function name). I would just leave it as it is, to be honest.Jason Laster <notifications@github.com> hat am 8. Juni 2017 um 15:03 geschrieben:This looks great @amelzer!My one style critique is that it would be nice to have the hover background be full width. Other than that I think it's ready!--You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub:https://github.com/devtools-html/debugger.html/pull/3128#issuecomment-307096616

**Comment by codehag** [comment]
Also, it looks like our `ul` element is set by default to have a margin of 40. I wonder if we want to do that, or if we should normalize it 🤔

**Comment by amelzer** [comment]
@codehag The 40px ul padding seems to be browser default. 

Thank you for your other suggestions, it does look quite nice now.
outlinefunctionsv2

**Comment by codehag** [comment]
Looks great! Thanks for your hard work!

**Pull request merged**
