### PR TITLE
fix Center Pane - add a minimum width #1029

### PR DESCRIPTION
**Pull request by briantully**
Associated Issue: #1029

### Summary of Changes

* change center-pane parent div min-width to 300px

### Testing

* [X] passes `npm test`
* [ ] passes `npm run lint`

npm run lint reveals the following errors not related to my changes:

```
/Users/brian.tully/Sites/debugger.html/public/js/components/Accordion.js
  18:14  error  Expected indentation of 6 spaces but found 13   indent
  54:15  error  Expected indentation of 12 spaces but found 14  indent

/Users/brian.tully/Sites/debugger.html/public/js/components/App.js
  87:15  error  Expected indentation of 4 spaces but found 14  indent
  88:13  error  Expected indentation of 2 spaces but found 12  indent

/Users/brian.tully/Sites/debugger.html/public/js/components/Expressions.js
  110:7  error  Expected indentation of 8 spaces but found 6  indent

/Users/brian.tully/Sites/debugger.html/public/js/components/RightSidebar.js
  195:5  error  Expected indentation of 6 spaces but found 4  indent
  196:7  error  Expected indentation of 8 spaces but found 6  indent
  197:7  error  Expected indentation of 8 spaces but found 6  indent
  198:5  error  Expected indentation of 6 spaces but found 4  indent
  199:7  error  Expected indentation of 8 spaces but found 6  indent
  200:5  error  Expected indentation of 6 spaces but found 4  indent
  201:7  error  Expected indentation of 8 spaces but found 6  indent

/Users/brian.tully/Sites/debugger.html/public/js/components/Sources.js
  39:15  error  Expected indentation of 4 spaces but found 14  indent

/Users/brian.tully/Sites/debugger.html/public/js/components/SourceSearch.js
  96:15  error  Expected indentation of 4 spaces but found 14  indent
  97:15  error  Expected indentation of 4 spaces but found 14  indent
  98:13  error  Expected indentation of 2 spaces but found 12  indent

/Users/brian.tully/Sites/debugger.html/public/js/components/SourcesTree.js
  68:21  error  Expected indentation of 6 spaces but found 20  indent
  69:21  error  Expected indentation of 6 spaces but found 20  indent

/Users/brian.tully/Sites/debugger.html/public/js/components/utils/ManagedTree.js
  12:14  error  Expected indentation of 6 spaces but found 13  indent

/Users/brian.tully/Sites/debugger.html/public/js/utils/sources-tree.js
  263:12  error  Expected indentation of 4 spaces but found 11  indent
  264:12  error  Expected indentation of 4 spaces but found 11  indent
  265:12  error  Expected indentation of 4 spaces but found 11  indent

✖ 22 problems (22 errors, 0 warnings)
```

These all have to do with indentation code style. Do these need to be fixed or does the .eslintrc file need to be updated to ignore these errors? I have a git stash that fixes all of the indentation issues in the unrelated files and passes `npm run lint`. Should I commit those fixes to this PR or is there a separate issue ticket to get lint passing?

### Screenshots/Videos (OPTIONAL)
center-pane-min-width

### CODE REVIEW

**Comment by jasonLaster** [comment]
Wow. So strange. 

I'll take a look tomorrow. Thanks for the help on the UI! Were launching soon and this polish really helps. 

By the way there's a nice new issue with hiding the collapse breakpoints. You might like that as it's a little more react than the last two.

**Comment by jasonLaster** [comment]
Hmm, I think a slightly smaller minimum like 200 would be better. While, we don't really support this case well now, it is possible for people to dock to the right.

The npm lint issue is strange. CI doesn't show it, and i can't repro it locally.

**Comment by jlongster** [comment]
We do we need a minimum width? The editor is the area that flexes, so I don't think it makes sense to have a minimum width.

**Comment by jlongster** [comment]
I don't think we should merge this before the uplift; it's a change to the main part of the UI and I'm not sure I agree with it. We haven't had any other feedback about it so changing it right before the uplift is risky if others don't like it.

**Comment by briantully** [comment]
@jasonLaster Agreed! I've updated min-width to 200px.

@jlongster That's fine by me. I was simply contributing towards issue #1029 
When the editor gets anywhere below 200px wide, there are some UI elements that get hidden (i.e., file selector menu) and file tab text gets badly truncated  -- so I can empathize for the desire to enforce a min-width :)

**Comment by wldcordeiro** [comment]
I lean towards having a minimum width because the editor is the focus of the debugger in many ways and it makes sense to always give it enough space to display all its contents. Thanks for the work @briantully

**Comment by jasonLaster** [comment]
Hmm, for some reason it looks like there's an implicit min width here...

**Comment by jasonLaster** [comment]
Hmm, never mind... the implcit min width is only true for large windows. If the debugger is small, then it's possible for the center pane to be tiny.

**Comment by jasonLaster** [comment]
Thanks for the help @briantully. Sorry we're not moving forward on this now, but it was a really helpful process.

**Pull request closed without merging**
