### PR TITLE
Frame count badge

### PR DESCRIPTION
**Pull request by amitzur**
Associated Issue: #4659 

### Summary of Changes

* new react component - `<Badge>{...}</Badge>` is intended to show a number with rounded background

* added some css utility classes a la bootstrap. If this is considered good, I'd add more and do some refactoring in existing css.

### Test Plan

I updated the snapshot for Group.js test.

This is pretty similar to GitHub's UI (even though I saw that only after I implemented):
screen shot 2017-11-10 at 2 57 21 pm

### CODE REVIEW

**Comment by jasonLaster** [comment]
I like this!

* lets clean up the patch
* add a screenshot so we can review UI (long badges, narrow sidebar, ..)
* review the css style... I like the utility class names, but it is different, so lets get some buy in (@codehag, @wldcordeiro)

**Comment by amitzur** [comment]
- What cleanup is needed? The irrelevant linted files?
- Here's a low res screencast:
(i think the edge case where it overlaps isn't that important, but let me know otherwise)
fw_count_pr
- Would be happy to discuss and elaborate on slack or in one of the weekly calls. @codehag @wldcordeiro

**Comment by jasonLaster** [comment]
> What cleanup is needed? The irrelevant linted files?

yep
 
> UI nit

I think i would prefer a smaller badge... but that's a minor thing.

@violasong what do you think?

**Comment by violasong** [comment]
Yes, a bit less top and bottom padding on the badge would be nice. Console has a badge style you could match.

**Comment by jasonLaster** [comment]
thanks. here's the css
https://searchfox.org/mozilla-central/source/devtools/client/themes/webconsole.css#100

we probably don't want to pull in all of webconsole.css, but we can copy it into a file that we can eventually share... if that's what we want to do

**Comment by amitzur** [comment]
> Edit: The Console badge class name is .message-repeats
Where in the console's UI can I find it?

**Comment by amitzur** [comment]
> > What cleanup is needed? The irrelevant linted files?

> yep

I wanna do this myself, but not sure - how do I pull commits out of the branch? Do I create another branch for this PR?

**Comment by amitzur** [comment]
> Yes, a bit less top and bottom padding on the badge would be nice. Console has a badge style you could match.

@violasong So, you're saying no circle style? And do you think the colors here work?

**Comment by jasonLaster** [comment]
Hmm, look into `git rebase interactive` or just make another commit on top, or squash commits ...

**Comment by amitzur** [comment]
- [x] UI cleaned up
- [x] patch cleaned up

Have a look at how it shows up with made up number of 1-3 digits:
screen shot 2017-11-13 at 8 00 45 pm
screen shot 2017-11-13 at 8 00 59 pm

**Comment by wldcordeiro** [comment]
👏 I dig this! Great job @amitzur! Like @jasonLaster mentioned cleaning up the CSS would be nice but can be done in a follow-up.

**Comment by jasonLaster** [comment]
I don't know. I like the CSS, and it's nice to have the full example w the
util vlasses. It just brings up the qs do we want to adopt this style :)

**Pull request merged**
