### PR TITLE
docs: fix typos

### PR DESCRIPTION
**Pull request by tbroadley**
### Summary of Changes

* Fixed a few typos in documentation.

### CODE REVIEW

**Comment by tbroadley** [comment]
@jasonLaster For sure!

**Comment by tbroadley** [comment]
@jasonLaster I used a tool I've built (https://github.com/tbroadley/github-spellcheck-cli) to find them.

**Comment by tbroadley** [comment]
I've created a PR against `devtools-linters` to remove some actual misspellings from that project's dictionary: https://github.com/jasonLaster/devtools-linters/pull/18

**Comment by jasonLaster** [comment]
Thanks so much

**Pull request merged**
