### PR TITLE
update mochitest docs

### PR DESCRIPTION
**Pull request by jbhoosreddy**
I'm making small updates to the docs as they are a little outdated. I noticed that API list is not exhaustive. If you'd like I can update that in this PR also.

### CODE REVIEW

**Comment by clarkbw** [comment]
doc changes look good!

**Comment by jlongster** [comment]
Thanks! Sure, feel free to add the new APIs here too.

**Comment by jbhoosreddy** [comment]
I took a pass at updating the API description in the docs. I broke it down to separate headings so that it is more manageable and easy to understand.

**Comment by jbhoosreddy** [comment]
@jlongster would it be okay to merge this PR first. It makes three different changes to different docs. It would be additional work to break it down again.

#750 would end up removing the API documentation and simply refer to the docs.

**Pull request merged**
