### PR TITLE
[reps] land reps transpiled modules in mc

### PR DESCRIPTION
**Pull request by jasonLaster**
### Summary of Changes

- re-purposes copy-modules to transpile reps
- we need to transpile because we need to strip flow types
- we can do AMD with a regex

### To Dos

- handle spurious imports
- remove unnecessary comments and indent the code
- fix it until it works 😉

### CODE REVIEW

**Comment by darkwing** [comment]
Still looking at this but building bricks because we override the devtools/moz.build file, which currently looks like this:

https://hg.mozilla.org/mozilla-central/file/tip/devtools/moz.build

We should probably leave this file alone.

**Comment by nchevobbe** [comment]
Do not override moz.build all the way up : 

```diff
diff --git a/bin/copy-modules.js b/bin/copy-modules.js
index b7e4920c..ee7ac0d5 100644
--- a/bin/copy-modules.js
+++ b/bin/copy-modules.js
@@ -120,7 +120,7 @@ function createMozBuildFiles() {
     // There should be a moz.build in every folder between the root and this
     // file. Climb up the folder hierarchy and make sure a each folder of the
     // chain is listing in its parent dir moz.build.
-    while (path.dirname(dir) != ".") {
+    while (!path.dirname(dir).endsWith("devtools/client/shared/components")) {
       const parentDir = path.dirname(dir);
       const dirName = path.basename(dir);
 ```

**Comment by darkwing** [comment]
@nchevobbe Did you want to push this across the finish line or shall we close?

**Comment by jasonLaster** [comment]
lets close and discuss in orlando

**Pull request closed without merging**
