### PR TITLE
Use the license checker

### PR DESCRIPTION
**Pull request by tromey**
### Summary of Changes

* Add devtools-license-checker dependency and command
* Change circle.yml to invoke it

### CODE REVIEW

**Comment by jasonLaster** [comment]
@tromey i'm seeing this error:

screen shot 2017-05-10 at 9 27 39 pm

Perhaps we need to exclude the file in our `.flowconfig`

**Comment by tromey** [comment]
I wonder why I don't see that.  I did see it in devtools-core (I updated the flow config there).  Anyway, will fix.

**Comment by tromey** [comment]
Oh, I know why.  The tests fail for me locally, which I knew wasn't due to my patch, so I pushed with `--no-verify`.  Which skipped flow.  Sorry about that.

**Comment by tromey** [comment]
Had to `--no-verify` again, so let's see.

**Comment by tromey** [comment]
Ignoring the percy thing as discussed.

**Pull request merged**
