### PR TITLE
Highlight all text on watch expression edit

### PR DESCRIPTION
**Pull request by AnshulMalik**
Associated Issue: #5220 

### Screenshots/Videos (OPTIONAL)

watch

### CODE REVIEW

**Comment by jasonLaster** [comment]
looks great. It would be nice to have a comment on what the code is trying to do :)

**Comment by AnshulMalik** [comment]
Hehe, I thought we hate comments :P

**Comment by jasonLaster** [comment]
this is the exception to the rule lol

**Comment by jasonLaster** [comment]
do we need to touch SearchInput?

**Comment by jasonLaster** [comment]
CC @Loirooriol

**Comment by AnshulMalik** [comment]
It's already a one-time thing in `SearchInput` because it's in `componentDidMount`. So we are good without this change.

**Comment by AnshulMalik** [comment]
We should probably make this a helper function, `moveCursorToEnd`

**Comment by Loirooriol** [comment]
Moving the cursor to the end when edition starts also seems a bit arbitrary. Selecting all the text may be more useful, this way you can just start typing and replace the old expression with the new one.

**Comment by jasonLaster** [comment]
I think given that we're double clicking to edit the user would expect the text to be highlighted.

**Comment by AnshulMalik** [comment]
watch

**Comment by jasonLaster** [comment]
:fire:

**Pull request merged**
