### PR TITLE
Moved workers to their own Worker directory.

### PR DESCRIPTION
**Pull request by jselmani**
Associated Issue: #3725 

### Summary of Changes

* Created new directory for workers (parser, pretty-print, search) and moved them
*** Path is now src/workers/*
* Altered src/test/tests-setup.js to change test environment path
* Altered webpack.config.js to reflect changes for workers

### Test Plan

After changing paths in several files, I would run `yarn test` and continue through the process.
All local tests passed, except for one, due to line endings.  My machine utilized CRLF, while the upstream code was in LF, which caused the issue.  After changing settings to LF, all tests ran without error.

I did not perform CI testing, but spoke with @jasonLaster through a call who asked me to PR this commit.

### Screenshots/Videos (OPTIONAL)
capture

### CODE REVIEW

**Comment by codehag** [comment]
Looks like there are still a couple of places that need renaming:
(from `yarn flow`)
```
Error: src/actions/types.js:17
 17: import type { SymbolDeclaration, AstLocation } from "../utils/parser";
                                                         ^^^^^^^^^^^^^^^^^ ../utils/parser. Required module not found

Error: src/components/PrimaryPanes/Outline.js:14
 14: } from "../../utils/parser/getSymbols";
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ../../utils/parser/getSymbols. Required module not found

Error: src/components/PrimaryPanes/Outline.js:15
 15: import type { AstLocation } from "../../utils/parser/types";
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^ ../../utils/parser/types. Required module not found

Error: src/components/SymbolModal.js:24
 24: import type { SymbolDeclaration } from "../utils/parser/types";
                                            ^^^^^^^^^^^^^^^^^^^^^^^ ../utils/parser/types. Required module not found

Error: src/reducers/ast.js:11
 11: import type { SymbolDeclarations, AstLocation } from "../utils/parser/types";
                                                          ^^^^^^^^^^^^^^^^^^^^^^^ ../utils/parser/types. Required module not found

Error: src/utils/editor/index.js:16
 16: import type { AstPosition, AstLocation } from "../parser/types";
                                                   ^^^^^^^^^^^^^^^^^ ../parser/types. Required module not found
```

from `yarn lint-md`

docs/updates/updates-7-25-2017.md
  22:22-22:31  warning  Link to unknown file: `src/utils/parser/getSymbols.js`                 remark-validate-links  remark-validate-links
  30:48-30:61  warning  Link to unknown file: `src/utils/parser/tests/fixtures/expression.js`  remark-validate-links  remark-validate-links

**Comment by jselmani** [comment]
I'll fix this and PR after I'm done.

**Comment by codehag** [comment]
Also, welcome! :tada:!

**Comment by jselmani** [comment]
Thanks @codehag happy to be here!

**Comment by jasonLaster** [comment]
hmm, really close... i can help you get over the finish line

**Pull request merged**
