### PR TITLE
Remove feature flags

### PR DESCRIPTION
**Pull request by justtry**
Associated Issue: #1205 

### Summary of Changes

* Remove Tabs, SourceMaps, Pretty Print feature flags.

### Testing

* [x] passes `npm test`
* [x] passes `npm run lint`

### CODE REVIEW

**Comment by jasonLaster** [comment]
One quick change, would you mind removing the features in the development.json and firefox.json as well :)

**Comment by jasonLaster** [comment]
Thanks!

**Comment by justtry** [comment]
of course!

**Comment by jasonLaster** [comment]
Thanks @justtry!

**Pull request merged**
