### PR TITLE
Directory restructure

### PR DESCRIPTION
**Pull request by wldcordeiro**
Associated Issue: #1153 

### Summary of Changes

* reorganize the directories of the project to follow the `src/` convention rather than a `public/js` convention.

### Testing

* [x] passes `npm test`
* [x] passes `npm run lint`

### Screenshots/Videos (OPTIONAL)

@jasonLaster @jlongster want to give this a good review? Might have missed something. One test also fails for me with a timeout. Not sure what I can do about that.

> 1) sources should download a sourcemap and create sources:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

### CODE REVIEW

**Comment by jasonLaster** [comment]
Awesome! This will land before the toolbox console work. 

My guess is the timeout I'd related to the node try script moving network requests 

Thanks for doing this!

**Comment by wldcordeiro** [comment]
Gah, I really don't get the failure. It's not present in master currently but is in this branch. @jasonLaster if you could give it a try and see if you have any ideas it'd be great (I'll be on IRC tomorrow or should be, I just need to configure my client heh)

**Comment by jasonLaster** [comment]
@wldcordeiro just pushed a fix. It was tough to track down!

**Comment by jasonLaster** [comment]
@wldcordeiro just rebased. this should hopefully be good to go soon

**Comment by wldcordeiro** [comment]
Looks good now. Tried it out locally and tests pass as well as CI

**Pull request merged**
