### PR TITLE
4651-call-stack-should-not-open-automatically

### PR DESCRIPTION
**Pull request by Fischer-L**
Associated Issue: #4651

### Summary of Changes
Make the call stack not open automatically on pause

### CODE REVIEW

**Comment by Fischer-L** [comment]
@jasonLaster a PR for #4651 , please have a look thanks

**Comment by bomsy** [comment]
@Fischer-L a tiny lint issue
image

**Comment by bomsy** [comment]
We might also need to update some of the mochitests

**Comment by Fischer-L** [comment]
> We might also need to update some of the mochitests

Thanks for reminding. Updated. Should be ok, wait for the test runs.

**Pull request merged**
