### PR TITLE
#3032: added drop shadow to preview popup

### PR DESCRIPTION
**Pull request by giltayar**
Associated Issue: #3032 

### Summary of Changes

* Added `box-shadow` to rule `.popover .preview` in `preview.css`

### Test Plan

Since this is a visual change, no tests, but there's a screenshot below.

### Screenshots/Videos
screen shot 2017-06-21 at 8 08 40 pm

#GoodnessSquad

### CODE REVIEW

**Comment by giltayar** [comment]
This PR was also implemented by @yasminny and @adigoldstein. Thanks!

**Comment by jasonLaster** [comment]
Can we soften it a bit softer? and perhaps angled a bit more rightward

**Comment by jasonLaster** [comment]
Also, mind running `yarn storybook` and taking a look at our experimental bottom bar?

**Comment by jasonLaster** [comment]
screen shot 2017-07-21 at 11 06 03 am

**Pull request merged**
