### PR TITLE
Display empty lines UI

### PR DESCRIPTION
**Pull request by darkwing**
As @jasonLaster merged the redux piece, this PR is for the UI piece of displaying empty vs. executable lines

### CODE REVIEW

**Comment by darkwing** [comment]
As with the previous PR, the functionality works with a normal source tab but pretty-printed source tabs throw an error.

**Comment by jasonLaster** [comment]
Seeing one flow error and two mochitest errors, which makes sense because we test sliding in our mochitests.
We can no longer slide :P

**Comment by darkwing** [comment]
Working on them right now

**Comment by jasonLaster** [comment]
oh nice. Forgot that you mochitest :)

Try `yarn mochi breakpoints-reloading` in debugger land

also we have mochitest docs for

```
yarn copy-assets
```

and getting firefox locally `./bin/prepare-mochitest`

**Comment by jasonLaster** [comment]
🌺

**Pull request merged**
