### PR TITLE
(WIP) Tweak the search bar appearance

### PR DESCRIPTION
**Pull request by jasonLaster**
Associated Issue: #<issue number>

### Summary of Changes

* clean up the colors
* adjust the heights to be more consistent

**Next Steps**
* Fix Source search height (keep it 40px)
* dark theme
  * Make the sidebar headers less prominent
  * remove the zebra call stack frames
  * fix very blue selection

#### New Look

screen shot 2017-03-05 at 6 00 04 pm

screen shot 2017-03-05 at 6 02 18 pm

#### Old Look

screen shot 2017-03-05 at 6 02 58 pm

----

#### Paused UI

screen shot 2017-03-06 at 12 42 11 pm
screen shot 2017-03-06 at 12 41 57 pm

### CODE REVIEW

**Comment by jasonLaster** [comment]
@nchevobbe pointed out that the search options bar is not visually differentiated from the search result items.

**Comment by nchevobbe** [comment]
Not specific to function search, but I think we could polish this up a bit by aligning the buttons

screenshot at mars 06 18-54-31

**Comment by jasonLaster** [comment]
Good find @nchevobbe. Damn, i hate that i'm off by a bit on the close button after just tweaking it :)

**Comment by jasonLaster** [comment]
Just styled the source result list UI in the inspector. Thoughts?

screen shot 2017-03-06 at 12 59 37 pm

**Comment by nchevobbe** [comment]
erf, I think the first one would make more sense, because a lot of people use the debugger docked to the bottom, and vertical space is then limited.
That's the reason I'm not too much into the "card" look for the result.
Is there a rationale displaying the results for file search differently than for function search ?

**Comment by jasonLaster** [comment]
@nchevobbe that's a good point. I think helen was using editor project level search as an inspiration. I agree that it's not as space efficient. 

I'd like to find a happy medium where it's not to dense when we have space, but also more space efficient when we're space challenged.

**Comment by nchevobbe** [comment]
For the design of the function search (but really, the search as a whole), it may be helpful to write down what we will end up to have
- We can __search in file__ for __text__
- We can __search in file__ for __function__
- Hopefully, we'll be able to __search in all files__ for __text__
- maybe be able to __search in all files__ for __function__
- maybe be able to __search in file__ for __variable__
- and then why not __search in all files__ for __variable__
- and each of these search could be constrained by : Regex,  case, whole word, ...

So we have several ideas:
- Where to search (file, all files)
- What to search for (text, function, variables, ..)
- How to search (case (in)sensitive, whole word, Regex)

The result list you did for the function results could be also used for the search in all files.

One thing we could have is all this in a single bar, and the ability to switch from "context" with a button that would open the choices.

```
Search *in file ▾* : a                        for *text ▾* | aA | .*
```
or
```
Search *in al files ▾* : a                   for *function ▾* | aA | .*
```

These context could be automatically selected depending off the keyboard shortcut you use.
I don't know if it would be better than a second toolbar, it was a thought.
I am looking at how to improve the current version too.

**Comment by nchevobbe** [comment]
> I'd like to find a happy medium where it's not to dense when we have space, but also more space efficient when we're space challenged.

Mhh, so we could either use media-queries, or see how we could work with viewport based units (`vh`in this case ? )

**Comment by jasonLaster** [comment]
Yeah - i think media queries like vertical layout would be slick.

* project search will come along soon. That's a Q2 goal. 
* jumping between file/project search is important. (unsolved problem)
* variable search is PRd now (close)
* modifiers are not used for function search as we're using fuzzy aldrin which is way better

**Comment by wldcordeiro** [comment]
@nchevobbe your little sketch resembles what I was thinking of for adding variable and class search. 👍

**Comment by jasonLaster** [comment]
This PR has become pretty big and I hope we can wrap it up and then do some smaller style tweaks:

1. Update Search bars so there's a big and small input and result list
2. Update some details like borders and colors
3. improve contrast and consistence

#### Editor Search
screen shot 2017-03-07 at 5 15 15 pm
screen shot 2017-03-07 at 5 15 05 pm

#### Source Search

screen shot 2017-03-07 at 5 15 40 pm
screen shot 2017-03-07 at 5 15 19 pm

**Comment by wldcordeiro** [comment]
Flow and css lint are complaining currently.

**Pull request merged**
