### PR TITLE
Issue 5324

### PR DESCRIPTION
**Pull request by tripurari001**
Associated Issue: #5324

### Summary of Changes

* removed the word-break property from `no-result-msg` css class in `ProjectSearch.css` file
* added `overflow-wrap` to break word if it exceed the parent (`max-width: 100%`)
* `hyphens: auto` to insert hyphens when word break on letters

#### before 
before

#### after
after

### CODE REVIEW

**Comment by jasonLaster** [comment]
CC @ericawright

**Comment by ericawright** [comment]
This works well for English, but once we translate, it's not guaranteed that the words will fit.
Then this happens:
screen shot 2018-02-08 at 2 07 15 pm

I think it would be nice if the words would break on letters if they have to.

**Comment by tripurari001** [comment]
cc @ericawright  Thanks for the suggestion

Added the `overflow-wrap: break-word` to break word if it exceed parent width (` max-width: 100% `)
also added `left-right padding` to `15px` and `hyphen:auto` (not working in firefox 59.0b7 and working in chrome)

after change  

final

**Comment by ericawright** [comment]
@tripurari001 thanks, it looks good! 
I don't know why `hyphens` is not working in this case, it should work on Firefox. I tried on another page and `hyphens` works as expected there, so there's something unique about this. Removing the `overflow-wrap` rule didn't seem to make it work either. I tried fiddling with some sizing rule sand couldn't figure it out. I think this is good for now, and maybe we can open a new bug about the hyphens not working.
Do you know how to rebase and squash these commits so there's only 1? Otherwise I can do it for you.

**Comment by tripurari001** [comment]
@ericawright  Thanks for your help. 
This was my first open-source code contribution and I am Looking forward to do more .
One thing I noticed while fixing this issue is `0 result x` at top right breaks in two line at smaller width ( as you can see in 3rd GIF) 
not sure if it's expected or not

**Comment by AnshulMalik** [comment]
Yep @tripurari001. Thanks for the contribution. It'll be an awesome journey

**Comment by tripurari001** [comment]
@ericawright  Notice this in 3rd gif 
screen shot 2018-02-09 at 10 04 46 pm

**Comment by jasonLaster** [comment]
hmm - we should fix this

**Pull request merged**
