### PR TITLE
Better format duplicate filename text

### PR DESCRIPTION
**Pull request by jaikathuria**
Fixes Issue: #6733

### Summary of Changes

* Add logic that hides the extended file information when both files are same just pretty-printed

### Test Plan

Add the test cases for the following:
* duplicate file path,  different name
* duplicate file path, same name (pretty print)

### Screenshots
screen shot 2018-08-07 at 2 02 49 am

### CODE REVIEW

**Comment by darkwing** [comment]
This is awesome so far @jaikathuria !  I think we should beef up the existing test, or add another, so that we check for the following:

## (no path)
/js/main.js
/js/main.js:formatted

## (*does* show path)
/js/main.js:formatted
/js/deeper/main.js:formatted

The core code you've written may already do that, so I think we just need a test :)

**Comment by jaikathuria** [comment]
Sure, I will go ahead and write the test for this 👆🏻

**Comment by darkwing** [comment]
I love it @jaikathuria !  Great work!  👍 💯 🥇

**Comment by jaikathuria** [comment]
With that my first PR merged 🌟🎉Thank you so much @darkwing ✌🏻

**Pull request merged**
