### PR TITLE
fix(package): update flow-bin to version 0.37.4

### PR DESCRIPTION
**Pull request by clarkbw**
Closes #1499

https://greenkeeper.io/

### CODE REVIEW

**Comment by jasonLaster** [comment]
Hmm, do you need a yarn update. Do you expect that to happen automatically?

**Comment by clarkbw** [comment]
> Do you expect that to happen automatically?

I do! 

Seems I have an upstream branch issue...

**Comment by jasonLaster** [comment]
@clarkbw where is this stuff at?

Should we merge? Is it blocked?

**Comment by clarkbw** [comment]
We can merge this. Need to open a new issue to review why the yarn lock file isn't updating

**Comment by jasonLaster** [comment]
@clarkbw is this needed after the last yarn PR?

**Comment by clarkbw** [comment]
> @clarkbw is this needed after the last yarn PR?

pulling out the yarn update work and just checking the original PR

**Pull request merged**
