### PR TITLE
Wait on sources

### PR DESCRIPTION
**Pull request by jasonLaster**
This also requires a small fix on mc's panel.js but the main idea is here.

### CODE REVIEW

**Comment by jlongster** [comment]
Sounds good. So this works? Does this mean we could `renderRoot(App)` ahead of the `startDebugging` calls too? If you wanted, we could still make `startDebugger` block on `initPage` there as well, if you want to be more consistent.

This looks like a good direction though; let's wait to merge until I cut a new release (tonight hopefully) just in case something goes wrong.

**Comment by jasonLaster** [comment]
> Does this mean we could renderRoot(App) ahead of the startDebugging calls too? 
Yes. 

> let's wait to merge until I cut a new release
Sounds good.

**Comment by jlongster** [comment]
Can you apply the changes from https://bugzilla.mozilla.org/show_bug.cgi?id=1302862 to your local Firefox repo, and run all the tests with this change locally? Just want to make sure there's not some clear breakage. We have to land this chance on m-c first, and then land the above bug, but if anything is wrong we won't see failures until we try to land the above bug, so it's worth trying to catch anything early.

**Comment by jlongster** [comment]
Also, something you could do to make sure this is behaving how we want: in one of the tests that needs sources, remove them from the `initDebugger` call and run the test several times. If it passes, it is indeed waiting for the sources to be loaded.

**Comment by jasonLaster** [comment]
That's a good idea, i've been running the change locally, but without the changes to `initDebugger`. Will do that now

**Comment by jlongster** [comment]
I bet DAMP (the tool that tracks Firefox performance) is going to show a decrease in perf in loading, too, because it tracks the `open` method of the panel. But that's ok... it's not really a decrease in perf, it's just moving around the events.

**Comment by jasonLaster** [comment]
I think this is fine to merge as is, but I was not able to get the tests to work when i removed the waitForSources.

The reason for that is that even though the console, in theory, will block on the debugger opening, other commands likes `addBreakpoint` will not block on `initPage`. Because of this, I think it's good to land this, possibly land the `m-c` change which needs this update to work, and then re-evaluate the tests.

**Comment by jlongster** [comment]
(I'm very curious about this too so I'm happy to try it out tomorrow and see why the tests aren't working)

**Comment by jasonLaster** [comment]
Cool. I think you have a good point about init debugger.

Happy to have it off. I'm in the middle of code search.

**Comment by jlongster** [comment]
Didn't have time to look at this more today. It's not a bugfix though so it's not too urgent. I'll take a look next week.

**Comment by jlongster** [comment]
These changes work for me. I applied this patch and made the `open` method of the panel block on the promise returned from `bootstrap`, and ran the `browser_dbg-editor-select.js` tests without explicitly waiting on sources and it passes. I used `--run-until-failure` and it never failed. I tweaked the `open` method to *not* block on `bootstrap` and the test immediately fails. (It's not a hard racy condition to see)

This verifies that this fix works and we should be able to remove waiting on sources. Note that you will still need to `waitForDispatch("LOAD_SOURCE_TEXT")` if you want to access the editor, but I think that makes sense.

We'll need to land this change, land a bundle update, and then land the m-c tweak. I'll see if everything looks good to land a bundle update today.

**Comment by jasonLaster** [comment]
@jlongster great.

**Pull request merged**
