### PR TITLE
cleanup api

### PR DESCRIPTION
**Pull request by jasonLaster**

### CODE REVIEW

**Comment by jlongster** [comment]
Looks like I need to update the docker build since your console landed. Thanks for opening this PR; I need to update it today for other reasons too. I'll do that now.

**Comment by jasonLaster** [comment]
Sounds good

**Comment by jlongster** [comment]
New docker image available. Should work now.

**Comment by jlongster** [comment]
Oh, I can't trigger it because I didn't create it. Can you kick the CI?

**Comment by jasonLaster** [comment]
kicked

**Comment by jlongster** [comment]
I reverted the image back to a good one, so you can use it now. Still working on updating it.

**Comment by jlongster** [comment]
Mind kicking it again? :)

**Pull request merged**
