### PR TITLE
Support highlighting the full expression

### PR DESCRIPTION
**Pull request by bomsy**
Associated Issue: #3109

WIP - Highlight the entire expression on hover

### CODE REVIEW

**Comment by codehag** [comment]
@jasonLaster @bomsy can you check if the updated test snapshot is correct?

**Comment by codehag** [comment]
(closed by accident)

**Comment by aklt** [comment]
@codehag I just tested this and all the tests complete nicely on my machine :+1:

**Comment by codehag** [comment]
@aklt Super!

**Pull request merged**
