### PR TITLE
fixed active tab header seperation

### PR DESCRIPTION
**Pull request by liorpr**
As a follow up to #1305,

please share what you think,

@jasonLaster @wldcordeiro

### CODE REVIEW

**Comment by jasonLaster** [comment]
Thanks @liorpr!

Mind giving some context on what wrong and what the fix was?

This looks like a mystery to me!

**Comment by jasonLaster** [comment]
Thanks @liorpr!

Mind giving some context on what wrong and what the fix was?

This looks like a mystery to me!

**Comment by liorpr** [comment]
It seemed like the border of the editor div(where the code is mounted with CodeMirror) was taking over so I just subtracted 1px from the tab and added 1px  as a (transparent) border

**Comment by jasonLaster** [comment]
Looks great in firefox and chrome

**Pull request merged**
