### PR TITLE
[Source Search] Performance is too slow for fast typing

### PR DESCRIPTION
**Pull request by arthur801031**
#1319

### CODE REVIEW

**Comment by arthur801031** [comment]
Hi @jasonLaster

I've an off topic question. I used `git fetch upstream` and `git merge upstream/master` to fetch the latest commits from master. In the terminal, it asked me to enter a commit message. Then, this commit message show up whenever I create a new branch. For instance, `Merge pull request #1 from devtools-html/master` and `mergeMerge remote-tracking branch 'upstream/master'` commits in this PR came from this merge. How do I remove these commits messages when I create a new PR?

Thank you! :)

**Comment by bomsy** [comment]
@arthur801031 Do `git rebase upstream/master` instead of `git merge upstream/master`, that should squash the commits.

**Comment by jasonLaster** [comment]
```diff

     if (sourceText && sourceText.get("text") &&
-      selectedSource != nextProps.selectedSource) {
+      selectedSource != prevProps.selectedSource) {
       const query = this.state.query;
       const count = countMatches(query, sourceText.get("text"));
-      this.setState({ count: count, index: 0 });
+      this.setState({ count: count, index: 0 }); // eslint-disable-no-did-update-set-state
+      this.replaceState({  ... })
       this.search(query);
     }
```

**Comment by jasonLaster** [comment]
@arthur801031 can we keep the debounce for *doing the search* but immediately update the search input with the query and not lose any chars?

**Comment by arthur801031** [comment]
@jasonLaster

I think this fixes the issue. Please check. Thank you!

**Pull request merged**
