### PR TITLE
update ignores

### PR DESCRIPTION
**Pull request by jasonLaster**

### CODE REVIEW

**Comment by jlongster** [comment]
Interesting, why was it passing before this?

**Comment by atiraminor** [comment]
How do I use this app

**Comment by wldcordeiro** [comment]
Comments like this one above have popped up in a few PRs and I can't help but think they're from bot accounts. They're never relevant to what they reply too. 😕

**Comment by jlongster** [comment]
Yeah, I just ignore them :) @atiraminor if you are serious, please check our readme.

**Comment by jasonLaster** [comment]
@jlongster this is not for our `npm run lint` it's for editors
https://github.com/devtools-html/debugger.html/blob/master/package.json#L18-L19

**Pull request merged**
