### PR TITLE
Convert Autocomplete.js into ES6 class

### PR DESCRIPTION
**Pull request by deneuv34**
Associated Issue: #1890

### Summary of Changes

* Autoomplete.js

I just convert `Autocomplete.js` into ES6, and This is my first time for contributing open source project like this. Please correct me if I'm wrong, It will be happy it is right

### CODE REVIEW

**Comment by jasonLaster** [comment]
@deneuv34 Looks like there are some issues with flow. Also, we just merged another feature to Autocomplete that will likely require a rebase

**Comment by deneuv34** [comment]
I just pass several issue in flow, now I have problem with `renderResults(result)` that result parameter is missing annotation. How to pass it, It will be great if you give me some clue :)

**Comment by jasonLaster** [comment]
sorry accidentally closed this: https://github.com/devtools-html/debugger.html/pull/2546

**Comment by deneuv34** [comment]
Thank you @jasonLaster glad to hear that, there is some lesson I learned from your tweak. Hope I can do more contribution in here :smiley:

**Pull request closed without merging**
