### PR TITLE
Fix scope listing hover background

### PR DESCRIPTION
**Pull request by pradeepgangwar**
Associated Issue: #5331 

### Summary of Changes

*  Removed extra padding that was making background shifted by some pixels.

### Screenshots

screenshot from 2018-02-13 03-22-34
screenshot-2018-2-13 debugger

### CODE REVIEW

**Comment by pradeepgangwar** [comment]
PR got a bit late as i was busy with some of my assignments so i forgot about the issue.

**Comment by darkwing** [comment]
Nice start @pradeepgangwar!  We do still need some padding of the tree, however -- it would look better if there was space between the arrow and the left border.

Check out the code for the Sources Tree -- it is a great example of proper 100% hover background but spacing to the left:

hoverspacing

**Comment by jasonLaster** [comment]
hey @pradeepgangwar do you have time to look at this?

**Comment by pradeepgangwar** [comment]
@jasonLaster sorry for the delay i have updated the pr and it looks like this now. 
screenshot from 2018-02-16 00-53-05

**Comment by darkwing** [comment]
Hello @pradeepgangwar !  I pushed a second commit to accommodate for RTL.  I will merge once Travis passes.  Great work!

**Pull request merged**
