### PR TITLE
UI Polish

### PR DESCRIPTION
**Pull request by arthur801031**
Associated Issue: #1704, #1717

### Summary of Changes

* Fix when the sidebars (left and right) are closed you see a horizontal scrollbar

### CODE REVIEW

**Comment by arthur801031** [comment]
@jasonLaster  

Please check. Thank you! :)

**Comment by jasonLaster** [comment]
Hmm. I'm not sure if we want to always overflow hidden. We do want scrollbars with wise elements

**Comment by arthur801031** [comment]
So we only want to set `overflow-x: hidden;` to ` .split-box.vert` when the sidebar(s) are closed?

What are wise elements?

**Comment by jasonLaster** [comment]
Sorry meant wide element like the source tree is deeply expanded.

Yea, I think that's right

**Comment by wldcordeiro** [comment]
Overflow auto might be what you want so the scrollbars appear when needed?

**Comment by jasonLaster** [comment]
Hmm, @wldcordeiro looks like `oveflow:auto` is already in affect. Actually this might be a case of the splitter still being 1px and the width being 100% or flex:1

**Comment by arthur801031** [comment]
Hi @jasonLaster 

I tried setting splitterSize to 0, but it didn't work, so I used this approach instead :)

**Pull request merged**
