### PR TITLE
fixes move tab issue

### PR DESCRIPTION
**Pull request by jainsneha23**
Fixes Issue: #6657

### Summary of Changes

* Fixes move tab issue

### Test Plan

Open a sample project.
Open multiple tabs.
Click on hidden tabs

Example test plan:

- [x] Open the editor
- [x] Click on more tabs icon
- [x] Click on a hidden tab
- [x] The tab loads

### Screenshots/Videos (OPTIONAL)
http://g.recordit.co/vBAG1DaZHb.gif

### CODE REVIEW

**Comment by bomsy** [comment]
Nice one!

**Comment by darkwing** [comment]
Oddly enough I don't see this crash in a Firefox build, the launchpad, or Chrome + launchpad.  I'll keep looking though.

**Comment by kenjiO** [comment]
@darkwing, I think this change has been made in 1215bf2 so that may be why you are not seeing it.

**Comment by jasonLaster** [comment]
yep, that is right

**Pull request closed without merging**
