### PR TITLE
[WIP] Use devtools-reps ObjectInspector

### PR DESCRIPTION
**Pull request by nchevobbe**
I think this is looking good.
It misses 2 things : having global window object in the Scopes panel dimmed ([PR up](https://github.com/devtools-html/devtools-core/pull/555)) and function styling (i.e. `fn()` instead of `function fn()`), which I'll work on today.

This PR should be block by devtools-reps 0.12 bundle.

### CODE REVIEW

**Comment by nchevobbe** [comment]
@jasonLaster do you remember how you got the watch expressions issue ?

**Comment by nchevobbe** [comment]
This should work with devtools-reps 0.12 bundle

**Comment by jasonLaster** [comment]
@nchevobbe getting this error

screen shot 2017-08-10 at 6 49 57 pm

**Comment by jasonLaster** [comment]
this should be good to go when we're green

**Comment by jasonLaster** [comment]
These tests need better getters
devtools/client/debugger/new/test/mochitest/browser_dbg-expressions.js
devtools/client/debugger/new/test/mochitest/browser_dbg-scopes-mutations.js

**Comment by nchevobbe** [comment]
This would be good with the 0.12.1 package.
I'll check those tests too :)

**Comment by nchevobbe** [comment]
Or more like a 0.12.2 version. One test failing is waiting for root function `foo` to be displayed as `foo()`, where we display it as `function foo()` because we don't simplify root functions (for the console).
Maybe omitting the `function` keyword should just be for TINY mode so it behaves like expected in the debugger and in console (for top-level and then nested functions).

For the scope mutation test, it looks like we don't wait enough time: the action is done but nodes are not shown yet. I may re-use what I do on [webconsole test](http://searchfox.org/mozilla-central/source/devtools/client/webconsole/new-console-output/test/mochitest/browser_webconsole_object_inspector.js#43), i.e. wait for dom mutation on the tree instead of waiting for the action to end, which is implementation specific.

I'll tackle that on Monday, **I want** it to be done !

**Comment by nchevobbe** [comment]
The PR for functions is up https://github.com/devtools-html/devtools-core/pull/594

**Comment by jasonLaster** [comment]
> wait for dom mutation

I'd rather find a better Action. It's easy to do this by enabling action logging [here](https://github.com/nyrosmith/debugger.html/blob/convert_modal_to_jsx/src/utils/bootstrap.js#L22-L23)

**Comment by jasonLaster** [comment]
I was able to run yarn copy-assets-watch....

**Comment by nchevobbe** [comment]
Almost there. Need to wait for a fix to `getExpressions(...).findKey is not a function` error to rebase and make sure everything is working fine.

**Pull request merged**
