### PR TITLE
Initialize a breakpoint as loading

### LINKED ISSUE #6771: [Breakpoints] Use `loading` property
At present the Breakpoint object has a `loading` property but it doesn't appear we're actually using it anywhere; i.e. it default to false and never changes.

Ideally we default the value to `true` and then set to `false` when the server returns successful breakpoint syncing.

Once this is working properly, we can update `breakpointSources.js`'s `getBreakpointsForSource` function to check for `!bp.loading` to determine if the breakpoint should display.

### PR DESCRIPTION
**Pull request by Art-Vanderlay**
Fixes #6771

Latest attempt to initialize loading as true

### CODE REVIEW

**Comment by darkwing** [comment]
Presumably we'd need to set this to `false` somewhere, which may be why tests are failing.

**Comment by darkwing** [comment]
@AnshulMalik or @Bomsy, could you take a look at this?  I've tried this in the past and ran into the same issues.

**Comment by AnshulMalik** [comment]
This is more complex than I thought it would be, I'll try to look into it tonight.

**Comment by darkwing** [comment]
Any progress here @AnshulMalik ?

**Comment by AnshulMalik** [comment]
Yeah, there seems to be some issue with breakpoints not persisting aka pending breakpoints.
Not sure why this is happening though. Will try again

**Pull request closed without merging**
