### PR TITLE
Feature/history reducer :tada:

### PR DESCRIPTION
**Pull request by codehag**
allows going back in time!

Project schlomo < -- @jasonLaster

### CODE REVIEW

**Comment by bomsy** [comment]
This looks good!

**Comment by codehag** [comment]
http://g.recordit.co/jJEGAIetY5.gif

**Comment by AnshulMalik** [comment]
Awesome

**Comment by wldcordeiro** [comment]
I'm gonna grab this and fix the conflicts @codehag I hope you don't mind. 😄 I just really dig your work and wanna see it in the debugger!

**Comment by codehag** [comment]
This has been hanging for a long time so i would like to finish it up. but there are lots of other things to do -- how about I make a meta bug and you can take over some of those tasks?

**Comment by wldcordeiro** [comment]
Sounds good @codehag I'll help out where I can.

**Comment by codehag** [comment]
ok, so Wellington gets to take over the mochi tests (ask me anything about those!)

we can either break those out into their own bug or wellington can work on those here

**Pull request merged**
