### PR TITLE
Tracking changes in MC

### PR DESCRIPTION
**Pull request by jbhoosreddy**
_AUTOMATED PULL REQUEST VIA BOT_
 - **M** debugger.html/public/js/lib/devtools/shared/transport/websocket-transport.js
 - **M** debugger.html/public/js/lib/devtools/shared/flags.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/shim/Services.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/redux/middleware/wait-service.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/window.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/undefined.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/text-node.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/stylesheet.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/string.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/reps.css
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/rep.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/rep-utils.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/regexp.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/prop-rep.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/object.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/object-with-url.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/object-with-text.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/number.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/null.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/moz.build
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/grip.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/grip-array.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/function.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/event.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/document.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/date-time.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/caption.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/attribute.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/array.js

### CODE REVIEW

**Comment by jbhoosreddy** [comment]
When the bot is live, the logs from the bot can be seen here for debugging: http://52.54.91.129:8080/

There was issues with merge conflicts which the bot didn't handle so it stopped working. I changed it so that it could be handled. I'll monitor it to make sure the bot handles all usual use cases.

**Comment by jasonLaster** [comment]
Hmm strange, the reps should be up to date

**Comment by jbhoosreddy** [comment]
I guess it updated the same PR by itself.

**Comment by jasonLaster** [comment]
closing, as this is covered by #879

**Pull request closed without merging**
