### PR TITLE
Add current cursor info  in footer

### LINKED ISSUE #7189: [Editor] show the line and column in the footer
It would be pretty helpful to show the current cursor line and column offset in the footer of the editor.

### PR DESCRIPTION
**Pull request by emanueltimlopez**
Fixes #7189

Add the current line and column to footer in sources.

A little help.
¿The line and colunm should be saved on the store?

@jasonLaster

### CODE REVIEW

**Comment by darkwing** [comment]
Hello @emanueltimlopez !  Thank you for jumping on this!

I made some changes here that will help you:

https://gist.github.com/darkwing/777d339d4b10b6bb5d2de09d011752d4#file-src-components-editor-footer-js-diff

I don't think we need the type/cursorInfo stuff.  Check out the change to Footer.js that I made! :)

linecol

**Comment by jasonLaster** [comment]
This is minor, but I think I would prefer styling the UI (line, column). I believe sublime does this and it uses less horizontal space and is intuitive as your clicking around.

**Comment by emanueltimlopez** [comment]
@jasonLaster how would that be? you have a screenshot?

**Comment by jasonLaster** [comment]
@emanueltimlopez instead of the UI showing `line 20, column 5` it would be `(20, 5)`

**Comment by emanueltimlopez** [comment]
There are no tests for the footer, right? then I will add footer.spec

**Comment by jasonLaster** [comment]
@emmet0r you're probably the first. Feel free to jump into our slack and discuss

**Comment by emanueltimlopez** [comment]
@jasonLaster @darkwing 
Sorry, I think he's ready for a review.

The circleci is broken? :( 
"CircleCI was unable to start the container because the container entrypoint or command failed to start."

**Comment by loganfsmyth** [comment]
@emanueltimlopez Circle should be fixed if you'd like to update.

**Comment by darkwing** [comment]
I made a few updates here; let's see how circle and travis like them!

**Comment by emanueltimlopez** [comment]
Sorry, but still broken

**Comment by darkwing** [comment]
Rebased

**Pull request merged**
