### PR TITLE
(WIP) Preview object properties

### PR DESCRIPTION
**Pull request by jasonLaster**
Associated Issue: #2219

### Summary of Changes

* This adds an expression when we hover on a property, we still need to hide it in watch expressions
* There are perf implications here and other things :)

### CODE REVIEW

**Comment by bomsy** [comment]
Looks good! testing locally now..

**Comment by bomsy** [comment]
LGTM! Fixed a tiny bug with previewExpressions!

@jasonLaster i could do another quick PR soon to address hiding the watch expressions and possible improvements

**Comment by jasonLaster** [comment]
@bomsy go for it!

**Comment by bomsy** [comment]
WIP! hold off on merge!

**Pull request closed without merging**
