### PR TITLE
Fix Open Office Hours link

### PR DESCRIPTION
**Pull request by joshunger**
Fixed the Open Office Hours link

### CODE REVIEW

**Comment by joshunger** [comment]
@jasonLaster I don't think your calendar link is repeating?  Is is supposed to be every Tuesday? 
image

**Comment by jasonLaster** [comment]
Thanks! We're struggling with this link.

**Comment by jasonLaster** [comment]
@joshunger I switched the link to the hangouts, which is probably slightly better. Devs can always add their own event in their calendar :)

@clarkbw curious what you think

**Comment by joshunger** [comment]
@jasonLaster looks good how do you drink with the team?

**Comment by jasonLaster** [comment]
Haha - we all have a beer at our own computers. Basically, when you open a tab, you're just using your browser...

**Pull request merged**
