### PR TITLE
Auto open scopes

### PR DESCRIPTION
**Pull request by bomsy**
Associated Issue: #804

### Summary of Changes

* WIP PR (Open to better options)
* Added a new `autoExpandAll` to enable auto expanding only the first root
* Added new lifecycle method `componentWilReceiveProps` to enable updating the open/close property of the Accordion

### Screenshots/Videos
aos

### CODE REVIEW

**Comment by bomsy** [comment]
@jasonLaster here it is!

**Comment by jasonLaster** [comment]
👍 

This is pretty crazy. I'll study it tomorrow morning so i can wrap my head around it.

I love how the PR is so small.

**Comment by bomsy** [comment]
Yeah...that was part of why it took a bit of a while. I really needed to understand what was going on, so as to make the least amount of changes. haha

**Comment by jasonLaster** [comment]
Yup. It's easier to do a big PR than a small one :)

**Comment by jasonLaster** [comment]
Hey @bomsy, I hope you don't mind, but I
1) squashed your commits
2) removed the right sidebar auto-expand feature for scopes and breakpoints
  - I found that toggling them based on paused caused them to open/close quickly when stepping
  - It's probably better to open them if they're closed when we pause and then leave them open
  - This will be easier when #1277 lands
  - The tree expanding is plenty of logic for one PR :)

**Comment by bomsy** [comment]
that's cool.

**Comment by bomsy** [comment]
Super! happy to get the out!

**Pull request merged**
