### PR TITLE
Adding MobX to framework frames feature

### PR DESCRIPTION
**Pull request by jacobjzhang**
Associated Issue: #4661

Here's the Pull Request Doc
https://devtools-html.github.io/debugger.html/CONTRIBUTING.html#pull-requests

### Summary of Changes

* Added MobX svg asset
* Added logic to detect mobx files

### Test Plan

- [x]  Open debugger
- [x]  Go to https://jsfiddle.net/wf02kyr8/1/
- [x]  Click on "Click me!" button.
- [x]  Open call stack panel.

### Screenshots/Videos (OPTIONAL)

image

### CODE REVIEW

**Comment by jasonLaster** [comment]
Mind checking this in dark theme:

Launchpad > settings > theme

**Comment by jacobjzhang** [comment]
Good catch, swapped it out for a dark one. Looks way better:

image

**Comment by jasonLaster** [comment]
sweet, mind sharing the light theme again?

**Comment by jacobjzhang** [comment]
Np

image

**Comment by amitzur** [comment]
:clap:

**Pull request merged**
