### PR TITLE
Add eslint-flow-type rule to eslint config

### PR DESCRIPTION
**Pull request by twhite96**
### Summary of Changes

* Add `eslint-flow-type` rule: 
```
"flowtype/require-valid-file-annotation": [
      2,
      "always"
    ],
```
to `.eslintrc`

* Add `//@flow` headers to several files in `ast`, `breakpoints`, and `SecondaryPanes`. Will check them off in the issue.

### Test Plan

Tell us a little a bit about how you tested your patch.

Example test plan:

- [x] Since this was a small fix, I ran `yarn test` to make sure there were no conflicts.

### CODE REVIEW

**Comment by darkwing** [comment]
Awesome @twhite96!  Thank you for joining our team 👍

**Comment by twhite96** [comment]
Hey @darling!!! Big fan of yours. Hopefully I can give some useful contributions. ☺️

**Comment by darkwing** [comment]
Hello @twhite96! I think this is going to end up being too general, as it's kicked off loads of flow errors.    Do you know if there's a way to make the flow declaration more pinpoint/exact so we don't have to make all of these changes at once?

**Comment by twhite96** [comment]
@darkwing not sure but I'll definitely investigate.

**Comment by jasonLaster** [comment]
CC @gregtatum i think he did this for perf.html

something like `// @ exclude flow`

**Comment by gregtatum** [comment]
```
// @noflow
```

**Comment by twhite96** [comment]
Okay. Will get on this tomorrow.

**Comment by darkwing** [comment]
Hello @twhite96!  I'm going to close this since it's triggering loads of flow errors and contains a few extra config changes; I think it will be easier if we incrementally implement some flow awesomeness 👍

**Comment by twhite96** [comment]
Sounds good!

**Pull request closed without merging**
