### PR TITLE
Update all jest snapshots after upgrade

### PR DESCRIPTION
**Pull request by darkwing**
A whole bunch of jest snapshots need to be updated now that we've upgraded.  It's making rebasing contributor PRs a nightmare.

### CODE REVIEW

**Comment by jasonLaster** [comment]
merge as soon as circle is green

**Comment by jasonLaster** [comment]
seeing some jest issues here. 

screen shot 2018-05-14 at 1 14 05 pm

**Comment by wldcordeiro** [comment]
Weird that there were failing ones. I ran the suites to get the updates. 🤔

**Comment by darkwing** [comment]
I think I hosed my yarn or was on an old commit.  Just ignore all this.

**Pull request closed without merging**
