### PR TITLE
Show optimized out variables in object inspector

### PR DESCRIPTION
**Pull request by jlongster**
I had most of this done before break but didn't get it finished. This is actually pretty simple. It will show variables and arguments that have been optimized out with a special message:

screen shot 2016-11-28 at 11 39 50 am

### CODE REVIEW

**Comment by clarkbw** [comment]
> It will show variables and arguments that have been optimized out with a special message:

Do you have a test jsfiddle or something where I can play with it?

**Comment by jlongster** [comment]
@clarkbw Sure, go to http://jlongster.com/s/foo.html and click the button. When it's paused, select the 2nd stack frame and look at the second block scope.

**Comment by jlongster** [comment]
Let me know if there are any problems @clarkbw.

**Comment by clarkbw** [comment]
It works, trying it out now.

> look at the second block scope

Just looking at this like its the first time.  I don't really understand why there is a 2nd block scope.  At the very least it would make more sense to me if they were given more context.

**Pull request merged**
