### PR TITLE
Format breakpoints in sidebar with @jasonLaster, fix #604

### LINKED ISSUE #604: Breakpoints - include source name in the description
It would be nice to include the breakpoint source name in the description so that it is clear where the breakpoint is set. This design is similar to how we show source locations in the call stack. It is also similar to how chrome shows it.

This would need to be styled so that the typography is right before we ship it. The patch below is a first pass though so anyone should feel free to pick it up and run with it.

#### Before
screen shot 2016-08-28 at 1 57 23 pm

#### After
screen shot 2016-08-28 at 1 55 19 pm

```diff
diff --git a/public/js/components/Breakpoints.js b/public/js/components/Breakpoints.js
index 72c571a..d6bb329 100644
--- a/public/js/components/Breakpoints.js
+++ b/public/js/components/Breakpoints.js
@@ -9,6 +9,8 @@ const { getSource, getPause, getBreakpoints } = require("../selectors");
 const { makeLocationId } = require("../reducers/breakpoints");
 const { truncateStr } = require("../utils/utils");
 const { DOM: dom, PropTypes } = React;
+const { endTruncateStr } = require("../utils/utils");
+const { basename } = require("../utils/path");
 
 require("./Breakpoints.css");
 
@@ -26,6 +28,15 @@ function isCurrentlyPausedAtBreakpoint(state, breakpoint) {
   return bpId === pausedId;
 }
 
+function renderSourceLocation(source, line) {
+  const url = basename(source.get("url"));
+  // const line = url !== "" ? `: ${line}` : "";
+  return url !== "" ?
+    dom.div({ className: "location" },
+      `${endTruncateStr(url, 30)}${line}`
+    ) : null;
+}
+
 const Breakpoints = React.createClass({
   propTypes: {
     breakpoints: ImPropTypes.map.isRequired,
@@ -84,7 +95,8 @@ const Breakpoints = React.createClass({
         }),
       dom.div(
         { className: "breakpoint-label", title: breakpoint.text },
-        `${line} ${snippet}`
+        dom.div({}, renderSourceLocation(breakpoint.location.source, line)),
+        `${snippet}`
       ),
       isPausedIcon
     );
```

### PR DESCRIPTION
**Pull request by helenvholmes**
@jasonLaster, this includes code from your patch in #604. I've never committed with someone before, do you know how that's done? (I just copied and pasted what you had left in the comments.)

### CODE REVIEW

**Comment by jlongster** [comment]
That "with ..." comment is generated by github when you merge with the "squash and merge" button. I guess when you squash they want to make sure both names are referenced.

**Comment by helenvholmes** [comment]
@jlongster I wrote the "with" manually—I didn't apply a patch, I manually applied the code changes referenced in #604 (there weren't a lot).

I can change this if there's a better way of doing it is what I'm saying, if that makes sense.

**Comment by jasonLaster** [comment]
Looks good @helenvholmes. Some small js lint errors which you can see locally by running `npm run lint-js`

**Comment by jlongster** [comment]
Will double-check this before releasing today, but seems important enough to try to get it. The errors are because this is based off an older branch where tests weren't quite working yet.

**Pull request merged**
