### PR TITLE
fix pretty print sourcemap files

### PR DESCRIPTION
**Pull request by bomsy**
Associated Issue: #1661
- If no source map files are found, we enable  minified file for pretty printing.

### Summary of Changes

* Add new actions and reducers for missing source maps

### CODE REVIEW

**Comment by jasonLaster** [comment]
Hmm. Maybe add a test for this in actions/test/sources?

**Comment by jasonLaster** [comment]
Hmm, @bomsy i'd like to see if we can avoid adding a new action if we can.

Here's an opinionated refactor where the `newSource` action checks to see if it can load original sources. If not, then it clears it's sources sourceMapURL

https://gist.github.com/jasonLaster/e24b8955d1605304f497520bf5b201ad

**Comment by bomsy** [comment]
Good point! Cool will play with this and see.

**Comment by clarkbw** [comment]
Anything I can do to help out here @bomsy?

**Comment by bomsy** [comment]
Hey yeah ... made the changes @jasonLaster suggested, it broke a couple of tests. Would love to pair with you or @jasonLaster to fix the tests. Finding them a bit tricky.

**Comment by jasonLaster** [comment]
I'm closing this now so we can focus on the march 6th release. Lets pick it up afterwards

**Comment by tromey** [comment]
For anyone planning to resurrect this patch - I am not sure that changing the source map worker in this way is best.  This behavior is relied on by the toolbox to avoid reporting the same source map error multiple times.

Instead, if `fetchSourceMap` fails, then `getOriginalURLs` will report an error.  This can be caught and used.  *However*, the toolbox installs a proxy that reports these errors and returns a non-rejected promise; so an M-C change would be needed as well.

**Comment by bomsy** [comment]
@tromey really good to know, thanks! Will love to discuss more, to get the best possible solution.

**Pull request closed without merging**
