### PR TITLE
[scopes] Add another original scope line mapping test.

### PR DESCRIPTION
**Pull request by loganfsmyth**
Refs Issue: #5561

### Summary of Changes

* Add one more test to show that we fall back to generated scopes

### CODE REVIEW

**Comment by jasonLaster** [comment]
i just saw a false positive travis run, lets be careful before merging

**Comment by darkwing** [comment]
@jasonLaster Let's talk about this Monday; we can read the code super carefully but tests are a huge part of green light; should we run Travis multiple times or do so more locally?

**Comment by darkwing** [comment]
The cited build was green but didn't complete propertly so I've kicked it

**Comment by jasonLaster** [comment]
Hmm, this is showing an early error, which i think we fixed on travis...
screen shot 2018-05-07 at 3 34 01 pm

**Comment by jasonLaster** [comment]
I'm going to gamble and say it is alright... if i'm wrong we can revert

**Pull request merged**
