### PR TITLE
Fixes #7656 - Remove absolute positioning in directory view of sources pane

### LINKED ISSUE #7656: [sources] Workers break the directory root layout
STR:

1. debug a page with workers 
2. right click on a directory in the source tree and select "project directory"

NOTE: the launchpad cannot currently find workers, so you might need to fake it by telling the source tree there are workers

```diff
diff --git a/src/components/PrimaryPanes/SourcesTree.js b/src/components/PrimaryPanes/SourcesTree.js
index 86386a844..cd5a9ca20 100644
--- a/src/components/PrimaryPanes/SourcesTree.js
+++ b/src/components/PrimaryPanes/SourcesTree.js
@@ -416,7 +416,7 @@ const mapStateToProps = (state, props) => {
     sources: getRelativeSourcesForThread(state, thread),
     sourceCount: getSourceCount(state, props.thread),
     worker: getWorkerByThread(state, thread),
-    workerCount: getWorkerCount(state)
+    workerCount: 2//getWorkerCount(state)
   };
 };
```

screen shot 2019-01-04 at 12 15 05 pm

### PR DESCRIPTION
**Pull request by Regaddi**
Fixes #7656 

### Summary of Changes

* Removed absolute positioning for elements in the source directory tree view
* Moved projectRootHeader to PrimaryPane so it's rendered only once
* Adjusted some margins when project root is set
* Moved tests related to custom project roots from SourcesTree to PrimaryPanes component
* Updated tests and snapshots accordingly

### Test Plan

Tell us a little a bit about how you tested your patch.

Example test plan:

- [x] Launch Debugger locally using `yarn start`
- [x] Launch Firefox
- [x] Open up https://firefox-dev.tools/debugger-examples/examples/workers/shared.html in launched Firefox instance
- [x] Apply this patch locally

```
diff --git a/src/components/PrimaryPanes/SourcesTree.js b/src/components/PrimaryPanes/SourcesTree.js
index faf139b8..bc5d3cdf 100644
--- a/src/components/PrimaryPanes/SourcesTree.js
+++ b/src/components/PrimaryPanes/SourcesTree.js
@@ -332,9 +332,9 @@ class SourcesTree extends Component<Props, State> {
   renderThreadHeader() {
     const { worker, workerCount } = this.props;

-    if (!features.windowlessWorkers || workerCount == 0) {
-      return null;
-    }
+    // if (!features.windowlessWorkers || workerCount == 0) {
+    //   return null;
+    // }

     if (worker) {
       return (
```
- [x] Debug the tab from Launchpad
- [x] Right click on `firefox-dev.tools` in the Sources pane and select `Set directory root`
- [x] Elements don't overlay each other anymore

### Demo

Without specified root dir:
grafik

Selecting `assets/build` as root dir:
grafik

`assets/build` as selected root dir:
grafik

### CODE REVIEW

**Comment by darkwing** [comment]
I'm seeing the following after building:

nosources

anotherexample


@jasonLaster How do you feel about not showing thread groups that don't have sources?

Also, I'm not seeing the thread headings, oddly enough.

**Comment by darkwing** [comment]
I had a local change actually; let me try this one more time...

**Comment by darkwing** [comment]
Yep, can confirm the issue still exists without my modifications:

nosources2

Maybe there's a missing pref check for windowless workers?

**Comment by jasonLaster** [comment]
@darkwing 👍 . Lets stop rendering a source tree if the thread doesn't have any visible sources.

**Comment by Regaddi** [comment]
> Lets stop rendering a source tree if the thread doesn't have any visible sources.

@jasonLaster This means removing entirely these lines in [SourcesTree.js](https://github.com/Regaddi/debugger.html/blob/7656-fix-custom-root-layout-with-workers/src/components/PrimaryPanes/SourcesTree.js#L331-L335), correct?

```javascript
    if (this.isEmpty()) {
      return this.renderPane(
        this.renderEmptyElement(L10N.getStr("sources.noSourcesAvailable"))
      );
    }
```

**Comment by jasonLaster** [comment]
looks good to me!

**Comment by darkwing** [comment]
This is excellent!  Thank you @Regaddi !

**Review by darkwing — APPROVED** [review]

**Pull request merged**
