### PR TITLE
update 11-07-2017

### PR DESCRIPTION
**Pull request by codehag**

### CODE REVIEW

**Comment by jasonLaster** [comment]
screen shot 2017-11-07 at 12 28 30 pm

**Comment by codehag** [comment]
most of those do not seem like relevant corrections... is there a way to ignore them?

**Comment by jasonLaster** [comment]
yep, you can add the list to `assets/dictionary.txt`

**Comment by jasonLaster** [comment]
Checkout our docs on [spell check](https://github.com/devtools-html/debugger.html/blob/master/docs/pull-requests.md#spell-checking)

**Pull request merged**
