### PR TITLE
Extend babel test

### PR DESCRIPTION
**Pull request by jasonLaster**
it's timing out a bit

### CODE REVIEW

**Comment by codehag** [comment]
Can you please add more information?

**Comment by darkwing** [comment]
What's the next step here?  Can we merge?

**Comment by jasonLaster** [comment]
this PR failed the first time bc the test was too long
https://travis-ci.org/devtools-html/debugger.html/builds/340628175

one other PR failed last week, but passed on a rebuild

**Comment by jasonLaster** [comment]
https://travis-ci.org/devtools-html/debugger.html/builds/341031453?utm_source=github_status&utm_medium=notification

here's one test run

the test is really long btw

**Pull request merged**
