### PR TITLE
debounce the code search with a wait of 250ms

### PR DESCRIPTION
**Pull request by bomsy**
Associated Issue: #968

### Summary of Changes

* Created a new search function which is debounced

### Testing

* [x] passes `npm test`
* [x] passes `npm run lint`

### Screenshots/Videos (OPTIONAL)

debounce-search

### CODE REVIEW

**Comment by jlongster** [comment]
250ms seems a bit long. How did you settle on that number?

**Comment by jlongster** [comment]
We don't even do any network requests when searching, so it's a very quick search.

**Comment by jasonLaster** [comment]
Agreed, although use your judgement when you're playing with it. I'd suggest sticking with something similar to sublime / atom

**Comment by wldcordeiro** [comment]
I'd lean towards 100ms, as I know we coders tend to type pretty quickly so 1/10th of a second seems a bit more sensible than 1/4th of one.

**Comment by bomsy** [comment]
@jlongster Just used 250ms, no particular reasons ... was hoping it would kick of the discussions.  :)
Just dug through the atom source, and they use 100ms, which matches @wldcordeiro recommendation. I would think that feels right, and will go with that. updates coming up!

**Comment by jasonLaster** [comment]
@wldcordeiro 💯 

Thanks @bomsy will merge when CI passes

**Pull request merged**
