### PR TITLE
[breakpoints] Add possible breakpoints positions

### PR DESCRIPTION
**Pull request by jasonLaster**
### Summary of Changes

Adds "possible breakpoints" which are positions that the server says would be good places to place breakpoints. This is something we want for a couple of reasons:

1. when we place a breakpoint we want to know it'll be good
2. we want to know what lines the engine considers empty

### CODE REVIEW

**Comment by darkwing** [comment]
Is this temporary or permanent?  Is this a step toward removing pause points?  My worry is the confusion that now "PossibleBreakpoints" would cause.  Maybe "PossibleBreakPosition" ?

**Comment by jasonLaster** [comment]
this is permanent. when we drop pause points, this will be all that is left

**Comment by darkwing** [comment]
OK, good, that makes sense.  I'd love for us to figure out a better name than "possible breakpoints" though.  "Possible" feels "inexact" or "maybe", and we use "breakpoints" as actual stored breakpoints; maybe we can "Pause positions" instead?  The verbiage just feels a bit shaky.

**Comment by darkwing** [comment]
When I turn on column-breakpoints, clicking on gutters does nothing -- no breakpoint is created.

As part of this PR, maybe we should run breakpoint-centric tests with this pref both on and off.

**Comment by jasonLaster** [comment]
@darkwing we should definitely turn on the pref for the tests soon...

**Comment by darkwing** [comment]
I'm also seeing a white gap between column breakpoints and text when a line i paused; we can fix that with:

```diff
diff --git a/src/components/Editor/ColumnBreakpoints.css b/src/components/Editor/ColumnBreakpoints.css
index 265c7f839..fe8e08bb7 100644
--- a/src/components/Editor/ColumnBreakpoints.css
+++ b/src/components/Editor/ColumnBreakpoints.css
@@ -5,7 +5,7 @@
 .column-breakpoint {
   display: inline;
   padding: 0;
-  margin-inline-end: 4px;
+  padding-inline-end: 4px;
 }
```

**Comment by darkwing** [comment]
Built, tested, working great!  Excellent work @jasonLaster !

**Pull request merged**
