### PR TITLE
Use just an incrementing number rather than fake uuid

### PR DESCRIPTION
**Pull request by wldcordeiro**
@jlongster since we talked on irc.

### CODE REVIEW

**Comment by jlongster** [comment]
Not sure we should change the actual `uuid` module; the point of the name was to make it clear to the user that we didn't have a proper uuid implementation. The only place this is used is `public/js/utils/redux/middleware/promise.js`, so it's probably better to go in there and avoid the uuid module entirely and use an incrementing id. Do you mind doing that instead?

**Comment by wldcordeiro** [comment]
@jlongster if I do that should I just remove the `uuid` module? It'll be unused.

**Comment by jlongster** [comment]
@wldcordeiro yeah, you can try that and see if anything errors. I don't think anything else should be including it.

**Comment by jlongster** [comment]
Looks fine, thanks.

**Pull request merged**
