### PR TITLE
Updated the "skip pausing" button to "Deactivate breakpoints".

### LINKED ISSUE #7360: [breakpoints] update the skip pausing button copy
Currently hovering on the button shows this copy "Skip all pausing". That is kind of a lie because in reality you'll just skip pausing due to breakpoints. Chrome's copy is "Deactivate breakpoints". I think that is a better option.

image

### PR DESCRIPTION
**Pull request by acnair**
Fixes #7360 

Here's the Pull Request Doc
https://firefox-dev.tools/debugger.html/docs/pull-requests.html

### Summary of Changes

*  Replaced "Skip all pausing" with "Deactivate breakpoints" in assets/panel/debugger.properties

### Test Plan

* Ran ```yarn start``` and made sure it was changed to "Deactivate breakpoints". 

Here's the Debugger's Testing doc
https://docs.google.com/document/d/1oBMRxV8A2ag2t22YsQOxTdEv0mXKzIg0tggJjRkU1S0/edit#.
Feel free to improve it!

### Screenshots/Videos (OPTIONAL)

hover

### CODE REVIEW

**Comment by acnair** [comment]
@darkwing @flodolo I read the documentation that @flodolo sent me which said that all the instances have to be changed. So I did a rough search and there were close to 50 places where ``skipPausing`` is used! There are even files and import statements which has ``skipPausing`` so does all the ``skipPausing`` needs to be changed?

**Comment by acnair** [comment]
@darkwing but then how did it work when I ran the debugger? Just curious. 
@flodolo oh! I will look into it. :smile:

**Comment by darkwing** [comment]
My concern here is that we're introducing a new term, "Deactiviate", which could be confusing. 

@jasonLaster:  What about "Skip all debugger pauses"?

**Comment by jasonLaster** [comment]
@darkwing two thoughts:

1. the button is specific to breakpoints. we'll still pause in other circumstances like debugger statements, interrupts, and exceptions
2. deactivate is the term that chrome uses, so consistency might help us

**Comment by digitarald** [comment]
👍 for consistency.

**Pull request merged**
