### PR TITLE
Make source tab's UI and tests consistent in RTL mode

### PR DESCRIPTION
**Pull request by diessica**
Associated Issue: #2791 and #2858

### Summary of Changes

* Improved tab UI vertical alignments and spacing, including **special tabs with icons**.
* Improved Storybook's tab factory: now`document.dir` is configured according. (This one is important, because it was preventing styles from `postcss-bidirection` to apply, so tests weren't consistent.)
* Fixed dropdown alignment.

### Screenshots
Special tabs LTR

Special tabs RTL

Dropdown

### CODE REVIEW

**Comment by jasonLaster** [comment]
hmm, looks like the new tab button is a bit high

**Comment by jasonLaster** [comment]
Thanks for fixing storybook, that's awesome

**Comment by diessica** [comment]
> hmm, looks like the new tab button is a bit high

If you're comparing to the old version, yes, it is, but that's probably because it was very misaligned before. See this:

screencast 2017-05-10 at 6 55 00 pm

Liked it yet? 🙃

**Comment by diessica** [comment]
I've noticed from the last GIF that the icons were a bit shifted to the bottom. Now it's better 👌

**Comment by jasonLaster** [comment]
Thanks @diessica. The screenshots really helped. This looks really good!

**Pull request merged**
