### PR TITLE
(WIP) Add missing tooltips for new tab, close tab and delete breakpoint 

### PR DESCRIPTION
**Pull request by irfanhudda**
Associated Issue: #1424 

I want to get some feedback on whether I'm proceeding in right direction with this. So, I started with adding tooltip for close tab button.

### Summary of Changes

* Adds tooltip to close tab button in source tab.

### TODO
- [x] Add tooltip for close tab
- [x] Add tooltip for new tab
- [x] Add tooltip for delete breakpoint
- [x] Add tooltip for toggle side-pane button

### CODE REVIEW

**Comment by jasonLaster** [comment]
@irfanhudda looks good to me. Keep it up!

**Comment by irfanhudda** [comment]
@jasonLaster I've added tooltips to new tab, close tab, delete breakpoint and toggle side-pane.

I'm not sure what should be tooltip text of new tab button. Let me know if this requires any changes.

**Comment by clarkbw** [comment]
> I'm not sure what should be tooltip text for new tab button. Let me know if this requires any changes.

The new tab is really just opening the search, so use a similar one to search.  Like "Search for sources"

Nice work! 🎉

**Comment by jasonLaster** [comment]
Thanks @irfanhudda! This looks great.

I just merged the changes from wellington's PR recently. And I'll review in a little bit!

**Comment by jasonLaster** [comment]
Thanks so much for the help @irfanhudda 

Thinks for the early PR and the stream of updates. Worked the first time!

**Comment by irfanhudda** [comment]
@jasonLaster and @clarkbw  Thanks for quick suggestions. They helped a lot.

**Pull request merged**
