### PR TITLE
Add syntax highlighting to conditional panel

### LINKED ISSUE #7800: Improve code-styling for conditional breakpoint and logpoint input
When adding a conditional log point, I want to easily identify that the text I am typing is code, so that I don't second guess the behaviour.

Code fields should at least be monospaced, but even better providing syntax highlighting.

image

### PR DESCRIPTION
**Pull request by ravefalcon92**
Fixes #7800 

Please let me know your thoughts and what can be improved. Thank you!

### Summary of Changes

* Used CodeMirror to implement syntax highlighting for the conditional panel. This affects both conditional breakpoints and conditional log points. 
* Deleted code for placeholder/keyDown attributes on the input since the functionality is replaced by the CodeMirror instance

### Test Plan
[x] Added conditional breakpoint condition and saw syntax highlighting was in effect
[x] Edited conditional breakpoint condition and saw syntax highlighting was in effect
[x] Ensured code did not pause when condition was not met
[x] Ensured code paused when condition was met
[x] Removed conditional breakpoint

### Demo

feb-07-2019 14-43-09

### CODE REVIEW

**Comment by darkwing** [comment]
This is...wow!

**Comment by darkwing** [comment]
Travis is bombing because of the following error upon opening the debugger:

```js
JavaScript error: resource://devtools/shared/base-loader.js, line 195: Error: Module `codemirror/index.js` is not found at codemirror/index.js
console.error: (new TypeError("this.panelWin.Debugger is undefined", "resource://devtools/client/debugger/new/panel.js", 36))
```

Looking into it.

**Comment by darkwing** [comment]
@ravefalcon92 It turns out we need to use `SourceEditor` (`src/utils/editor/source-editor.js`) to get CodeMirror working properly in built firefox -- could you look at that and see if you could switch to that API?  It's not too different :) 👍

**Comment by jasonLaster** [comment]
i pushed some tweaks to get the tests to pass. Great work!

**Comment by jasonLaster** [comment]
One challenge i found was supporting horizontal scrolling. ideally the input remains fixed. 

by the way, it might help to temporarily comment out the onBlur code so you can inspect it without it going away...

**Comment by ravefalcon92** [comment]
@jasonLaster, thank you for tweaking the code to pass the tests! 
I've edited the code so that the input stays fixed when scrolling horizontally. 

horizontal_scroll

btw, thanks @darkwing for this [post](https://davidwalsh.name/codemirror-set-focus-line), it was helpful for this PR!

Let me know if there's anything else that needs to be fixed or can be improved.

**Comment by jasonLaster** [comment]
Nope. It works great. I'm thrilled to land this along side log points https://github.com/devtools-html/debugger.html/pull/7811

**Comment by ravefalcon92** [comment]
Sounds good, I'll take a look and see if I can help.

**Pull request merged**
