### PR TITLE
Issue Template

### PR DESCRIPTION
**Pull request by jasonLaster**
It'll be great to point people to resources for filing issues. Especially our slack and now our glitch template

### CODE REVIEW

**Comment by jasonLaster** [comment]
@digitarald @darkwing @bomsy  what do you think?

**Comment by darkwing** [comment]
I'd be much more direct because I don't think many people will take the time to follow the links.  Check out what the A-Frame team has: 

https://github.com/aframevr/aframe/issues/new

Three questions and the entire directive set fits in the default size of the issues textarea element.

**Comment by darkwing** [comment]
I would probably ask:

1.  What are you seeing?
2.  What did you expect to see?
3.  Screenshot of issue, if applicable

**Comment by bomsy** [comment]
I agree with @darkwing, people might find it a bit tasking, jumping back and forth.
A couple of questions which would guide them should be fine.

Here is what the react team's looks like aswell

https://github.com/facebook/react/issues/new

**Comment by darkwing** [comment]
Looks good!

**Pull request merged**
