### PR TITLE
Tracking changes in MC

### PR DESCRIPTION
**Pull request by jbhoosreddy**
_AUTOMATED PULL REQUEST VIA BOT_
 - **M** debugger.html/public/js/lib/devtools/shared/transport/websocket-transport.js
 - **M** debugger.html/public/js/lib/devtools/shared/flags.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/shim/Services.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/redux/middleware/wait-service.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/window.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/undefined.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/text-node.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/stylesheet.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/string.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/reps.css
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/rep.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/rep-utils.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/regexp.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/prop-rep.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/object.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/object-with-url.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/object-with-text.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/number.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/null.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/moz.build
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/grip.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/grip-array.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/function.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/event.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/document.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/date-time.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/caption.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/attribute.js
 - **M** debugger.html/public/js/lib/devtools/client/shared/components/reps/array.js

### CODE REVIEW

**Comment by jbhoosreddy** [comment]
Okay. Short story: The bot is running on AWS EC2 instance. thanks to @jlongster for the idea and the help/suggestions.

I learned a lot of things, and again I wasted some time tinkering around deployment servers, docker, AWS, etc. But I think it'll be worth it if we can be more efficient with it.

I turned off the bot (for now) because I wanted to know if there is a preferred interval for this automated PR action? a couple days, a week? @jasonLaster. Once I know this, I can start it after this PR is merged.

side not: sometimes I wonder if only I run into the most strange issues/hurdles, and then I go on StackOverflow to find that I'm not alone.

**Comment by jasonLaster** [comment]
Thanks @jbhoosreddy! This is really cool and great job getting this setup.

Have you shared a github repo for the project and written up some docs on how to maintain the project? Also, do you think it would be possible to setup the credentials so either James or i could access it as well. Lastly, i'm not sure how much it costs, but maybe we could set it up in a way where it's expensed for.

In terms of preferred interval. I'm curious if you made it possible to avoid duplicate PRs. If so, then I'd opt for something as immediate as possible (10 minutes / 1 hour). If not, then every other day or weekly is fine too.

**Comment by jlongster** [comment]
Awesome work! And yeah, I don't want you to have to pay for EC2. I wouldn't be surprised if Mozilla already had an account there for people to do things like that. It might be worth asking around how we can run it there and charge straight against Mozilla. I also agree that if you can open it up to us at some point, we can help run it.

I don't have a preference for interval; every day or so seems fine to me.

Should probably wait for https://github.com/devtools-html/debugger.html/pull/790 to be closed and then let it check it again.

**Comment by jbhoosreddy** [comment]
> Have you shared a github repo for the project and written up some docs on how to maintain the project?

I just needed to cleanup the code and remove my credentials before making it publicly visible. I have shared it on this GitHub repository: jbhoosreddy/moz-devtools-gitbot. As I said before, I'd definitely like a review on how somethings could be done better. And it's more readable now.

I can definitely set it up so that anyone can have access. I can add full access to all of you on the EC2 instance also. And the logs are mirrored online (when the bot is active).

The thing is that it is not easy to move. I was hoping to make it as simple as pulling a docker image container, but there's simply no automated way to do `hg clone mozilla-central`. So it has to be done manually. Even on the EC2 instance, this command failed when executed manually. So it was some effort to move the mozilla-central codebase to the server.

It's not costing anything right now and it shouldn't for some time. AWS is good for students. So it would be fine if leave it as for now (given what I said above). Especially since we could add more features to it quicker. But yes, we should also look for a place for it to be hosted on for long term.

> In terms of preferred interval. I'm curious if you made it possible to avoid duplicate PRs. 

GitHub API is nice in that it prevents duplicating PRs and also closes existing PRs if new ones are made.

**Comment by clarkbw** [comment]
> I don't want you to have to pay for EC2. I wouldn't be surprised if Mozilla already had an account there for people to do things like that. It might be worth asking around how we can run it there and charge straight against Mozilla

I can look into this.  We can associate one of us with the Mozilla Amazon account to get access to EC2.

**Comment by jlongster** [comment]
@jbhoosreddy can you tell the bot to open a new PR, or how does that work? this is out-of-date now.

**Pull request closed without merging**
