### PR TITLE
issue 3978  replace --theme-content-color3 with --theme-comment at al…

### PR DESCRIPTION
**Pull request by tripurari001**
issue #3978 

replace all the occurrence of `--theme-content-color3` with `--theme-comment` as discussed in issue

### CODE REVIEW

**Comment by jasonLaster** [comment]
CC @ericawright

**Comment by ericawright** [comment]
@tripurari001 can you give me a link to the issue you are referencing?

**Comment by tripurari001** [comment]
@ericawright  referenced the issue #3978

**Comment by ericawright** [comment]
looks good to me too. I spent some time and went through the variables, it seems many are not being used, just a note for future code cleanup.

**Comment by codehag** [comment]
thanks @ericawright !

**Pull request merged**
