### PR TITLE
[SourceTree] Keyboard arrow behaviour integration tests

### PR DESCRIPTION
**Pull request by WenInCode**
Fixes Issue: #6700 

### Summary of Changes
* Adds keyboard integrations tests for source-tree

### Test Plan
- [x] left arrow on a closed directory
- [x] left arrow on an open directory
- [x] left arrow on a source
- [x] right arrow on a closed directory
- [x] right arrow on an open directory
- [x] right arrow on a source
- [x] up arrow on a directory
- [x] up arrow on a source
- [x] down arrow on a directory
- [x] down arrow on a source
- [x] down arrow at the bottom of the tree
- [x] up arrow at the top of the tree

### A few questions
- I wasn't sure if it was okay to add a second `add_task` inside one mochitest file. It looks like it has been done before, but I am not sure if it's not recommended.
- I had some issues knowing _what to wait for_ after triggering a `pressKey`. I made a function that waits for a specific node to gain focus. This does work, but if that test is going to fail and the node won't gain focus, the test will just timeout not giving the best error message. Any idea what I should be waiting for instead?

### CODE REVIEW

**Comment by WenInCode** [comment]
Haha I think that timeout is exactly what happened

**Comment by darkwing** [comment]
Thank you so much for this @WenInCode !  I love it!  We probably want to put this set of tests in a new file; that way we can isolate the `add_task` calls and keep the test suite more focused.

I do see a lot of `TypeError: findElement(...) is null, can't access property "classList" of it`, so we probably need to make `return findElement(dbg, "sourceNode", index).classList` safer.

**Comment by WenInCode** [comment]
I'm having trouble reproducing the failure that's on Travis locally. Do you have any recommendations?

When I run the test with `yarn mochih browser_dbg-sources-arrow-keys` it passes.
I tried copying the command that is run on Travis, `./node_modules/.bin/mochii --ci --mc ./firefox --headless devtools/client/debugger/new`. The tests pass, but a different unrelated test fails. 

I've only worked with CircleCi before, and there I would probably try SSHing in and running the test. I'm not sure if there is an equivalent in Travis, or perhaps a recommended debug flow in these kinds of situations.

**Comment by darkwing** [comment]
A few points:
-  You'll want to back out the `module-manifest` and `yarn.lock` files.
-  90% of the time the tests pass locally, but every so often I get a timeout at `TEST-PASS 2 node is focused`

You may want to try adding this to the top of the test new test script file:

`requestLongerTimeout(5);

**Comment by WenInCode** [comment]
Thanks for the help 😄 . I spent some time looking into why it was getting hung up, and it seemed like the test was not waiting properly following clicking the bottom source in the tree. I removed the changes to the `yarn.lock` and the `module-manifest`

**Pull request merged**
