### PR TITLE
Revert "Revert "[Sources] - fix paddings in sources tree and outline …

### PR DESCRIPTION
**Pull request by jasonLaster**
This brings back the padding fix, which had to be reverted because it broke dbg-sources

### CODE REVIEW

**Comment by jasonLaster** [comment]
Alright - we now know that `onClick` is never received :)

**Comment by jasonLaster** [comment]
Weird i don't see the effect of the grid...

**Comment by jasonLaster** [comment]
CC @martinfojtik lets see if rolling back the grid stuff fixes it... just guessing now. Would love your thoughts here. Also, feel free to open your own PR so you can test what travis is doing too...

this might be a first for me.

**Comment by jasonLaster** [comment]
hmm - this helps the tests go green... can we try and avoid the `display: grid` stuff?

**Comment by martinfojtik** [comment]
We should be able using grid without any problems. If I disable it, there is a problem as you can see on video Gif.
devtools-sources

**Comment by martinfojtik** [comment]
@jasonLaster I just created the same PR with display: grid and all tests passed. Can you try to Rebase your branch? Maybe something from this PR https://github.com/devtools-html/debugger.html/pull/5230 was causing the problem.

**Comment by jasonLaster** [comment]
@martinfojtik i'm not sure - travis wasn't included in your run. try adding an extra comment somewhere to get a different sha...

**Pull request closed without merging**
