### PR TITLE
Add flow coverage to parser/types.js

### PR DESCRIPTION
**Pull request by yalooong**
Fixes Issue: #5707

### Summary of Changes

This PR consists one error message as shown in the screenshot. 

### Screenshots
flow issue

### CODE REVIEW

**Comment by jasonLaster** [comment]
huzzah, i think i had a break through!

This patch breaks a bunch of things, but there isn't a recursion warning. My guess is some how that's related:

```diff
diff --git a/src/workers/parser/index.js b/src/workers/parser/index.js
index 3e50dd8..abf5d16 100644
--- a/src/workers/parser/index.js
+++ b/src/workers/parser/index.js
@@ -44,7 +44,7 @@ export type {

 export type {
   SymbolDeclaration,
-  SymbolDeclarations,
+  // SymbolDeclarations,
   AstLocation,
   AstPosition,
   Scope,
(END)

```

**Comment by jasonLaster** [comment]
I also pushed some more tweaks i found when tightening up the types

**Comment by jasonLaster** [comment]
ping @yalooong. What's your schedule?

**Comment by yalooong** [comment]
I have a test tomorrow morning so I probably get back working on this issue after the test.

**Comment by jasonLaster** [comment]
no worries

**Comment by yalooong** [comment]
I found this part was causing the issue, but I am not sure why. Could you take a look?
It's the line which I commented out in "src/utils/ast.js"

screen shot 2018-03-28 at 19 21 43

**Comment by jasonLaster** [comment]
so... this is shocking :)

**Comment by jasonLaster** [comment]
Thanks, just added a local type definition to avoid it!

Are you in our slack? https://devtools-html-slack.herokuapp.com/

**Comment by jasonLaster** [comment]
alright, i've got some bad news :/

I just did a rebase and a bunch of the issues came back...

**Comment by yalooong** [comment]
I am not invited to join the slack. Could you show me the way? Thanks.

**Comment by jasonLaster** [comment]
Hows it going @yalooong?

**Comment by yalooong** [comment]
@jasonLaster I didn't find a good way to get around with it. Is it ok to prevent the flow checking the functions in ast.js file?

**Comment by jasonLaster** [comment]
hmm, i can check too

**Comment by jasonLaster** [comment]
@yalooong could you push your work with `ast.js` turned off aka no `// @flow`? 

This way I can take a look and try and reduce or fix the issue...

**Comment by yalooong** [comment]
I was thinking of removing the flow coverage from `ast.js` like this:

screen shot 2018-03-31 at 12 34 17

**Comment by jasonLaster** [comment]
@yalooong geez, this is pretty difficult to track down...

I've tried a couple of things:

1. splitting up utils/ast
2. moving all of the types to `src/types`
3. remove SymbolDeclarations usages from non-worker directories

**Comment by jasonLaster** [comment]
i merged #5838 so that we can focus on why the recursion is happening

**Comment by jasonLaster** [comment]
Alright, I think I figured it out... but this was likely the hardest bug to spot this month.

The issue came from this line: https://github.com/yalooong/debugger.html/blob/add-flow/src/utils/ast.js#L26

and had something to do with `identifiers.concat(members, literals)`

**Comment by jasonLaster** [comment]
The code is very much WIP right, but i'll clean it up tomorrow...

**Comment by yalooong** [comment]
@jasonLaster Thanks for sharing the debugging process. I have learned a lot too. I wished I could be more helpful on this bug.

**Pull request merged**
