### PR TITLE
Fix prop-type warnings

### PR DESCRIPTION
**Pull request by ahuth**
Using `PropTypes` from the `React` repo has been deprecated, and there is a `prop-types` package that this project should be using now. This PR brings in that dependency.

Doing so clears up a bunch of deprecation warnings. There are still some more, however, that I haven't been able to track down, yet. Can't find any more cases of this app using `React.PropTypes`, so maybe a dependency is causing the remaining warnings.

Additionally, I've also removed some duplicate entries for dependencies in the package.json and alphabetized them.

### Summary of Changes

* Adds the `prop-types` library as a dependency
* Imports the library where prop types are used
* Removed duplicate package.json dependencies
* Alphabatized package.json dependencies

### Test Plan

Ran the tests, which are green.

### CODE REVIEW

**Comment by ahuth** [comment]
Interesting. Something failed on Travis that didn't fail locally. Will debug.

**Comment by jasonLaster** [comment]
@ahuth I don't think it's you. we just added this test...

```
TEST-START browser_dbg-wasm-sourcemaps.js
   Adding a new tab with URL: http://example.com/browser/devtools/client/debugger/new/test/mochitest/examples/doc-wasm-sourcemaps.html
   Waiting for thread event 'paused' to fire.
 onPacket threw an exception: Error: Server did not specify an actor, dropping packet: {"error":"unknownError","message":"error occurred while processing 'prototypeAndProperties: Error: Object grip requested while not paused.\nStack: pauseObjectGrip@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/script.js:1748:13\ncreateValueGrip@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/object.js:2375:14\ncreateValueGrip@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/script.js:1725:29\n_propertyDescriptor@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/object.js:542:22\nonPrototypeAndProperties@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/object.js:308:29\nonPacket@resource://devtools/shared/base-loader.js -> resource://devtools/server/main.js:1792:15\nreceiveMessage@resource://devtools/shared/base-loader.js -> resource://devtools/shared/transport/transport.js:761:7\nLine: 1748, column: 13"}
 Stack: onPacket@resource://devtools/shared/base-loader.js -> resource://devtools/shared/client/main.js:953:9
 send/<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/transport/transport.js:570:13
 exports.makeInfallible/<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:109:14
 DevToolsUtils.executeSoon*exports.executeSoon@resource://devtools/shared/base-loader.js -> resource://devtools/shared/DevToolsUtils.js:57:19
 send@resource://devtools/shared/base-loader.js -> resource://devtools/shared/transport/transport.js:563:9
 send@resource://devtools/shared/base-loader.js -> resource://devtools/server/main.js:1514:5
 receiveMessage@resource://devtools/shared/base-loader.js -> resource://devtools/shared/transport/transport.js:761:7
 Line: 953, column: 9
  Console Error
    pauseObjectGrip@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/script.js:1748:13\ncreateValueGrip@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/object.js:2375:14\ncreateValueGrip@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/script.js:1725:29\n_propertyDescriptor@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/object.js:542:22\nonPrototypeAndProperties@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/object.js:308:29\nonPacket@resource://devtools/shared/base-loader.js -> resource://devtools/server/main.js:1792:15\nreceiveMessage transport.js:761:7\nLine  1748, column: 13"}
    onPacket main.js 953:9
    send/< transport.js 570:13
    exports.makeInfallible/< ThreadSafeDevToolsUtils.js 109:14
    DevToolsUtils.executeSoon*exports.executeSoon DevToolsUtils.js 57:19
    send transport.js 563:9
    send main.js 1514:5
    receiveMessage transport.js 761:7
 Line: 953, column: 9
   Console message: [JavaScript Error: "error occurred while processing 'prototypeAndProperties: Error: Object grip requested while not paused.
Stack: pauseObjectGrip@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/script.js:1748:13
createValueGrip@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/object.js:2375:14
createValueGrip@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/script.js:1725:29
_propertyDescriptor@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/object.js:542:22
onPrototypeAndProperties@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/object.js:308:29
onPacket@resource://devtools/shared/base-loader.js -> resource://devtools/server/main.js:1792:15
receiveMessage@resource://devtools/shared/base-loader.js -> resource://devtools/shared/transport/transport.js:761:7
Line: 1748, column: 13" {file: "resource://devtools/shared/base-loader.js -> resource://devtools/server/main.js" line: 1655}]
   Thread event 'paused' fired.
 TEST-PASS top frame's source is selected -
 TEST-PASS Line is highlighted as paused -
 TEST-PASS expression is highlighted as paused -
 TEST-UNEXPECTED-FAIL head.js:426 - Error: Unable to find source: wasm
sourcemaps/average.c
  Stack trace
   findSource head.js 426:11
   addBreakpoint head.js 555:12
    browser_dbg-wasm-sourcemaps.js 14:9
   Async*Tester_execTest/< browser-test.js 807:21
   Tester_execTest browser-test.js 798:9
   Tester.prototype.nextTest</< browser-test.js 697:9
   SimpleTest.waitForFocus/waitForFocusInner/focusedOrLoaded/< SimpleTest.js 795:59
```

**Comment by jasonLaster** [comment]
Just triggered a re-build. Lets see if the test passes.

**Comment by jasonLaster** [comment]
Great work @ahuth thanks for cleaning up our package.json

**Comment by ahuth** [comment]
No problem. Thanks!

**Pull request merged**
