### PR TITLE
[WIP] Makes parser recognize Angular

### PR DESCRIPTION
**Pull request by lukaszsobek**
Associated Issue: #5526

- Adds logic to test against Angular files
- Adds tests for angular 1 and undefined
- Adds & renames fixture files

- [ ] Add recognizing later versions of angular

### CODE REVIEW

**Comment by nyrosmith** [comment]
I don't think this will work for ng2 +

**Comment by lukaszsobek** [comment]
@nyrosmith I think we have to write different tests for different versions of angular then. Right we seem to have 2,4 and 5 ...

**Comment by jasonLaster** [comment]
do we want to add support to other versions here or another PR?

**Comment by lukaszsobek** [comment]
@jasonLaster as we discussed adding the next versions is dependent on being able to parse decorators, which is a whole other issue. I think wrapping up this PR and introducing Angular 1 support is beneficial over waiting for another issue to be implemented only to be able to expand this issue.

**Pull request merged**
