### PR TITLE
Tree blur

### PR DESCRIPTION
**Pull request by roieu**
Associated Issue: #2053 

### Summary of Changes

* Added Blurred style for Source node in SourcesTree
* Adjusted render parameters for ManagedTree sub components

### Test Plan

Tested manually using SourcesTree component from devtools-html/debugger.html

Example test plan:

- Focus in and out SourcesTree from various use-cases

Here's the Debugger's Testing doc
https://docs.google.com/document/d/1oBMRxV8A2ag2t22YsQOxTdEv0mXKzIg0tggJjRkU1S0/edit#.
Feel free to improve it!

### Screenshots/Videos (OPTIONAL)

tree-blur

### CODE REVIEW

**Comment by jasonLaster** [comment]
Thanks! I'm traveling today and will be able to review when I'm back on Wednesday

**Comment by roieu** [comment]
@jasonLaster have a safe trip back. 
Note that there's another PR on devtools-core [https://github.com/devtools-html/devtools-core/pull/259](url) that needs to be pulled in order to support the enhancement.
Thanks!
Roie.

**Comment by jasonLaster** [comment]
adding blurred makes me concerned that we could be making things more difficult for ourselves in the future:  

* blurred could be a state for many elements
* blurred/focused might not be weird in some cases - an element is not focused, but it is blurred

I would like to better understand how atom does it. I started looking at their HTML:
One thing I do like is that it uses `::before` for the background which is nice

**Comment by jasonLaster** [comment]
closing this now as it's gone stale, but we can revisit it at any point

**Pull request closed without merging**
