### PR TITLE
Make the source tab hover effects feel more responsive

### PR DESCRIPTION
**Pull request by darkwing**
This is just a rough proposal.  My opinion is that the tab hover transitions are slow and appear labored.  The labored feeling is due to speed, so I drastically sped up the transitions and they seem much more quick and elegant.

I know the project has loads of transitions so I guess I'd like to hear some opinions on this faster effect and see if we'd like to speed things up globally.

### CODE REVIEW

**Comment by codehag** [comment]
hi @darkwing! thanks for the proposal, do you happen to have a screencap of the change?

**Comment by codehag** [comment]
hm...now that i think about it, i guess showing transitions with gifs doesnt work all that well.. 🤔 ill pull and take a look in a little bit!

**Comment by wldcordeiro** [comment]
@darkwing When I was implementing the `Modal` transition, I was pointed to this document http://design.firefox.com/photon/motion/motion.html Using the curve and `150ms` would be a good transition time I think.

**Comment by darkwing** [comment]
Updated to .15s.  Still think the lower speed seems nicer but branding is important.

**Pull request merged**
