### PR TITLE
(WIP) File search style outline matches

### PR DESCRIPTION
**Pull request by monicau**
Associated Issue: #1111

### Summary of Changes

* Change selected match to yellow
* Lighten the match outlines

### Test Plan

- [ ] Ctrl + F to see the search matches

### Screenshots

debugger-file-search

debugger-file-search-dark

### CODE REVIEW

**Comment by monicau** [comment]
This is a WIP.  I'm having trouble changing the text color of the highlighted text in the dark theme.  In dark-theme.css I tried setting the text color in the same class that affects the highlight but it doesn't seem to work:
```
.cm-s-mozilla .CodeMirror-selected {
background: rgb(255, 255, 0);
color: rgb(0, 0, 0);
}
```
When I inspect element, the selected text has classes `cm-overlay cm-selecting`, so do the other matches in the document.  Oddly the currently selected match doesn't have  the class `CodeMirror-selected` or any other classes to differentiate itself from the other matches in the file.. so I'm kinda stumped.

**Comment by jasonLaster** [comment]
@helenvholmes mind taking a quick look at this?

**Comment by jasonLaster** [comment]
Thanks @monicau for the help styling the background color and outline for matches.

I just looked into styling the highlighted element's color and **it is hard** to do with codemirror's api. I mean really hard.

You probably know this, but the yellow overlay is an element absolutely positioned on top of the matched text... and there's no CSS class for the currently highlighted matched text...

* Another problem I noticed is that the matched text is already styled differently and doesn't look great.  This happened before your PR.

* one other observation, your garrish yellow background makes it easier to read the selected matches than the grey.

With all of that mentioned, I think what you have is an improvement and we can fix the matched text color in another issue.


Here's a GIF of the matched color problem:

**Comment by jasonLaster** [comment]
@helenvholmes I think this PR makes sense landing and then we can update the styles in M-C. What do you think?

**Comment by jasonLaster** [comment]
this should help here: https://github.com/devtools-html/debugger.html/pull/1318

it could also give us a good class to match on

**Comment by jasonLaster** [comment]
Thanks @monicau!

I spoke with @helenvholmes offline and we'll update the m-c versions of these files

**Comment by monicau** [comment]
Awesome, thanks @jasonLaster!

**Comment by jasonLaster** [comment]
Hey @monicau! 

I just realized you might not have gotten the invite to our new [slack] channel! 

[slack]: https://devtools-html-slack.herokuapp.com/

**Pull request merged**
