### PR TITLE
Convert Footer.js to ES6 class

### PR DESCRIPTION
**Pull request by kristoforusrp**
Associated Issue: #1890

### Summary of Changes

* Convert Footer.js

This is my first-time contribution to open source project, please correct me if there is a mistake. I will happy to make it right.

### CODE REVIEW

**Comment by jasonLaster** [comment]
Thanks for the help @krishnagopinath. These PRs make a huge difference

**Comment by kristoforusrp** [comment]
@jasonLaster are the message above for me or it is for Krishnagopinath? I've tested the debugger and test the footer. Should I send the screenshot here?

**Comment by jasonLaster** [comment]
Sorry :)

I replied from my phone. I'll look into why the tests failed when I get to my computer

**Comment by kristoforusrp** [comment]
Nevermind, the test failed in $ ./bin/run-mochitests-docker. 
The failed test are:
* devtools/client/debugger/new/test/mochitest/browser_dbg-breaking.js 
* devtools/client/debugger/new/test/mochitest/browser_dbg-breaking-from-console.js

Please, give me a hint how I could pass this test when You have looked at it. :smile:

**Comment by jasonLaster** [comment]
Fixed a small bug.

You should join our slack https://devtools-html.slack.com :)

**Comment by kristoforusrp** [comment]
Happily to joined the Slack channel, Please Invite me.

**Comment by jasonLaster** [comment]
Oops, wrong link: https://devtools-html-slack.herokuapp.com

**Comment by jasonLaster** [comment]
Thanks @kristoforusrp

**Comment by kristoforusrp** [comment]
You're welcome @jasonLaster

**Pull request merged**
