### PR TITLE
[Sources] - fix paddings in sources tree and outline list

### PR DESCRIPTION
**Pull request by martinfojtik**
This reverts commit https://github.com/devtools-html/debugger.html/commit/b892892a0768e96f64df7b2ab3509da75029bb84.

### CODE REVIEW

**Comment by jasonLaster** [comment]
just a reminder that we need display grid here: 
https://user-images.githubusercontent.com/7465851/35499833-5834f524-04d4-11e8-99ea-9e641f25dec0.gif

**Comment by wldcordeiro** [comment]
Did this somehow skip Travis?

**Comment by martinfojtik** [comment]
@wldcordeiro yes, its because I have false positive abuse detection for my PR, I already sent a message to TravisCI, I hope they fix that.

**Comment by jasonLaster** [comment]
@martinfojtik what OS are you using? I can't reproduce on my mac...

**Comment by martinfojtik** [comment]
@wldcordeiro thanks, with your tweaks I don't see vertical scroller and test are not passing. Do you know why?

**Comment by jasonLaster** [comment]
yep - this flexbox approach seems to make the tree the width of the window

**Comment by jasonLaster** [comment]
just rebased to see if that fixed our mochitest problem tho

**Comment by jasonLaster** [comment]
Huzzah @wldcordeiro @martinfojtik i think this was a specificity thing. We needed the `.node`!

**Comment by martinfojtik** [comment]
@jasonLaster good job

**Pull request merged**
