### PR TITLE
Added license header in assets/images/disable-pausing.svg #6986

### LINKED ISSUE #6986: Missing license header in assets/images/disable-pausing.svg
For consistency's sake and as a follow-up to https://github.com/devtools-html/debugger.html/issues/4869 each SVG image should have a MPL license header.

Header format:
https://www.mozilla.org/en-US/MPL/headers/

Missing one in:
`assets/images/disable-pausing.svg`

### PR DESCRIPTION
**Pull request by nightwarrior-xxx**
Fixes #6986 
Added license header in assets/images/disable-pausing.svg
Feel free to suggest changes
Regards,
@nightwarrior-xxx

### CODE REVIEW

**Comment by nightwarrior-xxx** [comment]
Hi 
I am a newbie and wanted to contribute to this project of Mozilla 
Please review this PR and suggest changes
Regard,
@nightwarrior-xxx

**Comment by darkwing** [comment]
Awesome!  Thank you so much @nightwarrior-xxx !

**Comment by nightwarrior-xxx** [comment]
Also @darkwing  since I am new to this project can you refer me any sources from where I can learn to contribute more in this awesome project.

**Comment by nightwarrior-xxx** [comment]
Hi 
I am a newbie and wanted to contribute to this project of Mozilla 
Please review this PR and suggest changes
Regard,
@nightwarrior-xxx

**Comment by darkwing** [comment]
Of course, @nightwarrior-xxx !  Try any of these issues :)

https://github.com/devtools-html/debugger.html/labels/good%20first%20issue

https://github.com/devtools-html/debugger.html/labels/help%20wanted

**Pull request merged**
