### PR TITLE
ExtJS recognition for call stack collapsing

### PR DESCRIPTION
**Pull request by Eccenux**
### Summary of Changes

* added Sencha/ExtJS logo (should be close enough for an icon and not close enough for copyright)
* added recognition of ExtJS builds urls.

This is similar to #2868. Just another framework.

### Test Plan
- [x] Open debugger
- [x] Go to https://jsfiddle.net/eccenux/Ls8c48n3/
- [x] Click on "Click me!" button.
- [x] Open call stack panel.

ExtJS is collapsed.

### CODE REVIEW

**Comment by Eccenux** [comment]
Hm... I think I chocked `yarn lint-js`, but the RegExp `/\/ext-all[\.\-]/` is valid and accurate.
- [x] `/\/ext-all[\.\-]/.test('/ext-all.js')` -> true
- [x] `/\/ext-all[\.\-]/.test('/ext-al-debug.js')` -> true
- [x] `/\/ext-all[\.\-]/.test('/external.js')` -> false
- [x] `/\/ext-all[\.\-]/.test('/complexterminal.js')` -> false

**Comment by jasonLaster** [comment]
Thanks @Eccenux! The patch looks good. Mind sharing a before/after screenshot or perhaps GIF?

**Comment by jasonLaster** [comment]
minor lint issue, which i can fix up

**Comment by codehag** [comment]
Fixed linter issue! @jasonLaster

**Comment by codehag** [comment]
Here is a screenshot: 
screen shot 2017-05-15 at 3 49 21 pm

**Comment by codehag** [comment]
@Eccenux Hi! I do not see the logo (but the rest looks like it is working, great work)! I think it might be due to the file being generated by inkscape. Any ideas?

**Comment by Eccenux** [comment]
@codehag Not sure what is going on. The SVG displays fine in my Firefox. But I simplified the file and modified units. I'm guessing different units and possibly some extra namespaces Inkscape is using might cause problems.

**Comment by codehag** [comment]
Beautiful! great work!
screen shot 2017-05-22 at 3 59 22 pm

**Pull request merged**
