### PR TITLE
[Breakpoints] can't set breakpoint in prettified source

### PR DESCRIPTION
**Pull request by NickMalt**
Associated Issue: #1989 

### Summary of Changes
Unsuccessfully trying to reproduce bug in mochitest. Everything seems ok 🤔 . 
Can anyone play with it? Do I need to change something in STR?

### CODE REVIEW

**Comment by jasonLaster** [comment]
Thanks @NickMalt, definitely a great start! Try using the inline script with the funky `%0A  `

**Comment by jasonLaster** [comment]
Hey @NickMalt, here is an HTML test case w/ the crazy `%0A` new lines...

https://bug1327713.bmoattachments.org/attachment.cgi?id=8822992

I just tested and i think i was able to reproduce the bug

**Comment by NickMalt** [comment]
After some debugging I think that I caught this bug:

1) Here we send correct parameters but got `{ line: null, column: null }`.  Which is why breakpoint flashing. https://github.com/devtools-html/debugger.html/blob/223d35a570d4762000c736e00e5a16b09c9ae8c6/src/utils/source-maps.js#L17-L20

2) [Here](https://dxr.mozilla.org/mozilla-central/source/devtools/client/shared/source-map/worker.js?q=const+%7B+line%2C+column+%7D+%3D+map.generatedPositionFor%28%7B&redirect_type=single#674) we handle this request in source-map worker. But [_findSourceIndex](https://dxr.mozilla.org/mozilla-central/source/devtools/client/shared/source-map/worker.js#2912) return `-1` as if this source did not exist.
￼
image
image


3) The problem is in property `sourceUrl` mismatch.
This one we send to worker:
image
This one we have in worker: 
image
And we have this mismatch because of path [normalization](https://dxr.mozilla.org/mozilla-central/source/devtools/client/debugger/new/parser-worker.js#28487) in [worker](https://dxr.mozilla.org/mozilla-central/source/devtools/client/shared/source-map/worker.js#2474)
image

4) And if we add this patch to [normalize function](https://dxr.mozilla.org/mozilla-central/source/devtools/client/debugger/new/parser-worker.js#28487), everything works ok.
image

### Before/After
bp before
bp after



@jasonLaster The question is, how to properly change normalize function? I’m probably miss something, because do not see the whole picture.

And how should I continue this? I mean how to contibute to `mozila-central`?

**Comment by jasonLaster** [comment]
Nice hunting!

**Comment by jasonLaster** [comment]
Hey @NickMalt, great analysis I think you're right about how we're escaping the source url.

The normalize function comes from this file: https://github.com/mozilla/source-map/blob/master/lib/util.js in the mozilla source-map lib.

I think we can probably change how we create the URL in the debugger so it's not escaped... not sure where though.

**Comment by jasonLaster** [comment]
Hey how's it going?

**Pull request closed without merging**
