### PR TITLE
[breakpoints] Fix syncing cases with toggling

### PR DESCRIPTION
**Pull request by jasonLaster**
Fixes Issue:  #5570 

### Summary of Changes

addresses the syncing issues, which would come about when enabling a breakpoint after the code has moved.

### Test Plan

followed case #1 in this [doc](https://docs.google.com/document/d/1VDSyP4N2WPlmbi1s3ZiJWm9_HBB4nOsngZaeX1lH81s/edit).

### CODE REVIEW

**Comment by darkwing** [comment]
I tested this and found the following:

missing

The breakpoint is there in the editor but doesn't display in the sidebar.

**Comment by darkwing** [comment]
The breakpoint that was enabled, however, did move as expected!  Nice!

**Comment by darkwing** [comment]
I'm a complete and total disaster this Monday morning...I did this on master.  Rechecking :(

**Comment by darkwing** [comment]
I followed the STR and I'm still seeing the same result in panel; the disabled breakpoint doesn't display in the right column and the breakpoints didn't shift with the empty lines -- still at the original line.

**Comment by jasonLaster** [comment]
hmm, lets do a call and look together

**Pull request merged**
