### PR TITLE
Re-search when a new source is selected

### PR DESCRIPTION
**Pull request by arthur801031**
#966

### CODE REVIEW

**Comment by jasonLaster** [comment]
Thanks @arthur801031!

I just tried it locally and it works smoothly.

I took a shot at cleaning up some of the code, but I'm not sure if I got it right because there are some weird issues as I type with keys being dropped lol

https://gist.github.com/jasonLaster/3354799646a76927f817282fd8871c2b

Would you mind taking a look at this and letting me know what you think? 

I'd also be happy to merge your patch as is and then clean up some of the searching behavior.

**Comment by jasonLaster** [comment]
Hmm, looks like we're having some mochitest failures. Shouldn't be a big issue, i'll run locally in a little big

**Comment by arthur801031** [comment]
@jasonLaster 

1. We need `this.props.sourceText.get("text") != undefined ` because  `this.props.sourceText.get("text")` would be undefined when you open a new file tab, which would throw an error when getting "text".

2. We need `const count = countMatches(query, this.props.sourceText.get("text")); this.setState({ count: count, index: 0 });` because we need to update the count of text that match the query for the tab you're selecting.

3. I have made the changes that you suggested from line 24~30 and line 38~46 (https://gist.github.com/jasonLaster/3354799646a76927f817282fd8871c2b)

Thank you! :)

**Comment by jasonLaster** [comment]
Ah, all good points.

I'm sorry i did not have a chance to look at the failing tests today. I got caught up working on #1295 and #1294. Unfortunately, I'll be busy over the next couple days doing thanksgivingy things, but I'll get back to this soon.

**Comment by jasonLaster** [comment]
Ahh, just looked at the failing test and found the bug:

```
JavaScript error: resource://devtools/client/debugger/new/bundle.js, line 48484: TypeError: this.props.sourceText is undefined

1089 INFO Console message: [JavaScript Error: "TypeError: this.props.sourceText is undefined" {file: "resource://devtools/client/debugger/new/bundle.js" line: 48484}]

1090 INFO TEST-UNEXPECTED-FAIL | devtools/client/debugger/new/test/mochitest/browser_dbg_keyboard-shortcuts.js | Test timed out - 
```

I pushed a fix and hopefully this will be green soon and we can merge. In the future, it's possible to grep the mochitest output for unexpected fail and javascript error. and often you'll find the problem in the sea of text!

**Pull request merged**
