### PR TITLE
Shortcuts style tweak

### PR DESCRIPTION
**Pull request by samuel-peers**
Associated Issue: #4122

### Summary of Changes

Tiny style changes suggested by @violasong

### Mac
whatever

### Windows
whatever

### CODE REVIEW

**Comment by jasonLaster** [comment]
Thanks it's looking a lot better. Can we try a couple of style tweaks like the box around the keys. Also I think the wider two column UI could be nice.

If you want to try only doing the box around keys on mac we can do something in App.js (`navigator.userAgent.indexOf('Mac OS X') != -1`) where we add a `mac` class to the `.debugger` element.

**Comment by samuel-peers** [comment]
you got it bro. There are travis tests failing again :/ `failed test:  devtools/client/debugger/new/test/mochitest/browser_dbg-wasm-sourcemaps.js`

**Comment by jasonLaster** [comment]
sweet. that test ain't you. we're on it

**Comment by samuel-peers** [comment]
### Mac
whatever_mac

### Windows
whatever_pc

**Comment by jasonLaster** [comment]
also some other small things:

1. we should add a shortcut for launching it `cmd+/` i think
2. we should move K+ to the right and soften the color (whatever the accordion headers are)
3. the section headers in the mocks looked pretty nice. Lets do some small typography cleanup.

**Comment by samuel-peers** [comment]
stacked

**Comment by jasonLaster** [comment]
I'll make a new issue for the follow up CSS changes and some of the meetup new comers can work on it

**Pull request merged**
