### PR TITLE
refactored loading states & added loading in outline

### PR DESCRIPTION
**Pull request by Rohanhacker**
- [x] Refactor the loading state of symbols #5554
- [x] Should show a loading message in outline #5267
- [ ] Fix/Add tests

### CODE REVIEW

**Comment by Rohanhacker** [comment]
Work in progress

**Comment by jasonLaster** [comment]
Thanks @Rohanhacker

**Comment by jasonLaster** [comment]
the unit tests look like they're pointing out another use case for loading which is cool

src/utils/breakpoint/astBreakpointLocation

my guess is that the integration tests are saying the same thing

**Comment by jasonLaster** [comment]
I think Quick Open now also needs to the loading flag. So a rebase is probably in order.

@Rohanhacker do you have time to finish this up?

**Comment by Rohanhacker** [comment]
@jasonLaster will rebase. I'll try to finish this up by weekend. Is that okay ?

**Comment by jasonLaster** [comment]
That's cool. 

One of us might jump in sooner w/ a quick fix, but yeah weekend is good

**Comment by darkwing** [comment]
Hello @Rohanhacker!  I'd do the rebase for you but you've made your commits on master, and me making changes to that would cause problems.  Are you familiar with git branches?  That would allow us to help more moving forward. :)

**Comment by Rohanhacker** [comment]
yup can work with that

**Comment by Rohanhacker** [comment]
retest this please

**Comment by jasonLaster** [comment]
@Rohanhacker can you re-open this PR w/ a new branch?

**Comment by Rohanhacker** [comment]
@jasonLaster created a new pr

**Pull request closed without merging**
