### PR TITLE
[Sources] Show original sources next to generated

### PR DESCRIPTION
**Pull request by joshunger**

### CODE REVIEW

**Comment by darkwing** [comment]
Looked at this briefly and seeing two issues:

- The URL appears to be odd 
- Clicking on Hello.js spurs another Hello.js

weirdurl

Will be looking at this again shortly.

**Comment by joshunger** [comment]
@darkwing thanks let me know if you want me to debug into it

**Comment by jasonLaster** [comment]
@darkwing is it possible to only prepend `:original` in the component side like maybe in a selector or in the sourceTree:getPath... that might scope it down... tough to say though

**Comment by darkwing** [comment]
Hello @joshunger ; as we talked about this morning, we have a bit of maintenance work we need to do with the SourcesTree before we attack this.  You can feel free to experiment with it but it may be best to hold off for the moment.

I'm going to close this PR but will likely refer to its awesome start in the future; feel free to re-open if you make good progress!

**Pull request closed without merging**
