### PR TITLE
Adding close button to code search bar

### PR DESCRIPTION
**Pull request by akhillb**
Associated Issue: #929 
### Summary of Changes
- Adds close button to search bar

### CODE REVIEW

**Comment by jasonLaster** [comment]
Mind sharing a screen shot? I'm thinking about the size of the close button

**Comment by jasonLaster** [comment]
Hi @akhillb, I just took a look and this is off to a good start.

I found two things:
1) the branch needs a rebase. Afterwards, it'll be helpful to run `npm install`
2) I think the styling of the search bar could be improved. I took a stab at styling it here. The gist is that the close button should fit the search bar (width:16px, color: comment-alt *i think*). It might be helpful to add a close-button size prop, that way by default it could be size small, but in this case we pass down size large and it is styled appropriately.

**Comment by akhillb** [comment]
@jasonLaster sorry i was busy yesterday. Thanks for the input. I will make these changes and get back to you with the new code in a day or two.

**Comment by wldcordeiro** [comment]
Since the searchbar is a flex container you could apply an `align-self: center` to the button and get the vertical centering easy @akhillb.

I do like the idea of having some kind of size prop on the close button that corresponds to a CSS class for the different sizes. Personally I think the colors should stay as is to keep the visual consistency across the other close buttons but that isn't too big of a deal.

**Comment by jasonLaster** [comment]
ping @akhillb - here are some updated designs with the close button

https://projects.invisionapp.com/share/AY8OEG3C6#/screens/117937554_Debugger

feel free to disregard the button for search all files.

**Comment by jasonLaster** [comment]
ping @akhillb. What's your schedule like? I'd be happy to pick this up if you're busy.

**Comment by wldcordeiro** [comment]
Just renamed to make it more clear which search bar. 😄 I'm working on the file search UX currently.

**Comment by akhillb** [comment]
@jasonLaster I am on a vacation now. Will be back on this by tomorrow.

**Comment by akhillb** [comment]
Setting the margin-right property would mess up the alignment of close button in the file search bar. So i was thinking maybe we could have two different classes for close button, one for file search and other for code search, instead of setting values by a function.

**Comment by jasonLaster** [comment]
@akhillb that sounds good to me. I don't mind having a `large` and `small` class for the close button.

**Comment by wldcordeiro** [comment]
@jasonLaster We could add a `buttonClass` prop on the `CloseButton` that could optionally take an additional class for when you override things.

**Comment by jasonLaster** [comment]
Thanks for the help @akhillb. This work is being finished up in #1135

**Pull request closed without merging**
