### PR TITLE
Start spider monkey docs

### PR DESCRIPTION
**Pull request by jasonLaster**
Should help give debugger devs some tips on getting started with spidermonkey

- where the code is
- how to build a shell
- how to run the tests

### CODE REVIEW

**Comment by darkwing** [comment]
We should consider removing lint-md....

**Comment by wooorm** [comment]
Heya! 👋 How can I help?

**Comment by xtuc** [comment]
Isn't it the same as https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey?

**Comment by jasonLaster** [comment]
@xtuc im hoping it serves a different audience. At the moment, it might just be me :)

**Comment by xtuc** [comment]
Sorry I didn't expand what I meant. You could avoid the duplicated content/maintenance.

**Pull request merged**
